// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"time"
)

const TableNameCgzKnowledgeInfoHis = "cgz_knowledge_info_his"

// CgzKnowledgeInfoHis 初高中知识点信息更新历史记录表
type CgzKnowledgeInfoHis struct {
	ID             int       `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true;comment:主键id" json:"id"`       // 主键id
	CourseType     int       `gorm:"column:course_type;type:int(11);comment:科目" json:"course_type"`                              // 科目
	CatalogueID    int       `gorm:"column:catalogue_id;type:int(11);comment:(catalogue.id)" json:"catalogue_id"`                // (catalogue.id)
	Name           string    `gorm:"column:name;type:varchar(200);comment:知识点名称" json:"name"`                                    // 知识点名称
	Pid            int       `gorm:"column:pid;type:int(11);comment:上级Id" json:"pid"`                                            // 上级Id
	Pname          string    `gorm:"column:pname;type:varchar(500);comment:上级名称" json:"pname"`                                   // 上级名称
	CreateTime     int       `gorm:"column:create_time;type:int(11);comment:录入时间" json:"create_time"`                            // 录入时间
	ItemCount      int       `gorm:"column:item_count;type:int(11);comment:题目数量" json:"item_count"`                              // 题目数量
	OrderNum       int       `gorm:"column:order_num;type:int(11);comment:排序" json:"order_num"`                                  // 排序
	ZtID           int       `gorm:"column:zt_id;type:int(11);comment:所属专题Id" json:"zt_id"`                                      // 所属专题Id
	ZtName         string    `gorm:"column:zt_name;type:varchar(200);comment:所属专题名称" json:"zt_name"`                             // 所属专题名称
	Ktype          int16     `gorm:"column:ktype;type:smallint(6);comment:知识点/所属节点类型：1学，2练" json:"ktype"`                        // 知识点/所属节点类型：1学，2练
	KnowledgeCount int       `gorm:"column:knowledge_count;type:int(11);comment:知识点数量" json:"knowledge_count"`                   // 知识点数量
	ZtlCount       int       `gorm:"column:ztl_count;type:int(11);comment:专题下练数量" json:"ztl_count"`                              // 专题下练数量
	UpdateTime     time.Time `gorm:"column:update_time;type:datetime;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName CgzKnowledgeInfoHis's table name
func (*CgzKnowledgeInfoHis) TableName() string {
	return TableNameCgzKnowledgeInfoHis
}
