// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

const TableNameStcExamVideoTestUserLog = "stc_exam_video_test_user_log"

// StcExamVideoTestUserLog 随堂测用户做题记录
type StcExamVideoTestUserLog struct {
	ID           int    `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true;comment:主键id" json:"id"` // 主键id
	UID          int    `gorm:"column:uid;type:int(11);comment:uid" json:"uid"`                                       // uid
	TestCataID   int    `gorm:"column:test_cata_id;type:int(11);comment:随堂测目录Id（理论上与视频一对一）" json:"test_cata_id"`      // 随堂测目录Id（理论上与视频一对一）
	ExerciseID   int    `gorm:"column:exercise_id;type:int(11);comment:试题Id(exercise.id)" json:"exercise_id"`         // 试题Id(exercise.id)
	CourseType   int    `gorm:"column:course_type;type:int(11);comment:科目" json:"course_type"`                        // 科目
	Seconds      int    `gorm:"column:seconds;type:int(11);comment:耗时(秒)" json:"seconds"`                             // 耗时(秒)
	Answer       string `gorm:"column:answer;type:varchar(1000);comment:用户答案" json:"answer"`                          // 用户答案
	Correct      int16  `gorm:"column:correct;type:smallint(1);comment:答案正确" json:"correct"`                          // 答案正确
	CreateTime   int    `gorm:"column:create_time;type:int(11);comment:录入时间" json:"create_time"`                      // 录入时间
	PaperID      int    `gorm:"column:paper_id;type:int(11);comment:用户试卷记录Id" json:"paper_id"`                        // 用户试卷记录Id
	Vid          string `gorm:"column:vid;type:varchar(50);comment:关联技巧讲解视频" json:"vid"`                              // 关联技巧讲解视频
	Category     int    `gorm:"column:category;type:int(2);comment:课程分类" json:"category"`                             // 课程分类
	State        string `gorm:"column:state;type:varchar(500);comment:做题情况：1不会" json:"state"`                         // 做题情况：1不会
	StepImgCount int8   `gorm:"column:step_img_count;type:tinyint(1);comment:解题步骤图片数量" json:"step_img_count"`         // 解题步骤图片数量
	Offline      int8   `gorm:"column:offline;type:tinyint(4);comment:线下题" json:"offline"`                            // 线下题
	Source       int    `gorm:"column:source;type:int(1);comment:来源：0用户触发生成，1工具生成" json:"source"`                     // 来源：0用户触发生成，1工具生成
}

// TableName StcExamVideoTestUserLog's table name
func (*StcExamVideoTestUserLog) TableName() string {
	return TableNameStcExamVideoTestUserLog
}
