// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"time"
)

const TableNameSysUserCourseDeleted = "sys_user_course_deleted"

// SysUserCourseDeleted mapped from table <sys_user_course_deleted>
type SysUserCourseDeleted struct {
	ID                int       `gorm:"column:id;type:int(10) unsigned;not null;comment:主键ID" json:"id"`                                                                      // 主键ID
	UID               int       `gorm:"column:uid;type:int(10);not null;comment:UID" json:"uid"`                                                                              // UID
	GetType           int       `gorm:"column:get_type;type:int(10);not null;comment:获取课程方式：0 直接购买。1 激活码获得" json:"get_type"`                                                  // 获取课程方式：0 直接购买。1 激活码获得
	CourseType        int       `gorm:"column:course_type;type:int(10);not null;default:1;comment:课程类型 1.中考数学。2.中考英语。3.高考英语。4.高考数学。5.高考地理。6.高考政治。7.高考历史。" json:"course_type"` // 课程类型 1.中考数学。2.中考英语。3.高考英语。4.高考数学。5.高考地理。6.高考政治。7.高考历史。
	CreateTime        int       `gorm:"column:create_time;type:int(11);comment:激活码创建时间" json:"create_time"`                                                                   // 激活码创建时间
	ExpireTime        int       `gorm:"column:expire_time;type:int(11);comment:到期时间" json:"expire_time"`                                                                      // 到期时间
	LearnLimit        int       `gorm:"column:learn_limit;type:int(11);comment:学习时长限时（秒）" json:"learn_limit"`                                                                 // 学习时长限时（秒）
	LearnDuration     int       `gorm:"column:learn_duration;type:int(11);comment:累计学习时长（秒）" json:"learn_duration"`                                                           // 累计学习时长（秒）
	SaoleiOrderOpened int8      `gorm:"column:saolei_order_opened;type:tinyint(1);comment:放开扫雷卷按顺序完成" json:"saolei_order_opened"`                                             // 放开扫雷卷按顺序完成
	LearnDays         int       `gorm:"column:learn_days;type:int(11);comment:累计学习天数" json:"learn_days"`                                                                      // 累计学习天数
	LatestLearnDate   time.Time `gorm:"column:latest_learn_date;type:date;comment:最后学习日期" json:"latest_learn_date"`                                                           // 最后学习日期
	Deleted           int16     `gorm:"column:deleted;type:smallint(6);comment:删除" json:"deleted"`                                                                            // 删除
}

// TableName SysUserCourseDeleted's table name
func (*SysUserCourseDeleted) TableName() string {
	return TableNameSysUserCourseDeleted
}
