// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

const TableNameSysExamUserLog = "sys_exam_user_log"

// SysExamUserLog 用户做题记录
type SysExamUserLog struct {
	ID               int    `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true;comment:主键id" json:"id"` // 主键id
	UID              int    `gorm:"column:uid;type:int(11);comment:uid" json:"uid"`                                       // uid
	TestPaperID      int    `gorm:"column:test_paper_id;type:int(11);comment:试卷Id(catalogue.id)" json:"test_paper_id"`    // 试卷Id(catalogue.id)
	ExerciseID       int    `gorm:"column:exercise_id;type:int(11);comment:试题Id(exercise.id)" json:"exercise_id"`         // 试题Id(exercise.id)
	Seconds          int    `gorm:"column:seconds;type:int(11);comment:耗时(秒)" json:"seconds"`                             // 耗时(秒)
	Answer           string `gorm:"column:answer;type:varchar(1000);comment:答案" json:"answer"`                            // 答案
	Correct          int16  `gorm:"column:correct;type:smallint(1);comment:答案正确" json:"correct"`                          // 答案正确
	CreateTime       int    `gorm:"column:create_time;type:int(11);comment:录入时间" json:"create_time"`                      // 录入时间
	ParentID         int    `gorm:"column:parent_id;type:int(11);comment:用户试卷记录Id" json:"parent_id"`                      // 用户试卷记录Id
	ResetAt          int    `gorm:"column:reset_at;type:int(11);comment:重置时间" json:"reset_at"`                            // 重置时间
	State            string `gorm:"column:state;type:varchar(500);comment:做题情况：1不会" json:"state"`                         // 做题情况：1不会
	StepImgCount     int8   `gorm:"column:step_img_count;type:tinyint(1);comment:解题步骤图片数量" json:"step_img_count"`         // 解题步骤图片数量
	Offline          int8   `gorm:"column:offline;type:tinyint(4);comment:线下题" json:"offline"`                            // 线下题
	JyfsCorrectCount int    `gorm:"column:jyfs_correct_count;type:int(8);comment:举一反三正确数量" json:"jyfs_correct_count"`     // 举一反三正确数量
}

// TableName SysExamUserLog's table name
func (*SysExamUserLog) TableName() string {
	return TableNameSysExamUserLog
}
