// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"time"
)

const TableNameSysCourseVideoDayLogs = "sys_course_video_day_logs"

// SysCourseVideoDayLogs 技巧干货每日记录
type SysCourseVideoDayLogs struct {
	ID         int64     `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:主键id" json:"id"` // 主键id
	UID        int       `gorm:"column:uid;type:int(11);not null;comment:用户" json:"uid"`                                  // 用户
	Ymd        time.Time `gorm:"column:ymd;type:date;not null;comment:日期" json:"ymd"`                                     // 日期
	CourseType int       `gorm:"column:course_type;type:int(4);not null;comment:订单项id" json:"course_type"`                // 订单项id
	Vid        string    `gorm:"column:vid;type:varchar(50);not null;comment:视频Id" json:"vid"`                            // 视频Id
	CreateTime int       `gorm:"column:create_time;type:int(11);not null;comment:记录时间" json:"create_time"`                // 记录时间
	Duration   int       `gorm:"column:duration;type:int(11);not null;comment:停留时长" json:"duration"`                      // 停留时长
	UpdateTime int       `gorm:"column:update_time;type:int(11);not null;comment:最后更新时间" json:"update_time"`              // 最后更新时间
}

// TableName SysCourseVideoDayLogs's table name
func (*SysCourseVideoDayLogs) TableName() string {
	return TableNameSysCourseVideoDayLogs
}
