// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"time"
)

const TableNameSysUserEducation = "sys_user_education"

// SysUserEducation mapped from table <sys_user_education>
type SysUserEducation struct {
	UID        int       `gorm:"column:uid;type:int(11);primaryKey;comment:关联的用户ID" json:"uid"`     // 关联的用户ID
	Grade      int       `gorm:"column:grade;type:int(2);not null;comment:年级" json:"grade"`         // 年级
	SchoolName string    `gorm:"column:schoolName;type:varchar(50);comment:学校名称" json:"schoolName"` // 学校名称
	ExamYear   int       `gorm:"column:examYear;type:int(6);comment:参加中高考的年份" json:"examYear"`      // 参加中高考的年份
	Province   int       `gorm:"column:province;type:int(11);comment:考试所在省份" json:"province"`       // 考试所在省份
	City       int       `gorm:"column:city;type:int(11);comment:考试所在城市" json:"city"`               // 考试所在城市
	UpdateTime time.Time `gorm:"column:updateTime;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updateTime"`
}

// TableName SysUserEducation's table name
func (*SysUserEducation) TableName() string {
	return TableNameSysUserEducation
}
