// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

const TableNameSysMessagePush = "sys_message_push"

// SysMessagePush mapped from table <sys_message_push>
type SysMessagePush struct {
	TemplateID      int    `gorm:"column:template_id;type:int(11);primaryKey;autoIncrement:true;comment:模板id" json:"template_id"` // 模板id
	TemplateType    string `gorm:"column:template_type;type:varchar(255);not null;comment:模板类型" json:"template_type"`             // 模板类型
	TemplateTitle   string `gorm:"column:template_title;type:varchar(50);not null;comment:模板编号" json:"template_title"`            // 模板编号
	TemplateContent string `gorm:"column:template_content;type:text;not null;comment:模板名称" json:"template_content"`               // 模板名称
	IsEnable        int    `gorm:"column:is_enable;type:int(11);not null;comment:是否开启" json:"is_enable"`                          // 是否开启
	ModifyTime      int    `gorm:"column:modify_time;type:int(11);comment:更新时间" json:"modify_time"`                               // 更新时间
	NotifyType      string `gorm:"column:notify_type;type:varchar(255);not null;comment:通知人类型" json:"notify_type"`                // 通知人类型
	WebsiteID       int    `gorm:"column:website_id;type:int(11);not null;comment:实例信息" json:"website_id"`                        // 实例信息
	SignItem        string `gorm:"column:sign_item;type:varchar(255);not null;comment:签名值" json:"sign_item"`                      // 签名值
	Sample          string `gorm:"column:sample;type:varchar(255)" json:"sample"`
	Type            int    `gorm:"column:type;type:int(11);not null;comment:1为分销2为全球分红3为区域分红4为团队分红5为直播6为电子卡密7定向送券" json:"type"` // 1为分销2为全球分红3为区域分红4为团队分红5为直播6为电子卡密7定向送券
}

// TableName SysMessagePush's table name
func (*SysMessagePush) TableName() string {
	return TableNameSysMessagePush
}
