// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

const TableNameSysAddonsCategory = "sys_addons_category"

// SysAddonsCategory 插件分类表
type SysAddonsCategory struct {
	CategoryID   int    `gorm:"column:category_id;type:int(11);primaryKey;autoIncrement:true" json:"category_id"`
	CategoryName string `gorm:"column:category_name;type:varchar(50);not null" json:"category_name"`
	Sort         int    `gorm:"column:sort;type:int(11)" json:"sort"`
	CreateTime   int    `gorm:"column:create_time;type:int(11);comment:分类添加时间" json:"create_time"` // 分类添加时间
	UpdateTime   int    `gorm:"column:update_time;type:int(11);comment:分类修改时间" json:"update_time"` // 分类修改时间
}

// TableName SysAddonsCategory's table name
func (*SysAddonsCategory) TableName() string {
	return TableNameSysAddonsCategory
}
