// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

const TableNameSysNoticeTemplateType = "sys_notice_template_type"

// SysNoticeTemplateType 通知模板类型
type SysNoticeTemplateType struct {
	TypeID       int    `gorm:"column:type_id;type:int(11);primaryKey;autoIncrement:true" json:"type_id"`
	TemplateName string `gorm:"column:template_name;type:varchar(50);not null;comment:模板名称" json:"template_name"` // 模板名称
	TemplateCode string `gorm:"column:template_code;type:varchar(50);not null;comment:模板编号" json:"template_code"` // 模板编号
	TemplateType string `gorm:"column:template_type;type:varchar(50);not null;comment:模板类型" json:"template_type"` // 模板类型
	NotifyType   string `gorm:"column:notify_type;type:varchar(255);not null;comment:通知人类型" json:"notify_type"`   // 通知人类型
	WebsiteID    int    `gorm:"column:website_id;type:int(11);not null;comment:实例信息" json:"website_id"`           // 实例信息
	Sort         int    `gorm:"column:sort;type:int(11);not null" json:"sort"`
	Sample       string `gorm:"column:sample;type:varchar(255)" json:"sample"`
	IsPlatform   int8   `gorm:"column:is_platform;type:tinyint(4);default:1;comment:是否平台使用" json:"is_platform"` // 是否平台使用
	SmsType      int8   `gorm:"column:sms_type;type:tinyint(4);comment:1验证码2短信通知" json:"sms_type"`              // 1验证码2短信通知
}

// TableName SysNoticeTemplateType's table name
func (*SysNoticeTemplateType) TableName() string {
	return TableNameSysNoticeTemplateType
}
