// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

const TableNameSysAlbumPicture = "sys_album_picture"

// SysAlbumPicture 相册图片表
type SysAlbumPicture struct {
	PicID         int    `gorm:"column:pic_id;type:int(10) unsigned;primaryKey;autoIncrement:true;comment:相册图片表id" json:"pic_id"` // 相册图片表id
	WebsiteID     int    `gorm:"column:website_id;type:int(11);not null;comment:实例信息" json:"website_id"`                          // 实例信息
	ShopID        int    `gorm:"column:shop_id;type:int(11);not null;comment:所属实例id" json:"shop_id"`                              // 所属实例id
	SupplierID    int    `gorm:"column:supplier_id;type:int(11);not null;comment:供应商id(供应商端才有)" json:"supplier_id"`               // 供应商id(供应商端才有)
	AlbumID       int    `gorm:"column:album_id;type:int(10) unsigned;not null;comment:相册id" json:"album_id"`                     // 相册id
	IsWide        int    `gorm:"column:is_wide;type:int(11);not null;comment:是否宽屏" json:"is_wide"`                                // 是否宽屏
	PicName       string `gorm:"column:pic_name;type:varchar(100);not null;comment:图片名称" json:"pic_name"`                         // 图片名称
	PicTag        string `gorm:"column:pic_tag;type:varchar(255);not null;comment:图片标签" json:"pic_tag"`                           // 图片标签
	PicCover      string `gorm:"column:pic_cover;type:varchar(255);not null;comment:原图图片路径" json:"pic_cover"`                     // 原图图片路径
	PicSize       string `gorm:"column:pic_size;type:varchar(255);not null;comment:原图大小" json:"pic_size"`                         // 原图大小
	PicSpec       string `gorm:"column:pic_spec;type:varchar(100);not null;comment:原图规格" json:"pic_spec"`                         // 原图规格
	PicCoverBig   string `gorm:"column:pic_cover_big;type:varchar(255);not null;comment:大图路径" json:"pic_cover_big"`               // 大图路径
	PicSizeBig    string `gorm:"column:pic_size_big;type:varchar(255);not null;default:0;comment:大图大小" json:"pic_size_big"`       // 大图大小
	PicSpecBig    string `gorm:"column:pic_spec_big;type:varchar(100);not null;comment:大图规格" json:"pic_spec_big"`                 // 大图规格
	PicCoverMid   string `gorm:"column:pic_cover_mid;type:varchar(255);not null;comment:中图路径" json:"pic_cover_mid"`               // 中图路径
	PicSizeMid    string `gorm:"column:pic_size_mid;type:varchar(255);not null;default:0;comment:中图大小" json:"pic_size_mid"`       // 中图大小
	PicSpecMid    string `gorm:"column:pic_spec_mid;type:varchar(100);not null;comment:中图规格" json:"pic_spec_mid"`                 // 中图规格
	PicCoverSmall string `gorm:"column:pic_cover_small;type:varchar(255);not null;comment:小图路径" json:"pic_cover_small"`           // 小图路径
	PicSizeSmall  string `gorm:"column:pic_size_small;type:varchar(255);not null;default:0;comment:小图大小" json:"pic_size_small"`   // 小图大小
	PicSpecSmall  string `gorm:"column:pic_spec_small;type:varchar(255);not null;comment:小图规格" json:"pic_spec_small"`             // 小图规格
	PicCoverMicro string `gorm:"column:pic_cover_micro;type:varchar(255);not null;comment:微图路径" json:"pic_cover_micro"`           // 微图路径
	PicSizeMicro  string `gorm:"column:pic_size_micro;type:varchar(255);not null;default:0;comment:微图大小" json:"pic_size_micro"`   // 微图大小
	PicSpecMicro  string `gorm:"column:pic_spec_micro;type:varchar(255);not null;comment:微图规格" json:"pic_spec_micro"`             // 微图规格
	UploadTime    int    `gorm:"column:upload_time;type:int(11);comment:图片上传时间" json:"upload_time"`                               // 图片上传时间
	UploadType    int    `gorm:"column:upload_type;type:int(11);default:1;comment:图片外链" json:"upload_type"`                       // 图片外链
	Domain        string `gorm:"column:domain;type:varchar(255);comment:图片外链" json:"domain"`                                      // 图片外链
	Bucket        string `gorm:"column:bucket;type:varchar(255);comment:存储空间名称" json:"bucket"`                                    // 存储空间名称
}

// TableName SysAlbumPicture's table name
func (*SysAlbumPicture) TableName() string {
	return TableNameSysAlbumPicture
}
