// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

const TableNameVslAttributeValue = "vsl_attribute_value"

// VslAttributeValue 商品属性值
type VslAttributeValue struct {
	AttrValueID   int    `gorm:"column:attr_value_id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:属性值ID" json:"attr_value_id"` // 属性值ID
	AttrValueName string `gorm:"column:attr_value_name;type:varchar(50);not null;comment:属性值名称" json:"attr_value_name"`                       // 属性值名称
	AttrID        int    `gorm:"column:attr_id;type:int(11);not null;comment:属性ID" json:"attr_id"`                                            // 属性ID
	Value         string `gorm:"column:value;type:varchar(1000);not null;comment:属性对应相关数据" json:"value"`                                      // 属性对应相关数据
	Type          int    `gorm:"column:type;type:int(11);not null;default:1;comment:属性对应输入类型1.直接2.单选3.多选" json:"type"`                        // 属性对应输入类型1.直接2.单选3.多选
	Sort          int    `gorm:"column:sort;type:int(11);not null;default:1999;comment:排序号" json:"sort"`                                      // 排序号
	IsSearch      int8   `gorm:"column:is_search;type:tinyint(1);not null;default:1;comment:是否使用" json:"is_search"`                           // 是否使用
	WebsiteID     int    `gorm:"column:website_id;type:int(11);not null;comment:实例信息" json:"website_id"`                                      // 实例信息
	ShopID        int    `gorm:"column:shop_id;type:int(11);not null;comment:店铺id" json:"shop_id"`                                            // 店铺id
	SupplierID    int    `gorm:"column:supplier_id;type:int(11);not null;comment:供应商id" json:"supplier_id"`                                   // 供应商id
}

// TableName VslAttributeValue's table name
func (*VslAttributeValue) TableName() string {
	return TableNameVslAttributeValue
}
