// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

const TableNameVslOrderRefundAccountRecords = "vsl_order_refund_account_records"

// VslOrderRefundAccountRecords 订单退款账户记录
type VslOrderRefundAccountRecords struct {
	ID            int     `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true;comment:主键id" json:"id"`     // 主键id
	OrderGoodsID  int     `gorm:"column:order_goods_id;type:int(11);not null;comment:订单项id" json:"order_goods_id"`          // 订单项id
	RefundTradeNo string  `gorm:"column:refund_trade_no;type:varchar(55);not null;comment:退款交易号" json:"refund_trade_no"`    // 退款交易号
	RefundMoney   float64 `gorm:"column:refund_money;type:decimal(10,2);not null;comment:退款金额" json:"refund_money"`         // 退款金额
	RefundWay     int     `gorm:"column:refund_way;type:int(11);not null;comment:退款方式（1：微信，2：支付宝，10：线下）" json:"refund_way"` // 退款方式（1：微信，2：支付宝，10：线下）
	BuyerID       int     `gorm:"column:buyer_id;type:int(11);not null;comment:买家id" json:"buyer_id"`                       // 买家id
	RefundTime    int     `gorm:"column:refund_time;type:int(11);not null;comment:退款时间" json:"refund_time"`                 // 退款时间
	Remark        string  `gorm:"column:remark;type:varchar(255);comment:备注" json:"remark"`                                 // 备注
	WebsiteID     int     `gorm:"column:website_id;type:int(11);not null;comment:实例信息" json:"website_id"`                   // 实例信息
}

// TableName VslOrderRefundAccountRecords's table name
func (*VslOrderRefundAccountRecords) TableName() string {
	return TableNameVslOrderRefundAccountRecords
}
