// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

const TableNameVslElectroncardBase = "vsl_electroncard_base"

// VslElectroncardBase mapped from table <vsl_electroncard_base>
type VslElectroncardBase struct {
	ID                         int    `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	ElectroncardBaseName       string `gorm:"column:electroncard_base_name;type:varchar(100);not null;comment:卡密库名称" json:"electroncard_base_name"`            // 卡密库名称
	ElectroncardBaseCategoryID int    `gorm:"column:electroncard_base_category_id;type:int(11);not null;comment:卡密库分类id" json:"electroncard_base_category_id"` // 卡密库分类id
	Memo                       string `gorm:"column:memo;type:varchar(1000);not null;comment:备注" json:"memo"`                                                  // 备注
	Description                string `gorm:"column:description;type:varchar(1000);not null;comment:使用说明" json:"description"`                                  // 使用说明
	IsDataDifferent            int8   `gorm:"column:is_data_different;type:tinyint(1);not null;comment:数据去重   0:关闭  1:开启" json:"is_data_different"`            // 数据去重   0:关闭  1:开启
	KeyName                    string `gorm:"column:key_name;type:varchar(1000);not null;comment:字段名，多个字段名用，分隔" json:"key_name"`                               // 字段名，多个字段名用，分隔
	ShopID                     int    `gorm:"column:shop_id;type:int(11);not null;comment:店铺id" json:"shop_id"`                                                // 店铺id
	WebsiteID                  int    `gorm:"column:website_id;type:int(11);not null" json:"website_id"`
	CreateTime                 int    `gorm:"column:create_time;type:int(11);not null;comment:添加时间" json:"create_time"` // 添加时间
}

// TableName VslElectroncardBase's table name
func (*VslElectroncardBase) TableName() string {
	return TableNameVslElectroncardBase
}
