// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

const TableNameVslPartnerMember = "vsl_partner_member"

// VslPartnerMember mapped from table <vsl_partner_member>
type VslPartnerMember struct {
	UID        int    `gorm:"column:uid;type:int(11);primaryKey;autoIncrement:true;comment:经销商后台子账号" json:"uid"` // 经销商后台子账号
	RegTime    int    `gorm:"column:reg_time;type:int(11);not null;comment:注册的时间" json:"reg_time"`               // 注册的时间
	ParentUID  int    `gorm:"column:parent_uid;type:int(11);not null;comment:父级别的 uid" json:"parent_uid"`        // 父级别的 uid
	State      int    `gorm:"column:state;type:int(1);not null;comment:1 正常 2 失效" json:"state"`                  // 1 正常 2 失效
	MemberName string `gorm:"column:member_name;type:varchar(36);not null;comment:用户名" json:"member_name"`       // 用户名
	Pwd        string `gorm:"column:pwd;type:varchar(65);not null;comment:密码" json:"pwd"`                        // 密码
	Remark     string `gorm:"column:remark;type:varchar(255);comment:备注" json:"remark"`                          // 备注
	RealName   string `gorm:"column:real_name;type:varchar(36);comment:真实的姓名" json:"real_name"`                  // 真实的姓名
	Mobile     string `gorm:"column:mobile;type:varchar(11);comment:手机" json:"mobile"`                           // 手机
	RoleID     int    `gorm:"column:role_id;type:int(11);comment:角色的Id" json:"role_id"`                          // 角色的Id
}

// TableName VslPartnerMember's table name
func (*VslPartnerMember) TableName() string {
	return TableNameVslPartnerMember
}
