// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

const TableNameVslMemberGroup = "vsl_member_group"

// VslMemberGroup mapped from table <vsl_member_group>
type VslMemberGroup struct {
	GroupID         int     `gorm:"column:group_id;type:int(10);primaryKey;autoIncrement:true;comment:分组id" json:"group_id"` // 分组id
	GroupName       string  `gorm:"column:group_name;type:varchar(255);not null;comment:分组名" json:"group_name"`              // 分组名
	WebsiteID       int     `gorm:"column:website_id;type:int(10) unsigned;not null" json:"website_id"`
	IsLabel         int8    `gorm:"column:is_label;type:tinyint(2);not null" json:"is_label"`
	LabelCondition  int8    `gorm:"column:label_condition;type:tinyint(2);not null" json:"label_condition"`
	OrderMoney      float64 `gorm:"column:order_money;type:decimal(10,2);not null" json:"order_money"`
	OrderPay        int     `gorm:"column:order_pay;type:int(10);not null" json:"order_pay"`
	Point           int     `gorm:"column:point;type:int(10);not null" json:"point"`
	Balance         float64 `gorm:"column:balance;type:decimal(10,0);not null" json:"balance"`
	GoodsID         int     `gorm:"column:goods_id;type:int(10);not null" json:"goods_id"`
	Labelconditions string  `gorm:"column:labelconditions;type:varchar(255);not null" json:"labelconditions"`
}

// TableName VslMemberGroup's table name
func (*VslMemberGroup) TableName() string {
	return TableNameVslMemberGroup
}
