// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

const TableNameVslOrderDistributorCommission = "vsl_order_distributor_commission"

// VslOrderDistributorCommission mapped from table <vsl_order_distributor_commission>
type VslOrderDistributorCommission struct {
	ID            int     `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	OrderID       int     `gorm:"column:order_id;type:int(11);comment:订单id" json:"order_id"`                // 订单id
	WebsiteID     int     `gorm:"column:website_id;type:int(11);comment:商户id" json:"website_id"`            // 商户id
	OrderGoodsID  int     `gorm:"column:order_goods_id;type:int(11);comment:订单商品id" json:"order_goods_id"`  // 订单商品id
	BuyerID       int     `gorm:"column:buyer_id;type:int(11);comment:买家id" json:"buyer_id"`                // 买家id
	CommissionAID int     `gorm:"column:commissionA_id;type:int(11);comment:一级分销商id" json:"commissionA_id"` // 一级分销商id
	CommissionA   float64 `gorm:"column:commissionA;type:decimal(19,2);comment:一级佣金" json:"commissionA"`    // 一级佣金
	CommissionBID int     `gorm:"column:commissionB_id;type:int(11);comment:二级分销商id" json:"commissionB_id"` // 二级分销商id
	CommissionB   float64 `gorm:"column:commissionB;type:decimal(19,2);comment:二级佣金" json:"commissionB"`    // 二级佣金
	CommissionCID int     `gorm:"column:commissionC_id;type:int(11);comment:三级分销商id" json:"commissionC_id"` // 三级分销商id
	CommissionC   float64 `gorm:"column:commissionC;type:decimal(19,2);comment:三级佣金" json:"commissionC"`    // 三级佣金
	Commission    float64 `gorm:"column:commission;type:decimal(19,2);comment:总佣金" json:"commission"`       // 总佣金
	PointA        int     `gorm:"column:pointA;type:int(11);comment:一级积分" json:"pointA"`                    // 一级积分
	PointB        int     `gorm:"column:pointB;type:int(11);comment:二级积分" json:"pointB"`                    // 二级积分
	PointC        int     `gorm:"column:pointC;type:int(11);comment:三级积分" json:"pointC"`                    // 三级积分
	Point         int     `gorm:"column:point;type:int(11);comment:总积分" json:"point"`                       // 总积分
	ShopID        int     `gorm:"column:shop_id;type:int(11)" json:"shop_id"`
	ReturnStatus  int     `gorm:"column:return_status;type:int(2);comment:是否发生退款" json:"return_status"` // 是否发生退款
	PayStatus     int     `gorm:"column:pay_status;type:int(2);comment:是否支付完成" json:"pay_status"`       // 是否支付完成
	CalStatus     int     `gorm:"column:cal_status;type:int(2);comment:是否已经完成" json:"cal_status"`       // 是否已经完成
}

// TableName VslOrderDistributorCommission's table name
func (*VslOrderDistributorCommission) TableName() string {
	return TableNameVslOrderDistributorCommission
}
