// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

const TableNameVslGoodsDiscount = "vsl_goods_discount"

// VslGoodsDiscount mapped from table <vsl_goods_discount>
type VslGoodsDiscount struct {
	ID         int  `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true;comment:折扣主键id" json:"id"` // 折扣主键id
	GoodsID    int  `gorm:"column:goods_id;type:int(11);not null;comment:商品id" json:"goods_id"`            // 商品id
	Type       int8 `gorm:"column:type;type:tinyint(2);not null;comment:折扣类型 1权限折扣" json:"type"`           // 折扣类型 1权限折扣
	IsUse      int8 `gorm:"column:is_use;type:tinyint(2);not null;comment:是否使用 0未使用 1使用" json:"is_use"`    // 是否使用 0未使用 1使用
	ShopID     int  `gorm:"column:shop_id;type:int(11);not null;comment:店铺id" json:"shop_id"`              // 店铺id
	WebsiteID  int  `gorm:"column:website_id;type:int(11);not null;comment:实例信息" json:"website_id"`        // 实例信息
	CreateTime int  `gorm:"column:create_time;type:int(11);comment:创建时间" json:"create_time"`               // 创建时间
	UpdateTime int  `gorm:"column:update_time;type:int(11);comment:更新时间" json:"update_time"`               // 更新时间
	/*
		折扣json值（根据需求自定义）
		is_user_obj_open：会员是否开启1开2关
		u_is_label：会员取整
		u_discount_choice: 会员折扣方式1打折2固定金额
		u_level_ids：会员等级id
		u_level_vals: 会员等级值

		is_distributor_obj_open：分销商是否开启1开2关
		d_is_label：分销商取整
		d_discount_choice: 分销商折扣方式1打折2固定金额
		d_level_ids：分销商等级id
		d_level_vals: 分销商等级值

		discount_look_obj：浏览权限
		discount_buy_obj：购买权限
		member_level_id：会员等级
		distributor_level_id：分销商等级
		user_group_level_id：会员分组
	*/
	Value       string `gorm:"column:value;type:varchar(2500);comment:折扣json值（根据需求自定义）\nis_user_obj_open：会员是否开启1开2关\nu_is_label：会员取整\nu_discount_choice: 会员折扣方式1打折2固定金额\nu_level_ids：会员等级id\nu_level_vals: 会员等级值\n\nis_distributor_obj_open：分销商是否开启1开2关\nd_is_label：分销商取整\nd_discount_choice: 分销商折扣方式1打折2固定金额\nd_level_ids：分销商等级id\nd_level_vals: 分销商等级值\n\ndiscount_look_obj：浏览权限\ndiscount_buy_obj：购买权限\nmember_level_id：会员等级\ndistributor_level_id：分销商等级\nuser_group_level_id：会员分组" json:"value"`
	BrowseAuthU string `gorm:"column:browse_auth_u;type:varchar(255);comment:商品浏览权限(会员)" json:"browse_auth_u"`   // 商品浏览权限(会员)
	BrowseAuthD string `gorm:"column:browse_auth_d;type:varchar(255);comment:商品浏览权限(分销商)" json:"browse_auth_d"`  // 商品浏览权限(分销商)
	BrowseAuthS string `gorm:"column:browse_auth_s;type:varchar(255);comment:商品浏览权限(会员分组)" json:"browse_auth_s"` // 商品浏览权限(会员分组)
	BuyAuthU    string `gorm:"column:buy_auth_u;type:varchar(255);comment:商品购买权限(会员)" json:"buy_auth_u"`         // 商品购买权限(会员)
	BuyAuthD    string `gorm:"column:buy_auth_d;type:varchar(255);comment:商品购买权限(分销商)" json:"buy_auth_d"`        // 商品购买权限(分销商)
	BuyAuthS    string `gorm:"column:buy_auth_s;type:varchar(255);comment:商品购买权限(会员分组)" json:"buy_auth_s"`       // 商品购买权限(会员分组)
	ChannelAuth string `gorm:"column:channel_auth;type:varchar(255);comment:渠道商权限" json:"channel_auth"`          // 渠道商权限
}

// TableName VslGoodsDiscount's table name
func (*VslGoodsDiscount) TableName() string {
	return TableNameVslGoodsDiscount
}
