server:
  run_mode: debug
  http_port: 8080
  gormLogLevel: 4 # Silent Error Warn Info 1开始
  api_key_for_rpc: "test_api_key"
  api_key_for_sms_rpc: "test_sms_api_key"


fxshop:
  type: mysql
  host: 192.168.1.150
  port: 3306
  username: fx
  password: 123456
  dbname: fxshop
  max_idle_conn: 5
  max_open_conn: 30
  conn_max_lifetime: 60
  replicas:
    - user_fx_readonly:Sec7&plJK8#89ur&an3e#r23!@tcp(192.168.1.150:3306)/fxshop?charset=utf8mb4&parseTime=true

fxshop_sync:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "root"
  dbname: "fxshop_sync"
  max_idle_conn: 5
  max_open_conn: 30
  conn_max_lifetime: 60

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0

jwt:
  secret: "your_jwt_secret"
  expire: 86400

sync:
  token: "MIGfMA0GC*&SqGSIb3DQE%BAQUA"
