// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"exam-api-sync-go/dao/model/fxshop"
)

func newExamErrorExerciseSummary(db *gorm.DB, opts ...gen.DOOption) examErrorExerciseSummary {
	_examErrorExerciseSummary := examErrorExerciseSummary{}

	_examErrorExerciseSummary.examErrorExerciseSummaryDo.UseDB(db, opts...)
	_examErrorExerciseSummary.examErrorExerciseSummaryDo.UseModel(&fxshop.ExamErrorExerciseSummary{})

	tableName := _examErrorExerciseSummary.examErrorExerciseSummaryDo.TableName()
	_examErrorExerciseSummary.ALL = field.NewAsterisk(tableName)
	_examErrorExerciseSummary.ID = field.NewInt64(tableName, "id")
	_examErrorExerciseSummary.UID = field.NewInt(tableName, "uid")
	_examErrorExerciseSummary.CourseType = field.NewInt(tableName, "course_type")
	_examErrorExerciseSummary.ExerciseID = field.NewInt(tableName, "exercise_id")
	_examErrorExerciseSummary.Source = field.NewInt8(tableName, "source")
	_examErrorExerciseSummary.FromStc = field.NewInt8(tableName, "from_stc")
	_examErrorExerciseSummary.FromJyfs = field.NewInt8(tableName, "from_jyfs")
	_examErrorExerciseSummary.TestCount = field.NewInt(tableName, "test_count")
	_examErrorExerciseSummary.CorrectCount = field.NewInt(tableName, "correct_count")
	_examErrorExerciseSummary.ErrorCount = field.NewInt(tableName, "error_count")
	_examErrorExerciseSummary.EmptyCount = field.NewInt(tableName, "empty_count")
	_examErrorExerciseSummary.CorrectRate = field.NewFloat64(tableName, "correct_rate")
	_examErrorExerciseSummary.Mark = field.NewInt8(tableName, "mark")
	_examErrorExerciseSummary.CreateTime = field.NewInt(tableName, "create_time")
	_examErrorExerciseSummary.UpdateTime = field.NewInt(tableName, "update_time")

	_examErrorExerciseSummary.fillFieldMap()

	return _examErrorExerciseSummary
}

// examErrorExerciseSummary 用户举一反三错题统计
type examErrorExerciseSummary struct {
	examErrorExerciseSummaryDo

	ALL          field.Asterisk
	ID           field.Int64   // 主键id
	UID          field.Int     // uid
	CourseType   field.Int     // 科目
	ExerciseID   field.Int     // 试题Id
	Source       field.Int8    // 来源：1扫雷，2随堂测，3举一反三 ，4初高中2024, 5学案,6单元测试
	FromStc      field.Int8    // 来源：1随堂测
	FromJyfs     field.Int8    // 来源：1举一反三
	TestCount    field.Int     // 练习次数
	CorrectCount field.Int     // 正确次数
	ErrorCount   field.Int     // 错误次数
	EmptyCount   field.Int     // 不会次数
	CorrectRate  field.Float64 // 正确率
	Mark         field.Int8    // 星标
	CreateTime   field.Int     // 录入时间
	UpdateTime   field.Int     // 最后更新时间

	fieldMap map[string]field.Expr
}

func (e examErrorExerciseSummary) Table(newTableName string) *examErrorExerciseSummary {
	e.examErrorExerciseSummaryDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e examErrorExerciseSummary) As(alias string) *examErrorExerciseSummary {
	e.examErrorExerciseSummaryDo.DO = *(e.examErrorExerciseSummaryDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *examErrorExerciseSummary) updateTableName(table string) *examErrorExerciseSummary {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.UID = field.NewInt(table, "uid")
	e.CourseType = field.NewInt(table, "course_type")
	e.ExerciseID = field.NewInt(table, "exercise_id")
	e.Source = field.NewInt8(table, "source")
	e.FromStc = field.NewInt8(table, "from_stc")
	e.FromJyfs = field.NewInt8(table, "from_jyfs")
	e.TestCount = field.NewInt(table, "test_count")
	e.CorrectCount = field.NewInt(table, "correct_count")
	e.ErrorCount = field.NewInt(table, "error_count")
	e.EmptyCount = field.NewInt(table, "empty_count")
	e.CorrectRate = field.NewFloat64(table, "correct_rate")
	e.Mark = field.NewInt8(table, "mark")
	e.CreateTime = field.NewInt(table, "create_time")
	e.UpdateTime = field.NewInt(table, "update_time")

	e.fillFieldMap()

	return e
}

func (e *examErrorExerciseSummary) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *examErrorExerciseSummary) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 15)
	e.fieldMap["id"] = e.ID
	e.fieldMap["uid"] = e.UID
	e.fieldMap["course_type"] = e.CourseType
	e.fieldMap["exercise_id"] = e.ExerciseID
	e.fieldMap["source"] = e.Source
	e.fieldMap["from_stc"] = e.FromStc
	e.fieldMap["from_jyfs"] = e.FromJyfs
	e.fieldMap["test_count"] = e.TestCount
	e.fieldMap["correct_count"] = e.CorrectCount
	e.fieldMap["error_count"] = e.ErrorCount
	e.fieldMap["empty_count"] = e.EmptyCount
	e.fieldMap["correct_rate"] = e.CorrectRate
	e.fieldMap["mark"] = e.Mark
	e.fieldMap["create_time"] = e.CreateTime
	e.fieldMap["update_time"] = e.UpdateTime
}

func (e examErrorExerciseSummary) clone(db *gorm.DB) examErrorExerciseSummary {
	e.examErrorExerciseSummaryDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e examErrorExerciseSummary) replaceDB(db *gorm.DB) examErrorExerciseSummary {
	e.examErrorExerciseSummaryDo.ReplaceDB(db)
	return e
}

type examErrorExerciseSummaryDo struct{ gen.DO }

type IExamErrorExerciseSummaryDo interface {
	gen.SubQuery
	Debug() IExamErrorExerciseSummaryDo
	WithContext(ctx context.Context) IExamErrorExerciseSummaryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IExamErrorExerciseSummaryDo
	WriteDB() IExamErrorExerciseSummaryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IExamErrorExerciseSummaryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IExamErrorExerciseSummaryDo
	Not(conds ...gen.Condition) IExamErrorExerciseSummaryDo
	Or(conds ...gen.Condition) IExamErrorExerciseSummaryDo
	Select(conds ...field.Expr) IExamErrorExerciseSummaryDo
	Where(conds ...gen.Condition) IExamErrorExerciseSummaryDo
	Order(conds ...field.Expr) IExamErrorExerciseSummaryDo
	Distinct(cols ...field.Expr) IExamErrorExerciseSummaryDo
	Omit(cols ...field.Expr) IExamErrorExerciseSummaryDo
	Join(table schema.Tabler, on ...field.Expr) IExamErrorExerciseSummaryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IExamErrorExerciseSummaryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IExamErrorExerciseSummaryDo
	Group(cols ...field.Expr) IExamErrorExerciseSummaryDo
	Having(conds ...gen.Condition) IExamErrorExerciseSummaryDo
	Limit(limit int) IExamErrorExerciseSummaryDo
	Offset(offset int) IExamErrorExerciseSummaryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IExamErrorExerciseSummaryDo
	Unscoped() IExamErrorExerciseSummaryDo
	Create(values ...*fxshop.ExamErrorExerciseSummary) error
	CreateInBatches(values []*fxshop.ExamErrorExerciseSummary, batchSize int) error
	Save(values ...*fxshop.ExamErrorExerciseSummary) error
	First() (*fxshop.ExamErrorExerciseSummary, error)
	Take() (*fxshop.ExamErrorExerciseSummary, error)
	Last() (*fxshop.ExamErrorExerciseSummary, error)
	Find() ([]*fxshop.ExamErrorExerciseSummary, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.ExamErrorExerciseSummary, err error)
	FindInBatches(result *[]*fxshop.ExamErrorExerciseSummary, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*fxshop.ExamErrorExerciseSummary) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IExamErrorExerciseSummaryDo
	Assign(attrs ...field.AssignExpr) IExamErrorExerciseSummaryDo
	Joins(fields ...field.RelationField) IExamErrorExerciseSummaryDo
	Preload(fields ...field.RelationField) IExamErrorExerciseSummaryDo
	FirstOrInit() (*fxshop.ExamErrorExerciseSummary, error)
	FirstOrCreate() (*fxshop.ExamErrorExerciseSummary, error)
	FindByPage(offset int, limit int) (result []*fxshop.ExamErrorExerciseSummary, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IExamErrorExerciseSummaryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e examErrorExerciseSummaryDo) Debug() IExamErrorExerciseSummaryDo {
	return e.withDO(e.DO.Debug())
}

func (e examErrorExerciseSummaryDo) WithContext(ctx context.Context) IExamErrorExerciseSummaryDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e examErrorExerciseSummaryDo) ReadDB() IExamErrorExerciseSummaryDo {
	return e.Clauses(dbresolver.Read)
}

func (e examErrorExerciseSummaryDo) WriteDB() IExamErrorExerciseSummaryDo {
	return e.Clauses(dbresolver.Write)
}

func (e examErrorExerciseSummaryDo) Session(config *gorm.Session) IExamErrorExerciseSummaryDo {
	return e.withDO(e.DO.Session(config))
}

func (e examErrorExerciseSummaryDo) Clauses(conds ...clause.Expression) IExamErrorExerciseSummaryDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e examErrorExerciseSummaryDo) Returning(value interface{}, columns ...string) IExamErrorExerciseSummaryDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e examErrorExerciseSummaryDo) Not(conds ...gen.Condition) IExamErrorExerciseSummaryDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e examErrorExerciseSummaryDo) Or(conds ...gen.Condition) IExamErrorExerciseSummaryDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e examErrorExerciseSummaryDo) Select(conds ...field.Expr) IExamErrorExerciseSummaryDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e examErrorExerciseSummaryDo) Where(conds ...gen.Condition) IExamErrorExerciseSummaryDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e examErrorExerciseSummaryDo) Order(conds ...field.Expr) IExamErrorExerciseSummaryDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e examErrorExerciseSummaryDo) Distinct(cols ...field.Expr) IExamErrorExerciseSummaryDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e examErrorExerciseSummaryDo) Omit(cols ...field.Expr) IExamErrorExerciseSummaryDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e examErrorExerciseSummaryDo) Join(table schema.Tabler, on ...field.Expr) IExamErrorExerciseSummaryDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e examErrorExerciseSummaryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IExamErrorExerciseSummaryDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e examErrorExerciseSummaryDo) RightJoin(table schema.Tabler, on ...field.Expr) IExamErrorExerciseSummaryDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e examErrorExerciseSummaryDo) Group(cols ...field.Expr) IExamErrorExerciseSummaryDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e examErrorExerciseSummaryDo) Having(conds ...gen.Condition) IExamErrorExerciseSummaryDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e examErrorExerciseSummaryDo) Limit(limit int) IExamErrorExerciseSummaryDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e examErrorExerciseSummaryDo) Offset(offset int) IExamErrorExerciseSummaryDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e examErrorExerciseSummaryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IExamErrorExerciseSummaryDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e examErrorExerciseSummaryDo) Unscoped() IExamErrorExerciseSummaryDo {
	return e.withDO(e.DO.Unscoped())
}

func (e examErrorExerciseSummaryDo) Create(values ...*fxshop.ExamErrorExerciseSummary) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e examErrorExerciseSummaryDo) CreateInBatches(values []*fxshop.ExamErrorExerciseSummary, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e examErrorExerciseSummaryDo) Save(values ...*fxshop.ExamErrorExerciseSummary) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e examErrorExerciseSummaryDo) First() (*fxshop.ExamErrorExerciseSummary, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.ExamErrorExerciseSummary), nil
	}
}

func (e examErrorExerciseSummaryDo) Take() (*fxshop.ExamErrorExerciseSummary, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.ExamErrorExerciseSummary), nil
	}
}

func (e examErrorExerciseSummaryDo) Last() (*fxshop.ExamErrorExerciseSummary, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.ExamErrorExerciseSummary), nil
	}
}

func (e examErrorExerciseSummaryDo) Find() ([]*fxshop.ExamErrorExerciseSummary, error) {
	result, err := e.DO.Find()
	return result.([]*fxshop.ExamErrorExerciseSummary), err
}

func (e examErrorExerciseSummaryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.ExamErrorExerciseSummary, err error) {
	buf := make([]*fxshop.ExamErrorExerciseSummary, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e examErrorExerciseSummaryDo) FindInBatches(result *[]*fxshop.ExamErrorExerciseSummary, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e examErrorExerciseSummaryDo) Attrs(attrs ...field.AssignExpr) IExamErrorExerciseSummaryDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e examErrorExerciseSummaryDo) Assign(attrs ...field.AssignExpr) IExamErrorExerciseSummaryDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e examErrorExerciseSummaryDo) Joins(fields ...field.RelationField) IExamErrorExerciseSummaryDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e examErrorExerciseSummaryDo) Preload(fields ...field.RelationField) IExamErrorExerciseSummaryDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e examErrorExerciseSummaryDo) FirstOrInit() (*fxshop.ExamErrorExerciseSummary, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.ExamErrorExerciseSummary), nil
	}
}

func (e examErrorExerciseSummaryDo) FirstOrCreate() (*fxshop.ExamErrorExerciseSummary, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.ExamErrorExerciseSummary), nil
	}
}

func (e examErrorExerciseSummaryDo) FindByPage(offset int, limit int) (result []*fxshop.ExamErrorExerciseSummary, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e examErrorExerciseSummaryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e examErrorExerciseSummaryDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e examErrorExerciseSummaryDo) Delete(models ...*fxshop.ExamErrorExerciseSummary) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *examErrorExerciseSummaryDo) withDO(do gen.Dao) *examErrorExerciseSummaryDo {
	e.DO = *do.(*gen.DO)
	return e
}
