// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"exam-api-sync-go/dao/model/fxshop"
)

func newLearnPlanTaskVideo(db *gorm.DB, opts ...gen.DOOption) learnPlanTaskVideo {
	_learnPlanTaskVideo := learnPlanTaskVideo{}

	_learnPlanTaskVideo.learnPlanTaskVideoDo.UseDB(db, opts...)
	_learnPlanTaskVideo.learnPlanTaskVideoDo.UseModel(&fxshop.LearnPlanTaskVideo{})

	tableName := _learnPlanTaskVideo.learnPlanTaskVideoDo.TableName()
	_learnPlanTaskVideo.ALL = field.NewAsterisk(tableName)
	_learnPlanTaskVideo.ID = field.NewInt(tableName, "id")
	_learnPlanTaskVideo.UID = field.NewInt(tableName, "uid")
	_learnPlanTaskVideo.CourseType = field.NewInt(tableName, "course_type")
	_learnPlanTaskVideo.TaskID = field.NewInt(tableName, "task_id")
	_learnPlanTaskVideo.Vid = field.NewString(tableName, "vid")
	_learnPlanTaskVideo.Duration = field.NewInt(tableName, "duration")
	_learnPlanTaskVideo.CreateTime = field.NewInt64(tableName, "create_time")
	_learnPlanTaskVideo.CompleteAt = field.NewInt64(tableName, "complete_at")
	_learnPlanTaskVideo.ResetAt = field.NewInt64(tableName, "reset_at")

	_learnPlanTaskVideo.fillFieldMap()

	return _learnPlanTaskVideo
}

// learnPlanTaskVideo 学案任务技巧干货进度记录
type learnPlanTaskVideo struct {
	learnPlanTaskVideoDo

	ALL        field.Asterisk
	ID         field.Int
	UID        field.Int    // uid
	CourseType field.Int    // 科目
	TaskID     field.Int    // uid
	Vid        field.String // 视频id
	Duration   field.Int    // 学习时长
	CreateTime field.Int64  // 创建时间
	CompleteAt field.Int64  // 完成时间
	ResetAt    field.Int64  // 重置时间

	fieldMap map[string]field.Expr
}

func (l learnPlanTaskVideo) Table(newTableName string) *learnPlanTaskVideo {
	l.learnPlanTaskVideoDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l learnPlanTaskVideo) As(alias string) *learnPlanTaskVideo {
	l.learnPlanTaskVideoDo.DO = *(l.learnPlanTaskVideoDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *learnPlanTaskVideo) updateTableName(table string) *learnPlanTaskVideo {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewInt(table, "id")
	l.UID = field.NewInt(table, "uid")
	l.CourseType = field.NewInt(table, "course_type")
	l.TaskID = field.NewInt(table, "task_id")
	l.Vid = field.NewString(table, "vid")
	l.Duration = field.NewInt(table, "duration")
	l.CreateTime = field.NewInt64(table, "create_time")
	l.CompleteAt = field.NewInt64(table, "complete_at")
	l.ResetAt = field.NewInt64(table, "reset_at")

	l.fillFieldMap()

	return l
}

func (l *learnPlanTaskVideo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *learnPlanTaskVideo) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 9)
	l.fieldMap["id"] = l.ID
	l.fieldMap["uid"] = l.UID
	l.fieldMap["course_type"] = l.CourseType
	l.fieldMap["task_id"] = l.TaskID
	l.fieldMap["vid"] = l.Vid
	l.fieldMap["duration"] = l.Duration
	l.fieldMap["create_time"] = l.CreateTime
	l.fieldMap["complete_at"] = l.CompleteAt
	l.fieldMap["reset_at"] = l.ResetAt
}

func (l learnPlanTaskVideo) clone(db *gorm.DB) learnPlanTaskVideo {
	l.learnPlanTaskVideoDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l learnPlanTaskVideo) replaceDB(db *gorm.DB) learnPlanTaskVideo {
	l.learnPlanTaskVideoDo.ReplaceDB(db)
	return l
}

type learnPlanTaskVideoDo struct{ gen.DO }

type ILearnPlanTaskVideoDo interface {
	gen.SubQuery
	Debug() ILearnPlanTaskVideoDo
	WithContext(ctx context.Context) ILearnPlanTaskVideoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILearnPlanTaskVideoDo
	WriteDB() ILearnPlanTaskVideoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILearnPlanTaskVideoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILearnPlanTaskVideoDo
	Not(conds ...gen.Condition) ILearnPlanTaskVideoDo
	Or(conds ...gen.Condition) ILearnPlanTaskVideoDo
	Select(conds ...field.Expr) ILearnPlanTaskVideoDo
	Where(conds ...gen.Condition) ILearnPlanTaskVideoDo
	Order(conds ...field.Expr) ILearnPlanTaskVideoDo
	Distinct(cols ...field.Expr) ILearnPlanTaskVideoDo
	Omit(cols ...field.Expr) ILearnPlanTaskVideoDo
	Join(table schema.Tabler, on ...field.Expr) ILearnPlanTaskVideoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILearnPlanTaskVideoDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILearnPlanTaskVideoDo
	Group(cols ...field.Expr) ILearnPlanTaskVideoDo
	Having(conds ...gen.Condition) ILearnPlanTaskVideoDo
	Limit(limit int) ILearnPlanTaskVideoDo
	Offset(offset int) ILearnPlanTaskVideoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILearnPlanTaskVideoDo
	Unscoped() ILearnPlanTaskVideoDo
	Create(values ...*fxshop.LearnPlanTaskVideo) error
	CreateInBatches(values []*fxshop.LearnPlanTaskVideo, batchSize int) error
	Save(values ...*fxshop.LearnPlanTaskVideo) error
	First() (*fxshop.LearnPlanTaskVideo, error)
	Take() (*fxshop.LearnPlanTaskVideo, error)
	Last() (*fxshop.LearnPlanTaskVideo, error)
	Find() ([]*fxshop.LearnPlanTaskVideo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.LearnPlanTaskVideo, err error)
	FindInBatches(result *[]*fxshop.LearnPlanTaskVideo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*fxshop.LearnPlanTaskVideo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILearnPlanTaskVideoDo
	Assign(attrs ...field.AssignExpr) ILearnPlanTaskVideoDo
	Joins(fields ...field.RelationField) ILearnPlanTaskVideoDo
	Preload(fields ...field.RelationField) ILearnPlanTaskVideoDo
	FirstOrInit() (*fxshop.LearnPlanTaskVideo, error)
	FirstOrCreate() (*fxshop.LearnPlanTaskVideo, error)
	FindByPage(offset int, limit int) (result []*fxshop.LearnPlanTaskVideo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILearnPlanTaskVideoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l learnPlanTaskVideoDo) Debug() ILearnPlanTaskVideoDo {
	return l.withDO(l.DO.Debug())
}

func (l learnPlanTaskVideoDo) WithContext(ctx context.Context) ILearnPlanTaskVideoDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l learnPlanTaskVideoDo) ReadDB() ILearnPlanTaskVideoDo {
	return l.Clauses(dbresolver.Read)
}

func (l learnPlanTaskVideoDo) WriteDB() ILearnPlanTaskVideoDo {
	return l.Clauses(dbresolver.Write)
}

func (l learnPlanTaskVideoDo) Session(config *gorm.Session) ILearnPlanTaskVideoDo {
	return l.withDO(l.DO.Session(config))
}

func (l learnPlanTaskVideoDo) Clauses(conds ...clause.Expression) ILearnPlanTaskVideoDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l learnPlanTaskVideoDo) Returning(value interface{}, columns ...string) ILearnPlanTaskVideoDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l learnPlanTaskVideoDo) Not(conds ...gen.Condition) ILearnPlanTaskVideoDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l learnPlanTaskVideoDo) Or(conds ...gen.Condition) ILearnPlanTaskVideoDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l learnPlanTaskVideoDo) Select(conds ...field.Expr) ILearnPlanTaskVideoDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l learnPlanTaskVideoDo) Where(conds ...gen.Condition) ILearnPlanTaskVideoDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l learnPlanTaskVideoDo) Order(conds ...field.Expr) ILearnPlanTaskVideoDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l learnPlanTaskVideoDo) Distinct(cols ...field.Expr) ILearnPlanTaskVideoDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l learnPlanTaskVideoDo) Omit(cols ...field.Expr) ILearnPlanTaskVideoDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l learnPlanTaskVideoDo) Join(table schema.Tabler, on ...field.Expr) ILearnPlanTaskVideoDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l learnPlanTaskVideoDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILearnPlanTaskVideoDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l learnPlanTaskVideoDo) RightJoin(table schema.Tabler, on ...field.Expr) ILearnPlanTaskVideoDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l learnPlanTaskVideoDo) Group(cols ...field.Expr) ILearnPlanTaskVideoDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l learnPlanTaskVideoDo) Having(conds ...gen.Condition) ILearnPlanTaskVideoDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l learnPlanTaskVideoDo) Limit(limit int) ILearnPlanTaskVideoDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l learnPlanTaskVideoDo) Offset(offset int) ILearnPlanTaskVideoDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l learnPlanTaskVideoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILearnPlanTaskVideoDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l learnPlanTaskVideoDo) Unscoped() ILearnPlanTaskVideoDo {
	return l.withDO(l.DO.Unscoped())
}

func (l learnPlanTaskVideoDo) Create(values ...*fxshop.LearnPlanTaskVideo) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l learnPlanTaskVideoDo) CreateInBatches(values []*fxshop.LearnPlanTaskVideo, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l learnPlanTaskVideoDo) Save(values ...*fxshop.LearnPlanTaskVideo) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l learnPlanTaskVideoDo) First() (*fxshop.LearnPlanTaskVideo, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.LearnPlanTaskVideo), nil
	}
}

func (l learnPlanTaskVideoDo) Take() (*fxshop.LearnPlanTaskVideo, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.LearnPlanTaskVideo), nil
	}
}

func (l learnPlanTaskVideoDo) Last() (*fxshop.LearnPlanTaskVideo, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.LearnPlanTaskVideo), nil
	}
}

func (l learnPlanTaskVideoDo) Find() ([]*fxshop.LearnPlanTaskVideo, error) {
	result, err := l.DO.Find()
	return result.([]*fxshop.LearnPlanTaskVideo), err
}

func (l learnPlanTaskVideoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.LearnPlanTaskVideo, err error) {
	buf := make([]*fxshop.LearnPlanTaskVideo, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l learnPlanTaskVideoDo) FindInBatches(result *[]*fxshop.LearnPlanTaskVideo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l learnPlanTaskVideoDo) Attrs(attrs ...field.AssignExpr) ILearnPlanTaskVideoDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l learnPlanTaskVideoDo) Assign(attrs ...field.AssignExpr) ILearnPlanTaskVideoDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l learnPlanTaskVideoDo) Joins(fields ...field.RelationField) ILearnPlanTaskVideoDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l learnPlanTaskVideoDo) Preload(fields ...field.RelationField) ILearnPlanTaskVideoDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l learnPlanTaskVideoDo) FirstOrInit() (*fxshop.LearnPlanTaskVideo, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.LearnPlanTaskVideo), nil
	}
}

func (l learnPlanTaskVideoDo) FirstOrCreate() (*fxshop.LearnPlanTaskVideo, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.LearnPlanTaskVideo), nil
	}
}

func (l learnPlanTaskVideoDo) FindByPage(offset int, limit int) (result []*fxshop.LearnPlanTaskVideo, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l learnPlanTaskVideoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l learnPlanTaskVideoDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l learnPlanTaskVideoDo) Delete(models ...*fxshop.LearnPlanTaskVideo) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *learnPlanTaskVideoDo) withDO(do gen.Dao) *learnPlanTaskVideoDo {
	l.DO = *do.(*gen.DO)
	return l
}
