// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"exam-api-sync-go/dao/model/fxshop"
)

func newSysHooks(db *gorm.DB, opts ...gen.DOOption) sysHooks {
	_sysHooks := sysHooks{}

	_sysHooks.sysHooksDo.UseDB(db, opts...)
	_sysHooks.sysHooksDo.UseModel(&fxshop.SysHooks{})

	tableName := _sysHooks.sysHooksDo.TableName()
	_sysHooks.ALL = field.NewAsterisk(tableName)
	_sysHooks.ID = field.NewInt(tableName, "id")
	_sysHooks.Name = field.NewString(tableName, "name")
	_sysHooks.Description = field.NewString(tableName, "description")
	_sysHooks.Type = field.NewInt8(tableName, "type")
	_sysHooks.Addons = field.NewString(tableName, "addons")
	_sysHooks.Status = field.NewInt8(tableName, "status")
	_sysHooks.UpdateTime = field.NewInt(tableName, "update_time")

	_sysHooks.fillFieldMap()

	return _sysHooks
}

type sysHooks struct {
	sysHooksDo

	ALL         field.Asterisk
	ID          field.Int    // 主键
	Name        field.String // 钩子名称
	Description field.String // 描述
	Type        field.Int8   // 类型  1 视图 2 控制器
	Addons      field.String // 钩子挂载的插件 '，'分割
	Status      field.Int8
	UpdateTime  field.Int // 更新时间

	fieldMap map[string]field.Expr
}

func (s sysHooks) Table(newTableName string) *sysHooks {
	s.sysHooksDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysHooks) As(alias string) *sysHooks {
	s.sysHooksDo.DO = *(s.sysHooksDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysHooks) updateTableName(table string) *sysHooks {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt(table, "id")
	s.Name = field.NewString(table, "name")
	s.Description = field.NewString(table, "description")
	s.Type = field.NewInt8(table, "type")
	s.Addons = field.NewString(table, "addons")
	s.Status = field.NewInt8(table, "status")
	s.UpdateTime = field.NewInt(table, "update_time")

	s.fillFieldMap()

	return s
}

func (s *sysHooks) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysHooks) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 7)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["description"] = s.Description
	s.fieldMap["type"] = s.Type
	s.fieldMap["addons"] = s.Addons
	s.fieldMap["status"] = s.Status
	s.fieldMap["update_time"] = s.UpdateTime
}

func (s sysHooks) clone(db *gorm.DB) sysHooks {
	s.sysHooksDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysHooks) replaceDB(db *gorm.DB) sysHooks {
	s.sysHooksDo.ReplaceDB(db)
	return s
}

type sysHooksDo struct{ gen.DO }

type ISysHooksDo interface {
	gen.SubQuery
	Debug() ISysHooksDo
	WithContext(ctx context.Context) ISysHooksDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysHooksDo
	WriteDB() ISysHooksDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysHooksDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysHooksDo
	Not(conds ...gen.Condition) ISysHooksDo
	Or(conds ...gen.Condition) ISysHooksDo
	Select(conds ...field.Expr) ISysHooksDo
	Where(conds ...gen.Condition) ISysHooksDo
	Order(conds ...field.Expr) ISysHooksDo
	Distinct(cols ...field.Expr) ISysHooksDo
	Omit(cols ...field.Expr) ISysHooksDo
	Join(table schema.Tabler, on ...field.Expr) ISysHooksDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysHooksDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysHooksDo
	Group(cols ...field.Expr) ISysHooksDo
	Having(conds ...gen.Condition) ISysHooksDo
	Limit(limit int) ISysHooksDo
	Offset(offset int) ISysHooksDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysHooksDo
	Unscoped() ISysHooksDo
	Create(values ...*fxshop.SysHooks) error
	CreateInBatches(values []*fxshop.SysHooks, batchSize int) error
	Save(values ...*fxshop.SysHooks) error
	First() (*fxshop.SysHooks, error)
	Take() (*fxshop.SysHooks, error)
	Last() (*fxshop.SysHooks, error)
	Find() ([]*fxshop.SysHooks, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.SysHooks, err error)
	FindInBatches(result *[]*fxshop.SysHooks, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*fxshop.SysHooks) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysHooksDo
	Assign(attrs ...field.AssignExpr) ISysHooksDo
	Joins(fields ...field.RelationField) ISysHooksDo
	Preload(fields ...field.RelationField) ISysHooksDo
	FirstOrInit() (*fxshop.SysHooks, error)
	FirstOrCreate() (*fxshop.SysHooks, error)
	FindByPage(offset int, limit int) (result []*fxshop.SysHooks, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysHooksDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysHooksDo) Debug() ISysHooksDo {
	return s.withDO(s.DO.Debug())
}

func (s sysHooksDo) WithContext(ctx context.Context) ISysHooksDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysHooksDo) ReadDB() ISysHooksDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysHooksDo) WriteDB() ISysHooksDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysHooksDo) Session(config *gorm.Session) ISysHooksDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysHooksDo) Clauses(conds ...clause.Expression) ISysHooksDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysHooksDo) Returning(value interface{}, columns ...string) ISysHooksDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysHooksDo) Not(conds ...gen.Condition) ISysHooksDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysHooksDo) Or(conds ...gen.Condition) ISysHooksDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysHooksDo) Select(conds ...field.Expr) ISysHooksDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysHooksDo) Where(conds ...gen.Condition) ISysHooksDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysHooksDo) Order(conds ...field.Expr) ISysHooksDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysHooksDo) Distinct(cols ...field.Expr) ISysHooksDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysHooksDo) Omit(cols ...field.Expr) ISysHooksDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysHooksDo) Join(table schema.Tabler, on ...field.Expr) ISysHooksDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysHooksDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysHooksDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysHooksDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysHooksDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysHooksDo) Group(cols ...field.Expr) ISysHooksDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysHooksDo) Having(conds ...gen.Condition) ISysHooksDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysHooksDo) Limit(limit int) ISysHooksDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysHooksDo) Offset(offset int) ISysHooksDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysHooksDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysHooksDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysHooksDo) Unscoped() ISysHooksDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysHooksDo) Create(values ...*fxshop.SysHooks) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysHooksDo) CreateInBatches(values []*fxshop.SysHooks, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysHooksDo) Save(values ...*fxshop.SysHooks) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysHooksDo) First() (*fxshop.SysHooks, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysHooks), nil
	}
}

func (s sysHooksDo) Take() (*fxshop.SysHooks, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysHooks), nil
	}
}

func (s sysHooksDo) Last() (*fxshop.SysHooks, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysHooks), nil
	}
}

func (s sysHooksDo) Find() ([]*fxshop.SysHooks, error) {
	result, err := s.DO.Find()
	return result.([]*fxshop.SysHooks), err
}

func (s sysHooksDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.SysHooks, err error) {
	buf := make([]*fxshop.SysHooks, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysHooksDo) FindInBatches(result *[]*fxshop.SysHooks, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysHooksDo) Attrs(attrs ...field.AssignExpr) ISysHooksDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysHooksDo) Assign(attrs ...field.AssignExpr) ISysHooksDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysHooksDo) Joins(fields ...field.RelationField) ISysHooksDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysHooksDo) Preload(fields ...field.RelationField) ISysHooksDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysHooksDo) FirstOrInit() (*fxshop.SysHooks, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysHooks), nil
	}
}

func (s sysHooksDo) FirstOrCreate() (*fxshop.SysHooks, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysHooks), nil
	}
}

func (s sysHooksDo) FindByPage(offset int, limit int) (result []*fxshop.SysHooks, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysHooksDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysHooksDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysHooksDo) Delete(models ...*fxshop.SysHooks) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysHooksDo) withDO(do gen.Dao) *sysHooksDo {
	s.DO = *do.(*gen.DO)
	return s
}
