// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"exam-api-sync-go/dao/model/fxshop"
)

func newSysMessageItem(db *gorm.DB, opts ...gen.DOOption) sysMessageItem {
	_sysMessageItem := sysMessageItem{}

	_sysMessageItem.sysMessageItemDo.UseDB(db, opts...)
	_sysMessageItem.sysMessageItemDo.UseModel(&fxshop.SysMessageItem{})

	tableName := _sysMessageItem.sysMessageItemDo.TableName()
	_sysMessageItem.ALL = field.NewAsterisk(tableName)
	_sysMessageItem.ID = field.NewInt(tableName, "id")
	_sysMessageItem.ItemName = field.NewString(tableName, "item_name")
	_sysMessageItem.ShowName = field.NewString(tableName, "show_name")
	_sysMessageItem.ReplaceName = field.NewString(tableName, "replace_name")

	_sysMessageItem.fillFieldMap()

	return _sysMessageItem
}

type sysMessageItem struct {
	sysMessageItemDo

	ALL         field.Asterisk
	ID          field.Int
	ItemName    field.String // 项名称
	ShowName    field.String // 显示名称
	ReplaceName field.String // 替换字段名字

	fieldMap map[string]field.Expr
}

func (s sysMessageItem) Table(newTableName string) *sysMessageItem {
	s.sysMessageItemDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysMessageItem) As(alias string) *sysMessageItem {
	s.sysMessageItemDo.DO = *(s.sysMessageItemDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysMessageItem) updateTableName(table string) *sysMessageItem {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt(table, "id")
	s.ItemName = field.NewString(table, "item_name")
	s.ShowName = field.NewString(table, "show_name")
	s.ReplaceName = field.NewString(table, "replace_name")

	s.fillFieldMap()

	return s
}

func (s *sysMessageItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysMessageItem) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 4)
	s.fieldMap["id"] = s.ID
	s.fieldMap["item_name"] = s.ItemName
	s.fieldMap["show_name"] = s.ShowName
	s.fieldMap["replace_name"] = s.ReplaceName
}

func (s sysMessageItem) clone(db *gorm.DB) sysMessageItem {
	s.sysMessageItemDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysMessageItem) replaceDB(db *gorm.DB) sysMessageItem {
	s.sysMessageItemDo.ReplaceDB(db)
	return s
}

type sysMessageItemDo struct{ gen.DO }

type ISysMessageItemDo interface {
	gen.SubQuery
	Debug() ISysMessageItemDo
	WithContext(ctx context.Context) ISysMessageItemDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysMessageItemDo
	WriteDB() ISysMessageItemDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysMessageItemDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysMessageItemDo
	Not(conds ...gen.Condition) ISysMessageItemDo
	Or(conds ...gen.Condition) ISysMessageItemDo
	Select(conds ...field.Expr) ISysMessageItemDo
	Where(conds ...gen.Condition) ISysMessageItemDo
	Order(conds ...field.Expr) ISysMessageItemDo
	Distinct(cols ...field.Expr) ISysMessageItemDo
	Omit(cols ...field.Expr) ISysMessageItemDo
	Join(table schema.Tabler, on ...field.Expr) ISysMessageItemDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysMessageItemDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysMessageItemDo
	Group(cols ...field.Expr) ISysMessageItemDo
	Having(conds ...gen.Condition) ISysMessageItemDo
	Limit(limit int) ISysMessageItemDo
	Offset(offset int) ISysMessageItemDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysMessageItemDo
	Unscoped() ISysMessageItemDo
	Create(values ...*fxshop.SysMessageItem) error
	CreateInBatches(values []*fxshop.SysMessageItem, batchSize int) error
	Save(values ...*fxshop.SysMessageItem) error
	First() (*fxshop.SysMessageItem, error)
	Take() (*fxshop.SysMessageItem, error)
	Last() (*fxshop.SysMessageItem, error)
	Find() ([]*fxshop.SysMessageItem, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.SysMessageItem, err error)
	FindInBatches(result *[]*fxshop.SysMessageItem, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*fxshop.SysMessageItem) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysMessageItemDo
	Assign(attrs ...field.AssignExpr) ISysMessageItemDo
	Joins(fields ...field.RelationField) ISysMessageItemDo
	Preload(fields ...field.RelationField) ISysMessageItemDo
	FirstOrInit() (*fxshop.SysMessageItem, error)
	FirstOrCreate() (*fxshop.SysMessageItem, error)
	FindByPage(offset int, limit int) (result []*fxshop.SysMessageItem, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysMessageItemDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysMessageItemDo) Debug() ISysMessageItemDo {
	return s.withDO(s.DO.Debug())
}

func (s sysMessageItemDo) WithContext(ctx context.Context) ISysMessageItemDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysMessageItemDo) ReadDB() ISysMessageItemDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysMessageItemDo) WriteDB() ISysMessageItemDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysMessageItemDo) Session(config *gorm.Session) ISysMessageItemDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysMessageItemDo) Clauses(conds ...clause.Expression) ISysMessageItemDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysMessageItemDo) Returning(value interface{}, columns ...string) ISysMessageItemDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysMessageItemDo) Not(conds ...gen.Condition) ISysMessageItemDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysMessageItemDo) Or(conds ...gen.Condition) ISysMessageItemDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysMessageItemDo) Select(conds ...field.Expr) ISysMessageItemDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysMessageItemDo) Where(conds ...gen.Condition) ISysMessageItemDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysMessageItemDo) Order(conds ...field.Expr) ISysMessageItemDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysMessageItemDo) Distinct(cols ...field.Expr) ISysMessageItemDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysMessageItemDo) Omit(cols ...field.Expr) ISysMessageItemDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysMessageItemDo) Join(table schema.Tabler, on ...field.Expr) ISysMessageItemDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysMessageItemDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysMessageItemDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysMessageItemDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysMessageItemDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysMessageItemDo) Group(cols ...field.Expr) ISysMessageItemDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysMessageItemDo) Having(conds ...gen.Condition) ISysMessageItemDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysMessageItemDo) Limit(limit int) ISysMessageItemDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysMessageItemDo) Offset(offset int) ISysMessageItemDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysMessageItemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysMessageItemDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysMessageItemDo) Unscoped() ISysMessageItemDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysMessageItemDo) Create(values ...*fxshop.SysMessageItem) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysMessageItemDo) CreateInBatches(values []*fxshop.SysMessageItem, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysMessageItemDo) Save(values ...*fxshop.SysMessageItem) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysMessageItemDo) First() (*fxshop.SysMessageItem, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysMessageItem), nil
	}
}

func (s sysMessageItemDo) Take() (*fxshop.SysMessageItem, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysMessageItem), nil
	}
}

func (s sysMessageItemDo) Last() (*fxshop.SysMessageItem, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysMessageItem), nil
	}
}

func (s sysMessageItemDo) Find() ([]*fxshop.SysMessageItem, error) {
	result, err := s.DO.Find()
	return result.([]*fxshop.SysMessageItem), err
}

func (s sysMessageItemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.SysMessageItem, err error) {
	buf := make([]*fxshop.SysMessageItem, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysMessageItemDo) FindInBatches(result *[]*fxshop.SysMessageItem, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysMessageItemDo) Attrs(attrs ...field.AssignExpr) ISysMessageItemDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysMessageItemDo) Assign(attrs ...field.AssignExpr) ISysMessageItemDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysMessageItemDo) Joins(fields ...field.RelationField) ISysMessageItemDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysMessageItemDo) Preload(fields ...field.RelationField) ISysMessageItemDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysMessageItemDo) FirstOrInit() (*fxshop.SysMessageItem, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysMessageItem), nil
	}
}

func (s sysMessageItemDo) FirstOrCreate() (*fxshop.SysMessageItem, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysMessageItem), nil
	}
}

func (s sysMessageItemDo) FindByPage(offset int, limit int) (result []*fxshop.SysMessageItem, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysMessageItemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysMessageItemDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysMessageItemDo) Delete(models ...*fxshop.SysMessageItem) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysMessageItemDo) withDO(do gen.Dao) *sysMessageItemDo {
	s.DO = *do.(*gen.DO)
	return s
}
