// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"exam-api-sync-go/dao/model/fxshop"
)

func newSysAddonsConfig(db *gorm.DB, opts ...gen.DOOption) sysAddonsConfig {
	_sysAddonsConfig := sysAddonsConfig{}

	_sysAddonsConfig.sysAddonsConfigDo.UseDB(db, opts...)
	_sysAddonsConfig.sysAddonsConfigDo.UseModel(&fxshop.SysAddonsConfig{})

	tableName := _sysAddonsConfig.sysAddonsConfigDo.TableName()
	_sysAddonsConfig.ALL = field.NewAsterisk(tableName)
	_sysAddonsConfig.ID = field.NewInt(tableName, "id")
	_sysAddonsConfig.Value = field.NewString(tableName, "value")
	_sysAddonsConfig.Desc = field.NewString(tableName, "desc")
	_sysAddonsConfig.IsUse = field.NewInt8(tableName, "is_use")
	_sysAddonsConfig.CreateTime = field.NewInt(tableName, "create_time")
	_sysAddonsConfig.ModifyTime = field.NewInt(tableName, "modify_time")
	_sysAddonsConfig.Addons = field.NewString(tableName, "addons")
	_sysAddonsConfig.WebsiteID = field.NewInt(tableName, "website_id")
	_sysAddonsConfig.ShopID = field.NewInt(tableName, "shop_id")

	_sysAddonsConfig.fillFieldMap()

	return _sysAddonsConfig
}

// sysAddonsConfig 应用配置表
type sysAddonsConfig struct {
	sysAddonsConfigDo

	ALL        field.Asterisk
	ID         field.Int    // 主键
	Value      field.String // 配置值json
	Desc       field.String // 描述
	IsUse      field.Int8   // 是否启用 1启用 0不启用
	CreateTime field.Int    // 创建时间
	ModifyTime field.Int    // 修改时间
	Addons     field.String // 应用名称
	WebsiteID  field.Int    // 实例信息
	ShopID     field.Int    // 店铺id

	fieldMap map[string]field.Expr
}

func (s sysAddonsConfig) Table(newTableName string) *sysAddonsConfig {
	s.sysAddonsConfigDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysAddonsConfig) As(alias string) *sysAddonsConfig {
	s.sysAddonsConfigDo.DO = *(s.sysAddonsConfigDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysAddonsConfig) updateTableName(table string) *sysAddonsConfig {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt(table, "id")
	s.Value = field.NewString(table, "value")
	s.Desc = field.NewString(table, "desc")
	s.IsUse = field.NewInt8(table, "is_use")
	s.CreateTime = field.NewInt(table, "create_time")
	s.ModifyTime = field.NewInt(table, "modify_time")
	s.Addons = field.NewString(table, "addons")
	s.WebsiteID = field.NewInt(table, "website_id")
	s.ShopID = field.NewInt(table, "shop_id")

	s.fillFieldMap()

	return s
}

func (s *sysAddonsConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysAddonsConfig) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 9)
	s.fieldMap["id"] = s.ID
	s.fieldMap["value"] = s.Value
	s.fieldMap["desc"] = s.Desc
	s.fieldMap["is_use"] = s.IsUse
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["modify_time"] = s.ModifyTime
	s.fieldMap["addons"] = s.Addons
	s.fieldMap["website_id"] = s.WebsiteID
	s.fieldMap["shop_id"] = s.ShopID
}

func (s sysAddonsConfig) clone(db *gorm.DB) sysAddonsConfig {
	s.sysAddonsConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysAddonsConfig) replaceDB(db *gorm.DB) sysAddonsConfig {
	s.sysAddonsConfigDo.ReplaceDB(db)
	return s
}

type sysAddonsConfigDo struct{ gen.DO }

type ISysAddonsConfigDo interface {
	gen.SubQuery
	Debug() ISysAddonsConfigDo
	WithContext(ctx context.Context) ISysAddonsConfigDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysAddonsConfigDo
	WriteDB() ISysAddonsConfigDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysAddonsConfigDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysAddonsConfigDo
	Not(conds ...gen.Condition) ISysAddonsConfigDo
	Or(conds ...gen.Condition) ISysAddonsConfigDo
	Select(conds ...field.Expr) ISysAddonsConfigDo
	Where(conds ...gen.Condition) ISysAddonsConfigDo
	Order(conds ...field.Expr) ISysAddonsConfigDo
	Distinct(cols ...field.Expr) ISysAddonsConfigDo
	Omit(cols ...field.Expr) ISysAddonsConfigDo
	Join(table schema.Tabler, on ...field.Expr) ISysAddonsConfigDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysAddonsConfigDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysAddonsConfigDo
	Group(cols ...field.Expr) ISysAddonsConfigDo
	Having(conds ...gen.Condition) ISysAddonsConfigDo
	Limit(limit int) ISysAddonsConfigDo
	Offset(offset int) ISysAddonsConfigDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysAddonsConfigDo
	Unscoped() ISysAddonsConfigDo
	Create(values ...*fxshop.SysAddonsConfig) error
	CreateInBatches(values []*fxshop.SysAddonsConfig, batchSize int) error
	Save(values ...*fxshop.SysAddonsConfig) error
	First() (*fxshop.SysAddonsConfig, error)
	Take() (*fxshop.SysAddonsConfig, error)
	Last() (*fxshop.SysAddonsConfig, error)
	Find() ([]*fxshop.SysAddonsConfig, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.SysAddonsConfig, err error)
	FindInBatches(result *[]*fxshop.SysAddonsConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*fxshop.SysAddonsConfig) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysAddonsConfigDo
	Assign(attrs ...field.AssignExpr) ISysAddonsConfigDo
	Joins(fields ...field.RelationField) ISysAddonsConfigDo
	Preload(fields ...field.RelationField) ISysAddonsConfigDo
	FirstOrInit() (*fxshop.SysAddonsConfig, error)
	FirstOrCreate() (*fxshop.SysAddonsConfig, error)
	FindByPage(offset int, limit int) (result []*fxshop.SysAddonsConfig, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysAddonsConfigDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysAddonsConfigDo) Debug() ISysAddonsConfigDo {
	return s.withDO(s.DO.Debug())
}

func (s sysAddonsConfigDo) WithContext(ctx context.Context) ISysAddonsConfigDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysAddonsConfigDo) ReadDB() ISysAddonsConfigDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysAddonsConfigDo) WriteDB() ISysAddonsConfigDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysAddonsConfigDo) Session(config *gorm.Session) ISysAddonsConfigDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysAddonsConfigDo) Clauses(conds ...clause.Expression) ISysAddonsConfigDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysAddonsConfigDo) Returning(value interface{}, columns ...string) ISysAddonsConfigDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysAddonsConfigDo) Not(conds ...gen.Condition) ISysAddonsConfigDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysAddonsConfigDo) Or(conds ...gen.Condition) ISysAddonsConfigDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysAddonsConfigDo) Select(conds ...field.Expr) ISysAddonsConfigDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysAddonsConfigDo) Where(conds ...gen.Condition) ISysAddonsConfigDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysAddonsConfigDo) Order(conds ...field.Expr) ISysAddonsConfigDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysAddonsConfigDo) Distinct(cols ...field.Expr) ISysAddonsConfigDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysAddonsConfigDo) Omit(cols ...field.Expr) ISysAddonsConfigDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysAddonsConfigDo) Join(table schema.Tabler, on ...field.Expr) ISysAddonsConfigDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysAddonsConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysAddonsConfigDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysAddonsConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysAddonsConfigDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysAddonsConfigDo) Group(cols ...field.Expr) ISysAddonsConfigDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysAddonsConfigDo) Having(conds ...gen.Condition) ISysAddonsConfigDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysAddonsConfigDo) Limit(limit int) ISysAddonsConfigDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysAddonsConfigDo) Offset(offset int) ISysAddonsConfigDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysAddonsConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysAddonsConfigDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysAddonsConfigDo) Unscoped() ISysAddonsConfigDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysAddonsConfigDo) Create(values ...*fxshop.SysAddonsConfig) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysAddonsConfigDo) CreateInBatches(values []*fxshop.SysAddonsConfig, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysAddonsConfigDo) Save(values ...*fxshop.SysAddonsConfig) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysAddonsConfigDo) First() (*fxshop.SysAddonsConfig, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysAddonsConfig), nil
	}
}

func (s sysAddonsConfigDo) Take() (*fxshop.SysAddonsConfig, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysAddonsConfig), nil
	}
}

func (s sysAddonsConfigDo) Last() (*fxshop.SysAddonsConfig, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysAddonsConfig), nil
	}
}

func (s sysAddonsConfigDo) Find() ([]*fxshop.SysAddonsConfig, error) {
	result, err := s.DO.Find()
	return result.([]*fxshop.SysAddonsConfig), err
}

func (s sysAddonsConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.SysAddonsConfig, err error) {
	buf := make([]*fxshop.SysAddonsConfig, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysAddonsConfigDo) FindInBatches(result *[]*fxshop.SysAddonsConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysAddonsConfigDo) Attrs(attrs ...field.AssignExpr) ISysAddonsConfigDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysAddonsConfigDo) Assign(attrs ...field.AssignExpr) ISysAddonsConfigDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysAddonsConfigDo) Joins(fields ...field.RelationField) ISysAddonsConfigDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysAddonsConfigDo) Preload(fields ...field.RelationField) ISysAddonsConfigDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysAddonsConfigDo) FirstOrInit() (*fxshop.SysAddonsConfig, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysAddonsConfig), nil
	}
}

func (s sysAddonsConfigDo) FirstOrCreate() (*fxshop.SysAddonsConfig, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysAddonsConfig), nil
	}
}

func (s sysAddonsConfigDo) FindByPage(offset int, limit int) (result []*fxshop.SysAddonsConfig, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysAddonsConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysAddonsConfigDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysAddonsConfigDo) Delete(models ...*fxshop.SysAddonsConfig) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysAddonsConfigDo) withDO(do gen.Dao) *sysAddonsConfigDo {
	s.DO = *do.(*gen.DO)
	return s
}
