// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"exam-api-sync-go/dao/model/fxshop"
)

func newSysCourseUnit(db *gorm.DB, opts ...gen.DOOption) sysCourseUnit {
	_sysCourseUnit := sysCourseUnit{}

	_sysCourseUnit.sysCourseUnitDo.UseDB(db, opts...)
	_sysCourseUnit.sysCourseUnitDo.UseModel(&fxshop.SysCourseUnit{})

	tableName := _sysCourseUnit.sysCourseUnitDo.TableName()
	_sysCourseUnit.ALL = field.NewAsterisk(tableName)
	_sysCourseUnit.ID = field.NewInt(tableName, "id")
	_sysCourseUnit.Name = field.NewString(tableName, "name")
	_sysCourseUnit.CourseType = field.NewInt(tableName, "course_type")
	_sysCourseUnit.CategoryID = field.NewInt(tableName, "category_id")
	_sysCourseUnit.Invisible = field.NewInt8(tableName, "invisible")
	_sysCourseUnit.Rank = field.NewInt(tableName, "rank")
	_sysCourseUnit.CreateTime = field.NewInt(tableName, "create_time")
	_sysCourseUnit.CalcProgress = field.NewInt(tableName, "calc_progress")
	_sysCourseUnit.TeacherID = field.NewInt(tableName, "teacher_id")
	_sysCourseUnit.Label = field.NewString(tableName, "label")
	_sysCourseUnit.RefCourseType = field.NewInt(tableName, "ref_course_type")
	_sysCourseUnit.CgzCatalogues = field.NewString(tableName, "cgz_catalogues")
	_sysCourseUnit.Obsoleted = field.NewInt(tableName, "obsoleted")
	_sysCourseUnit.SaoleiIds = field.NewString(tableName, "saolei_ids")

	_sysCourseUnit.fillFieldMap()

	return _sysCourseUnit
}

// sysCourseUnit 课程单元
type sysCourseUnit struct {
	sysCourseUnitDo

	ALL           field.Asterisk
	ID            field.Int
	Name          field.String // 备注
	CourseType    field.Int
	CategoryID    field.Int
	Invisible     field.Int8   // 隐藏
	Rank          field.Int    // 排序：由小到大
	CreateTime    field.Int    // 添加时间
	CalcProgress  field.Int    // 是否计入学习进度
	TeacherID     field.Int    // 讲师
	Label         field.String // 标签分类
	RefCourseType field.Int    // 关联正课编码
	CgzCatalogues field.String // 关联初高中无漏专题目录ID
	Obsoleted     field.Int    // 过时的时间戳
	SaoleiIds     field.String // 关联扫雷卷ID

	fieldMap map[string]field.Expr
}

func (s sysCourseUnit) Table(newTableName string) *sysCourseUnit {
	s.sysCourseUnitDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysCourseUnit) As(alias string) *sysCourseUnit {
	s.sysCourseUnitDo.DO = *(s.sysCourseUnitDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysCourseUnit) updateTableName(table string) *sysCourseUnit {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt(table, "id")
	s.Name = field.NewString(table, "name")
	s.CourseType = field.NewInt(table, "course_type")
	s.CategoryID = field.NewInt(table, "category_id")
	s.Invisible = field.NewInt8(table, "invisible")
	s.Rank = field.NewInt(table, "rank")
	s.CreateTime = field.NewInt(table, "create_time")
	s.CalcProgress = field.NewInt(table, "calc_progress")
	s.TeacherID = field.NewInt(table, "teacher_id")
	s.Label = field.NewString(table, "label")
	s.RefCourseType = field.NewInt(table, "ref_course_type")
	s.CgzCatalogues = field.NewString(table, "cgz_catalogues")
	s.Obsoleted = field.NewInt(table, "obsoleted")
	s.SaoleiIds = field.NewString(table, "saolei_ids")

	s.fillFieldMap()

	return s
}

func (s *sysCourseUnit) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysCourseUnit) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 14)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["course_type"] = s.CourseType
	s.fieldMap["category_id"] = s.CategoryID
	s.fieldMap["invisible"] = s.Invisible
	s.fieldMap["rank"] = s.Rank
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["calc_progress"] = s.CalcProgress
	s.fieldMap["teacher_id"] = s.TeacherID
	s.fieldMap["label"] = s.Label
	s.fieldMap["ref_course_type"] = s.RefCourseType
	s.fieldMap["cgz_catalogues"] = s.CgzCatalogues
	s.fieldMap["obsoleted"] = s.Obsoleted
	s.fieldMap["saolei_ids"] = s.SaoleiIds
}

func (s sysCourseUnit) clone(db *gorm.DB) sysCourseUnit {
	s.sysCourseUnitDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysCourseUnit) replaceDB(db *gorm.DB) sysCourseUnit {
	s.sysCourseUnitDo.ReplaceDB(db)
	return s
}

type sysCourseUnitDo struct{ gen.DO }

type ISysCourseUnitDo interface {
	gen.SubQuery
	Debug() ISysCourseUnitDo
	WithContext(ctx context.Context) ISysCourseUnitDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysCourseUnitDo
	WriteDB() ISysCourseUnitDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysCourseUnitDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysCourseUnitDo
	Not(conds ...gen.Condition) ISysCourseUnitDo
	Or(conds ...gen.Condition) ISysCourseUnitDo
	Select(conds ...field.Expr) ISysCourseUnitDo
	Where(conds ...gen.Condition) ISysCourseUnitDo
	Order(conds ...field.Expr) ISysCourseUnitDo
	Distinct(cols ...field.Expr) ISysCourseUnitDo
	Omit(cols ...field.Expr) ISysCourseUnitDo
	Join(table schema.Tabler, on ...field.Expr) ISysCourseUnitDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysCourseUnitDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysCourseUnitDo
	Group(cols ...field.Expr) ISysCourseUnitDo
	Having(conds ...gen.Condition) ISysCourseUnitDo
	Limit(limit int) ISysCourseUnitDo
	Offset(offset int) ISysCourseUnitDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysCourseUnitDo
	Unscoped() ISysCourseUnitDo
	Create(values ...*fxshop.SysCourseUnit) error
	CreateInBatches(values []*fxshop.SysCourseUnit, batchSize int) error
	Save(values ...*fxshop.SysCourseUnit) error
	First() (*fxshop.SysCourseUnit, error)
	Take() (*fxshop.SysCourseUnit, error)
	Last() (*fxshop.SysCourseUnit, error)
	Find() ([]*fxshop.SysCourseUnit, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.SysCourseUnit, err error)
	FindInBatches(result *[]*fxshop.SysCourseUnit, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*fxshop.SysCourseUnit) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysCourseUnitDo
	Assign(attrs ...field.AssignExpr) ISysCourseUnitDo
	Joins(fields ...field.RelationField) ISysCourseUnitDo
	Preload(fields ...field.RelationField) ISysCourseUnitDo
	FirstOrInit() (*fxshop.SysCourseUnit, error)
	FirstOrCreate() (*fxshop.SysCourseUnit, error)
	FindByPage(offset int, limit int) (result []*fxshop.SysCourseUnit, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysCourseUnitDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysCourseUnitDo) Debug() ISysCourseUnitDo {
	return s.withDO(s.DO.Debug())
}

func (s sysCourseUnitDo) WithContext(ctx context.Context) ISysCourseUnitDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysCourseUnitDo) ReadDB() ISysCourseUnitDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysCourseUnitDo) WriteDB() ISysCourseUnitDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysCourseUnitDo) Session(config *gorm.Session) ISysCourseUnitDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysCourseUnitDo) Clauses(conds ...clause.Expression) ISysCourseUnitDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysCourseUnitDo) Returning(value interface{}, columns ...string) ISysCourseUnitDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysCourseUnitDo) Not(conds ...gen.Condition) ISysCourseUnitDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysCourseUnitDo) Or(conds ...gen.Condition) ISysCourseUnitDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysCourseUnitDo) Select(conds ...field.Expr) ISysCourseUnitDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysCourseUnitDo) Where(conds ...gen.Condition) ISysCourseUnitDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysCourseUnitDo) Order(conds ...field.Expr) ISysCourseUnitDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysCourseUnitDo) Distinct(cols ...field.Expr) ISysCourseUnitDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysCourseUnitDo) Omit(cols ...field.Expr) ISysCourseUnitDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysCourseUnitDo) Join(table schema.Tabler, on ...field.Expr) ISysCourseUnitDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysCourseUnitDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysCourseUnitDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysCourseUnitDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysCourseUnitDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysCourseUnitDo) Group(cols ...field.Expr) ISysCourseUnitDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysCourseUnitDo) Having(conds ...gen.Condition) ISysCourseUnitDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysCourseUnitDo) Limit(limit int) ISysCourseUnitDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysCourseUnitDo) Offset(offset int) ISysCourseUnitDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysCourseUnitDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysCourseUnitDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysCourseUnitDo) Unscoped() ISysCourseUnitDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysCourseUnitDo) Create(values ...*fxshop.SysCourseUnit) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysCourseUnitDo) CreateInBatches(values []*fxshop.SysCourseUnit, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysCourseUnitDo) Save(values ...*fxshop.SysCourseUnit) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysCourseUnitDo) First() (*fxshop.SysCourseUnit, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysCourseUnit), nil
	}
}

func (s sysCourseUnitDo) Take() (*fxshop.SysCourseUnit, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysCourseUnit), nil
	}
}

func (s sysCourseUnitDo) Last() (*fxshop.SysCourseUnit, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysCourseUnit), nil
	}
}

func (s sysCourseUnitDo) Find() ([]*fxshop.SysCourseUnit, error) {
	result, err := s.DO.Find()
	return result.([]*fxshop.SysCourseUnit), err
}

func (s sysCourseUnitDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.SysCourseUnit, err error) {
	buf := make([]*fxshop.SysCourseUnit, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysCourseUnitDo) FindInBatches(result *[]*fxshop.SysCourseUnit, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysCourseUnitDo) Attrs(attrs ...field.AssignExpr) ISysCourseUnitDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysCourseUnitDo) Assign(attrs ...field.AssignExpr) ISysCourseUnitDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysCourseUnitDo) Joins(fields ...field.RelationField) ISysCourseUnitDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysCourseUnitDo) Preload(fields ...field.RelationField) ISysCourseUnitDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysCourseUnitDo) FirstOrInit() (*fxshop.SysCourseUnit, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysCourseUnit), nil
	}
}

func (s sysCourseUnitDo) FirstOrCreate() (*fxshop.SysCourseUnit, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysCourseUnit), nil
	}
}

func (s sysCourseUnitDo) FindByPage(offset int, limit int) (result []*fxshop.SysCourseUnit, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysCourseUnitDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysCourseUnitDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysCourseUnitDo) Delete(models ...*fxshop.SysCourseUnit) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysCourseUnitDo) withDO(do gen.Dao) *sysCourseUnitDo {
	s.DO = *do.(*gen.DO)
	return s
}
