// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"exam-api-sync-go/dao/model/fxshop"
)

func newSysAlbumClass(db *gorm.DB, opts ...gen.DOOption) sysAlbumClass {
	_sysAlbumClass := sysAlbumClass{}

	_sysAlbumClass.sysAlbumClassDo.UseDB(db, opts...)
	_sysAlbumClass.sysAlbumClassDo.UseModel(&fxshop.SysAlbumClass{})

	tableName := _sysAlbumClass.sysAlbumClassDo.TableName()
	_sysAlbumClass.ALL = field.NewAsterisk(tableName)
	_sysAlbumClass.AlbumID = field.NewInt(tableName, "album_id")
	_sysAlbumClass.WebsiteID = field.NewInt(tableName, "website_id")
	_sysAlbumClass.ShopID = field.NewInt(tableName, "shop_id")
	_sysAlbumClass.SupplierID = field.NewInt(tableName, "supplier_id")
	_sysAlbumClass.Pid = field.NewInt(tableName, "pid")
	_sysAlbumClass.AlbumName = field.NewString(tableName, "album_name")
	_sysAlbumClass.AlbumCover = field.NewString(tableName, "album_cover")
	_sysAlbumClass.IsDefault = field.NewInt8(tableName, "is_default")
	_sysAlbumClass.Sort = field.NewInt(tableName, "sort")
	_sysAlbumClass.CreateTime = field.NewInt(tableName, "create_time")

	_sysAlbumClass.fillFieldMap()

	return _sysAlbumClass
}

// sysAlbumClass 相册表
type sysAlbumClass struct {
	sysAlbumClassDo

	ALL        field.Asterisk
	AlbumID    field.Int    // 相册id
	WebsiteID  field.Int    // 实例信息
	ShopID     field.Int    // 店铺id
	SupplierID field.Int    // 供应商id(供应商端才有)
	Pid        field.Int    // 上级相册ID
	AlbumName  field.String // 相册名称
	AlbumCover field.String // 相册封面
	IsDefault  field.Int8   // 是否为默认相册,1代表默认
	Sort       field.Int
	CreateTime field.Int // 创建时间

	fieldMap map[string]field.Expr
}

func (s sysAlbumClass) Table(newTableName string) *sysAlbumClass {
	s.sysAlbumClassDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysAlbumClass) As(alias string) *sysAlbumClass {
	s.sysAlbumClassDo.DO = *(s.sysAlbumClassDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysAlbumClass) updateTableName(table string) *sysAlbumClass {
	s.ALL = field.NewAsterisk(table)
	s.AlbumID = field.NewInt(table, "album_id")
	s.WebsiteID = field.NewInt(table, "website_id")
	s.ShopID = field.NewInt(table, "shop_id")
	s.SupplierID = field.NewInt(table, "supplier_id")
	s.Pid = field.NewInt(table, "pid")
	s.AlbumName = field.NewString(table, "album_name")
	s.AlbumCover = field.NewString(table, "album_cover")
	s.IsDefault = field.NewInt8(table, "is_default")
	s.Sort = field.NewInt(table, "sort")
	s.CreateTime = field.NewInt(table, "create_time")

	s.fillFieldMap()

	return s
}

func (s *sysAlbumClass) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysAlbumClass) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 10)
	s.fieldMap["album_id"] = s.AlbumID
	s.fieldMap["website_id"] = s.WebsiteID
	s.fieldMap["shop_id"] = s.ShopID
	s.fieldMap["supplier_id"] = s.SupplierID
	s.fieldMap["pid"] = s.Pid
	s.fieldMap["album_name"] = s.AlbumName
	s.fieldMap["album_cover"] = s.AlbumCover
	s.fieldMap["is_default"] = s.IsDefault
	s.fieldMap["sort"] = s.Sort
	s.fieldMap["create_time"] = s.CreateTime
}

func (s sysAlbumClass) clone(db *gorm.DB) sysAlbumClass {
	s.sysAlbumClassDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysAlbumClass) replaceDB(db *gorm.DB) sysAlbumClass {
	s.sysAlbumClassDo.ReplaceDB(db)
	return s
}

type sysAlbumClassDo struct{ gen.DO }

type ISysAlbumClassDo interface {
	gen.SubQuery
	Debug() ISysAlbumClassDo
	WithContext(ctx context.Context) ISysAlbumClassDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysAlbumClassDo
	WriteDB() ISysAlbumClassDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysAlbumClassDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysAlbumClassDo
	Not(conds ...gen.Condition) ISysAlbumClassDo
	Or(conds ...gen.Condition) ISysAlbumClassDo
	Select(conds ...field.Expr) ISysAlbumClassDo
	Where(conds ...gen.Condition) ISysAlbumClassDo
	Order(conds ...field.Expr) ISysAlbumClassDo
	Distinct(cols ...field.Expr) ISysAlbumClassDo
	Omit(cols ...field.Expr) ISysAlbumClassDo
	Join(table schema.Tabler, on ...field.Expr) ISysAlbumClassDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysAlbumClassDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysAlbumClassDo
	Group(cols ...field.Expr) ISysAlbumClassDo
	Having(conds ...gen.Condition) ISysAlbumClassDo
	Limit(limit int) ISysAlbumClassDo
	Offset(offset int) ISysAlbumClassDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysAlbumClassDo
	Unscoped() ISysAlbumClassDo
	Create(values ...*fxshop.SysAlbumClass) error
	CreateInBatches(values []*fxshop.SysAlbumClass, batchSize int) error
	Save(values ...*fxshop.SysAlbumClass) error
	First() (*fxshop.SysAlbumClass, error)
	Take() (*fxshop.SysAlbumClass, error)
	Last() (*fxshop.SysAlbumClass, error)
	Find() ([]*fxshop.SysAlbumClass, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.SysAlbumClass, err error)
	FindInBatches(result *[]*fxshop.SysAlbumClass, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*fxshop.SysAlbumClass) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysAlbumClassDo
	Assign(attrs ...field.AssignExpr) ISysAlbumClassDo
	Joins(fields ...field.RelationField) ISysAlbumClassDo
	Preload(fields ...field.RelationField) ISysAlbumClassDo
	FirstOrInit() (*fxshop.SysAlbumClass, error)
	FirstOrCreate() (*fxshop.SysAlbumClass, error)
	FindByPage(offset int, limit int) (result []*fxshop.SysAlbumClass, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysAlbumClassDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysAlbumClassDo) Debug() ISysAlbumClassDo {
	return s.withDO(s.DO.Debug())
}

func (s sysAlbumClassDo) WithContext(ctx context.Context) ISysAlbumClassDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysAlbumClassDo) ReadDB() ISysAlbumClassDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysAlbumClassDo) WriteDB() ISysAlbumClassDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysAlbumClassDo) Session(config *gorm.Session) ISysAlbumClassDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysAlbumClassDo) Clauses(conds ...clause.Expression) ISysAlbumClassDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysAlbumClassDo) Returning(value interface{}, columns ...string) ISysAlbumClassDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysAlbumClassDo) Not(conds ...gen.Condition) ISysAlbumClassDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysAlbumClassDo) Or(conds ...gen.Condition) ISysAlbumClassDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysAlbumClassDo) Select(conds ...field.Expr) ISysAlbumClassDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysAlbumClassDo) Where(conds ...gen.Condition) ISysAlbumClassDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysAlbumClassDo) Order(conds ...field.Expr) ISysAlbumClassDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysAlbumClassDo) Distinct(cols ...field.Expr) ISysAlbumClassDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysAlbumClassDo) Omit(cols ...field.Expr) ISysAlbumClassDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysAlbumClassDo) Join(table schema.Tabler, on ...field.Expr) ISysAlbumClassDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysAlbumClassDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysAlbumClassDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysAlbumClassDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysAlbumClassDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysAlbumClassDo) Group(cols ...field.Expr) ISysAlbumClassDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysAlbumClassDo) Having(conds ...gen.Condition) ISysAlbumClassDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysAlbumClassDo) Limit(limit int) ISysAlbumClassDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysAlbumClassDo) Offset(offset int) ISysAlbumClassDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysAlbumClassDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysAlbumClassDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysAlbumClassDo) Unscoped() ISysAlbumClassDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysAlbumClassDo) Create(values ...*fxshop.SysAlbumClass) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysAlbumClassDo) CreateInBatches(values []*fxshop.SysAlbumClass, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysAlbumClassDo) Save(values ...*fxshop.SysAlbumClass) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysAlbumClassDo) First() (*fxshop.SysAlbumClass, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysAlbumClass), nil
	}
}

func (s sysAlbumClassDo) Take() (*fxshop.SysAlbumClass, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysAlbumClass), nil
	}
}

func (s sysAlbumClassDo) Last() (*fxshop.SysAlbumClass, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysAlbumClass), nil
	}
}

func (s sysAlbumClassDo) Find() ([]*fxshop.SysAlbumClass, error) {
	result, err := s.DO.Find()
	return result.([]*fxshop.SysAlbumClass), err
}

func (s sysAlbumClassDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.SysAlbumClass, err error) {
	buf := make([]*fxshop.SysAlbumClass, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysAlbumClassDo) FindInBatches(result *[]*fxshop.SysAlbumClass, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysAlbumClassDo) Attrs(attrs ...field.AssignExpr) ISysAlbumClassDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysAlbumClassDo) Assign(attrs ...field.AssignExpr) ISysAlbumClassDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysAlbumClassDo) Joins(fields ...field.RelationField) ISysAlbumClassDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysAlbumClassDo) Preload(fields ...field.RelationField) ISysAlbumClassDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysAlbumClassDo) FirstOrInit() (*fxshop.SysAlbumClass, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysAlbumClass), nil
	}
}

func (s sysAlbumClassDo) FirstOrCreate() (*fxshop.SysAlbumClass, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysAlbumClass), nil
	}
}

func (s sysAlbumClassDo) FindByPage(offset int, limit int) (result []*fxshop.SysAlbumClass, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysAlbumClassDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysAlbumClassDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysAlbumClassDo) Delete(models ...*fxshop.SysAlbumClass) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysAlbumClassDo) withDO(do gen.Dao) *sysAlbumClassDo {
	s.DO = *do.(*gen.DO)
	return s
}
