// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"exam-api-sync-go/dao/model/fxshop"
)

func newSysDevLog(db *gorm.DB, opts ...gen.DOOption) sysDevLog {
	_sysDevLog := sysDevLog{}

	_sysDevLog.sysDevLogDo.UseDB(db, opts...)
	_sysDevLog.sysDevLogDo.UseModel(&fxshop.SysDevLog{})

	tableName := _sysDevLog.sysDevLogDo.TableName()
	_sysDevLog.ALL = field.NewAsterisk(tableName)
	_sysDevLog.ID = field.NewInt(tableName, "id")
	_sysDevLog.Msg = field.NewString(tableName, "msg")
	_sysDevLog.CreateTime = field.NewTime(tableName, "create_time")
	_sysDevLog.Code = field.NewString(tableName, "code")

	_sysDevLog.fillFieldMap()

	return _sysDevLog
}

// sysDevLog 开发日志表
type sysDevLog struct {
	sysDevLogDo

	ALL        field.Asterisk
	ID         field.Int    // 主键id
	Msg        field.String // log
	CreateTime field.Time   // 记录时间
	Code       field.String // 日志业务代码

	fieldMap map[string]field.Expr
}

func (s sysDevLog) Table(newTableName string) *sysDevLog {
	s.sysDevLogDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysDevLog) As(alias string) *sysDevLog {
	s.sysDevLogDo.DO = *(s.sysDevLogDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysDevLog) updateTableName(table string) *sysDevLog {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt(table, "id")
	s.Msg = field.NewString(table, "msg")
	s.CreateTime = field.NewTime(table, "create_time")
	s.Code = field.NewString(table, "code")

	s.fillFieldMap()

	return s
}

func (s *sysDevLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysDevLog) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 4)
	s.fieldMap["id"] = s.ID
	s.fieldMap["msg"] = s.Msg
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["code"] = s.Code
}

func (s sysDevLog) clone(db *gorm.DB) sysDevLog {
	s.sysDevLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysDevLog) replaceDB(db *gorm.DB) sysDevLog {
	s.sysDevLogDo.ReplaceDB(db)
	return s
}

type sysDevLogDo struct{ gen.DO }

type ISysDevLogDo interface {
	gen.SubQuery
	Debug() ISysDevLogDo
	WithContext(ctx context.Context) ISysDevLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysDevLogDo
	WriteDB() ISysDevLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysDevLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysDevLogDo
	Not(conds ...gen.Condition) ISysDevLogDo
	Or(conds ...gen.Condition) ISysDevLogDo
	Select(conds ...field.Expr) ISysDevLogDo
	Where(conds ...gen.Condition) ISysDevLogDo
	Order(conds ...field.Expr) ISysDevLogDo
	Distinct(cols ...field.Expr) ISysDevLogDo
	Omit(cols ...field.Expr) ISysDevLogDo
	Join(table schema.Tabler, on ...field.Expr) ISysDevLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysDevLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysDevLogDo
	Group(cols ...field.Expr) ISysDevLogDo
	Having(conds ...gen.Condition) ISysDevLogDo
	Limit(limit int) ISysDevLogDo
	Offset(offset int) ISysDevLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysDevLogDo
	Unscoped() ISysDevLogDo
	Create(values ...*fxshop.SysDevLog) error
	CreateInBatches(values []*fxshop.SysDevLog, batchSize int) error
	Save(values ...*fxshop.SysDevLog) error
	First() (*fxshop.SysDevLog, error)
	Take() (*fxshop.SysDevLog, error)
	Last() (*fxshop.SysDevLog, error)
	Find() ([]*fxshop.SysDevLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.SysDevLog, err error)
	FindInBatches(result *[]*fxshop.SysDevLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*fxshop.SysDevLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysDevLogDo
	Assign(attrs ...field.AssignExpr) ISysDevLogDo
	Joins(fields ...field.RelationField) ISysDevLogDo
	Preload(fields ...field.RelationField) ISysDevLogDo
	FirstOrInit() (*fxshop.SysDevLog, error)
	FirstOrCreate() (*fxshop.SysDevLog, error)
	FindByPage(offset int, limit int) (result []*fxshop.SysDevLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysDevLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysDevLogDo) Debug() ISysDevLogDo {
	return s.withDO(s.DO.Debug())
}

func (s sysDevLogDo) WithContext(ctx context.Context) ISysDevLogDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysDevLogDo) ReadDB() ISysDevLogDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysDevLogDo) WriteDB() ISysDevLogDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysDevLogDo) Session(config *gorm.Session) ISysDevLogDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysDevLogDo) Clauses(conds ...clause.Expression) ISysDevLogDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysDevLogDo) Returning(value interface{}, columns ...string) ISysDevLogDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysDevLogDo) Not(conds ...gen.Condition) ISysDevLogDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysDevLogDo) Or(conds ...gen.Condition) ISysDevLogDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysDevLogDo) Select(conds ...field.Expr) ISysDevLogDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysDevLogDo) Where(conds ...gen.Condition) ISysDevLogDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysDevLogDo) Order(conds ...field.Expr) ISysDevLogDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysDevLogDo) Distinct(cols ...field.Expr) ISysDevLogDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysDevLogDo) Omit(cols ...field.Expr) ISysDevLogDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysDevLogDo) Join(table schema.Tabler, on ...field.Expr) ISysDevLogDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysDevLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysDevLogDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysDevLogDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysDevLogDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysDevLogDo) Group(cols ...field.Expr) ISysDevLogDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysDevLogDo) Having(conds ...gen.Condition) ISysDevLogDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysDevLogDo) Limit(limit int) ISysDevLogDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysDevLogDo) Offset(offset int) ISysDevLogDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysDevLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysDevLogDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysDevLogDo) Unscoped() ISysDevLogDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysDevLogDo) Create(values ...*fxshop.SysDevLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysDevLogDo) CreateInBatches(values []*fxshop.SysDevLog, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysDevLogDo) Save(values ...*fxshop.SysDevLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysDevLogDo) First() (*fxshop.SysDevLog, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysDevLog), nil
	}
}

func (s sysDevLogDo) Take() (*fxshop.SysDevLog, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysDevLog), nil
	}
}

func (s sysDevLogDo) Last() (*fxshop.SysDevLog, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysDevLog), nil
	}
}

func (s sysDevLogDo) Find() ([]*fxshop.SysDevLog, error) {
	result, err := s.DO.Find()
	return result.([]*fxshop.SysDevLog), err
}

func (s sysDevLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.SysDevLog, err error) {
	buf := make([]*fxshop.SysDevLog, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysDevLogDo) FindInBatches(result *[]*fxshop.SysDevLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysDevLogDo) Attrs(attrs ...field.AssignExpr) ISysDevLogDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysDevLogDo) Assign(attrs ...field.AssignExpr) ISysDevLogDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysDevLogDo) Joins(fields ...field.RelationField) ISysDevLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysDevLogDo) Preload(fields ...field.RelationField) ISysDevLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysDevLogDo) FirstOrInit() (*fxshop.SysDevLog, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysDevLog), nil
	}
}

func (s sysDevLogDo) FirstOrCreate() (*fxshop.SysDevLog, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysDevLog), nil
	}
}

func (s sysDevLogDo) FindByPage(offset int, limit int) (result []*fxshop.SysDevLog, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysDevLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysDevLogDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysDevLogDo) Delete(models ...*fxshop.SysDevLog) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysDevLogDo) withDO(do gen.Dao) *sysDevLogDo {
	s.DO = *do.(*gen.DO)
	return s
}
