// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"exam-api-sync-go/dao/model/fxshop"
)

func newSysCourseVideoViewLogs(db *gorm.DB, opts ...gen.DOOption) sysCourseVideoViewLogs {
	_sysCourseVideoViewLogs := sysCourseVideoViewLogs{}

	_sysCourseVideoViewLogs.sysCourseVideoViewLogsDo.UseDB(db, opts...)
	_sysCourseVideoViewLogs.sysCourseVideoViewLogsDo.UseModel(&fxshop.SysCourseVideoViewLogs{})

	tableName := _sysCourseVideoViewLogs.sysCourseVideoViewLogsDo.TableName()
	_sysCourseVideoViewLogs.ALL = field.NewAsterisk(tableName)
	_sysCourseVideoViewLogs.ID = field.NewInt(tableName, "id")
	_sysCourseVideoViewLogs.UID = field.NewInt(tableName, "uid")
	_sysCourseVideoViewLogs.CourseType = field.NewInt(tableName, "course_type")
	_sysCourseVideoViewLogs.Vid = field.NewString(tableName, "vid")
	_sysCourseVideoViewLogs.CreateTime = field.NewInt(tableName, "create_time")
	_sysCourseVideoViewLogs.ViewCount = field.NewInt(tableName, "view_count")
	_sysCourseVideoViewLogs.UpdateTime = field.NewInt(tableName, "update_time")
	_sysCourseVideoViewLogs.ViewDuration = field.NewInt(tableName, "view_duration")
	_sysCourseVideoViewLogs.PlayDuration = field.NewInt(tableName, "play_duration")
	_sysCourseVideoViewLogs.Process = field.NewInt8(tableName, "process")
	_sysCourseVideoViewLogs.PolvDuration = field.NewInt(tableName, "polv_duration")
	_sysCourseVideoViewLogs.CDuration = field.NewInt(tableName, "c_duration")
	_sysCourseVideoViewLogs.CompleteAt = field.NewInt(tableName, "complete_at")
	_sysCourseVideoViewLogs.StcTime = field.NewInt(tableName, "stc_time")
	_sysCourseVideoViewLogs.StcProcess = field.NewInt8(tableName, "stc_process")
	_sysCourseVideoViewLogs.StcResetAt = field.NewInt64(tableName, "stc_reset_at")

	_sysCourseVideoViewLogs.fillFieldMap()

	return _sysCourseVideoViewLogs
}

// sysCourseVideoViewLogs 视频课程观看记录
type sysCourseVideoViewLogs struct {
	sysCourseVideoViewLogsDo

	ALL          field.Asterisk
	ID           field.Int    // 主键id
	UID          field.Int    // 用户
	CourseType   field.Int    // 订单项id
	Vid          field.String // 视频Id
	CreateTime   field.Int    // 记录时间
	ViewCount    field.Int    // 观看次数
	UpdateTime   field.Int    // 记录时间
	ViewDuration field.Int    // 累计停留时长
	PlayDuration field.Int    // 累计观看时长
	Process      field.Int8   // 1进行中 ，2已完成
	PolvDuration field.Int    // 保利威统计播放时长
	CDuration    field.Int    // 3.23后停留时长
	CompleteAt   field.Int    // 首次完成时间
	StcTime      field.Int    // 随堂测累计时长（每生成一次随堂测，重置为0）
	StcProcess   field.Int8   // 0重置，1进行中，2学完
	StcResetAt   field.Int64  // 随堂测重置时间

	fieldMap map[string]field.Expr
}

func (s sysCourseVideoViewLogs) Table(newTableName string) *sysCourseVideoViewLogs {
	s.sysCourseVideoViewLogsDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysCourseVideoViewLogs) As(alias string) *sysCourseVideoViewLogs {
	s.sysCourseVideoViewLogsDo.DO = *(s.sysCourseVideoViewLogsDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysCourseVideoViewLogs) updateTableName(table string) *sysCourseVideoViewLogs {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt(table, "id")
	s.UID = field.NewInt(table, "uid")
	s.CourseType = field.NewInt(table, "course_type")
	s.Vid = field.NewString(table, "vid")
	s.CreateTime = field.NewInt(table, "create_time")
	s.ViewCount = field.NewInt(table, "view_count")
	s.UpdateTime = field.NewInt(table, "update_time")
	s.ViewDuration = field.NewInt(table, "view_duration")
	s.PlayDuration = field.NewInt(table, "play_duration")
	s.Process = field.NewInt8(table, "process")
	s.PolvDuration = field.NewInt(table, "polv_duration")
	s.CDuration = field.NewInt(table, "c_duration")
	s.CompleteAt = field.NewInt(table, "complete_at")
	s.StcTime = field.NewInt(table, "stc_time")
	s.StcProcess = field.NewInt8(table, "stc_process")
	s.StcResetAt = field.NewInt64(table, "stc_reset_at")

	s.fillFieldMap()

	return s
}

func (s *sysCourseVideoViewLogs) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysCourseVideoViewLogs) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 16)
	s.fieldMap["id"] = s.ID
	s.fieldMap["uid"] = s.UID
	s.fieldMap["course_type"] = s.CourseType
	s.fieldMap["vid"] = s.Vid
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["view_count"] = s.ViewCount
	s.fieldMap["update_time"] = s.UpdateTime
	s.fieldMap["view_duration"] = s.ViewDuration
	s.fieldMap["play_duration"] = s.PlayDuration
	s.fieldMap["process"] = s.Process
	s.fieldMap["polv_duration"] = s.PolvDuration
	s.fieldMap["c_duration"] = s.CDuration
	s.fieldMap["complete_at"] = s.CompleteAt
	s.fieldMap["stc_time"] = s.StcTime
	s.fieldMap["stc_process"] = s.StcProcess
	s.fieldMap["stc_reset_at"] = s.StcResetAt
}

func (s sysCourseVideoViewLogs) clone(db *gorm.DB) sysCourseVideoViewLogs {
	s.sysCourseVideoViewLogsDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysCourseVideoViewLogs) replaceDB(db *gorm.DB) sysCourseVideoViewLogs {
	s.sysCourseVideoViewLogsDo.ReplaceDB(db)
	return s
}

type sysCourseVideoViewLogsDo struct{ gen.DO }

type ISysCourseVideoViewLogsDo interface {
	gen.SubQuery
	Debug() ISysCourseVideoViewLogsDo
	WithContext(ctx context.Context) ISysCourseVideoViewLogsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysCourseVideoViewLogsDo
	WriteDB() ISysCourseVideoViewLogsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysCourseVideoViewLogsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysCourseVideoViewLogsDo
	Not(conds ...gen.Condition) ISysCourseVideoViewLogsDo
	Or(conds ...gen.Condition) ISysCourseVideoViewLogsDo
	Select(conds ...field.Expr) ISysCourseVideoViewLogsDo
	Where(conds ...gen.Condition) ISysCourseVideoViewLogsDo
	Order(conds ...field.Expr) ISysCourseVideoViewLogsDo
	Distinct(cols ...field.Expr) ISysCourseVideoViewLogsDo
	Omit(cols ...field.Expr) ISysCourseVideoViewLogsDo
	Join(table schema.Tabler, on ...field.Expr) ISysCourseVideoViewLogsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysCourseVideoViewLogsDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysCourseVideoViewLogsDo
	Group(cols ...field.Expr) ISysCourseVideoViewLogsDo
	Having(conds ...gen.Condition) ISysCourseVideoViewLogsDo
	Limit(limit int) ISysCourseVideoViewLogsDo
	Offset(offset int) ISysCourseVideoViewLogsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysCourseVideoViewLogsDo
	Unscoped() ISysCourseVideoViewLogsDo
	Create(values ...*fxshop.SysCourseVideoViewLogs) error
	CreateInBatches(values []*fxshop.SysCourseVideoViewLogs, batchSize int) error
	Save(values ...*fxshop.SysCourseVideoViewLogs) error
	First() (*fxshop.SysCourseVideoViewLogs, error)
	Take() (*fxshop.SysCourseVideoViewLogs, error)
	Last() (*fxshop.SysCourseVideoViewLogs, error)
	Find() ([]*fxshop.SysCourseVideoViewLogs, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.SysCourseVideoViewLogs, err error)
	FindInBatches(result *[]*fxshop.SysCourseVideoViewLogs, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*fxshop.SysCourseVideoViewLogs) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysCourseVideoViewLogsDo
	Assign(attrs ...field.AssignExpr) ISysCourseVideoViewLogsDo
	Joins(fields ...field.RelationField) ISysCourseVideoViewLogsDo
	Preload(fields ...field.RelationField) ISysCourseVideoViewLogsDo
	FirstOrInit() (*fxshop.SysCourseVideoViewLogs, error)
	FirstOrCreate() (*fxshop.SysCourseVideoViewLogs, error)
	FindByPage(offset int, limit int) (result []*fxshop.SysCourseVideoViewLogs, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysCourseVideoViewLogsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysCourseVideoViewLogsDo) Debug() ISysCourseVideoViewLogsDo {
	return s.withDO(s.DO.Debug())
}

func (s sysCourseVideoViewLogsDo) WithContext(ctx context.Context) ISysCourseVideoViewLogsDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysCourseVideoViewLogsDo) ReadDB() ISysCourseVideoViewLogsDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysCourseVideoViewLogsDo) WriteDB() ISysCourseVideoViewLogsDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysCourseVideoViewLogsDo) Session(config *gorm.Session) ISysCourseVideoViewLogsDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysCourseVideoViewLogsDo) Clauses(conds ...clause.Expression) ISysCourseVideoViewLogsDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysCourseVideoViewLogsDo) Returning(value interface{}, columns ...string) ISysCourseVideoViewLogsDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysCourseVideoViewLogsDo) Not(conds ...gen.Condition) ISysCourseVideoViewLogsDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysCourseVideoViewLogsDo) Or(conds ...gen.Condition) ISysCourseVideoViewLogsDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysCourseVideoViewLogsDo) Select(conds ...field.Expr) ISysCourseVideoViewLogsDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysCourseVideoViewLogsDo) Where(conds ...gen.Condition) ISysCourseVideoViewLogsDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysCourseVideoViewLogsDo) Order(conds ...field.Expr) ISysCourseVideoViewLogsDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysCourseVideoViewLogsDo) Distinct(cols ...field.Expr) ISysCourseVideoViewLogsDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysCourseVideoViewLogsDo) Omit(cols ...field.Expr) ISysCourseVideoViewLogsDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysCourseVideoViewLogsDo) Join(table schema.Tabler, on ...field.Expr) ISysCourseVideoViewLogsDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysCourseVideoViewLogsDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysCourseVideoViewLogsDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysCourseVideoViewLogsDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysCourseVideoViewLogsDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysCourseVideoViewLogsDo) Group(cols ...field.Expr) ISysCourseVideoViewLogsDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysCourseVideoViewLogsDo) Having(conds ...gen.Condition) ISysCourseVideoViewLogsDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysCourseVideoViewLogsDo) Limit(limit int) ISysCourseVideoViewLogsDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysCourseVideoViewLogsDo) Offset(offset int) ISysCourseVideoViewLogsDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysCourseVideoViewLogsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysCourseVideoViewLogsDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysCourseVideoViewLogsDo) Unscoped() ISysCourseVideoViewLogsDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysCourseVideoViewLogsDo) Create(values ...*fxshop.SysCourseVideoViewLogs) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysCourseVideoViewLogsDo) CreateInBatches(values []*fxshop.SysCourseVideoViewLogs, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysCourseVideoViewLogsDo) Save(values ...*fxshop.SysCourseVideoViewLogs) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysCourseVideoViewLogsDo) First() (*fxshop.SysCourseVideoViewLogs, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysCourseVideoViewLogs), nil
	}
}

func (s sysCourseVideoViewLogsDo) Take() (*fxshop.SysCourseVideoViewLogs, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysCourseVideoViewLogs), nil
	}
}

func (s sysCourseVideoViewLogsDo) Last() (*fxshop.SysCourseVideoViewLogs, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysCourseVideoViewLogs), nil
	}
}

func (s sysCourseVideoViewLogsDo) Find() ([]*fxshop.SysCourseVideoViewLogs, error) {
	result, err := s.DO.Find()
	return result.([]*fxshop.SysCourseVideoViewLogs), err
}

func (s sysCourseVideoViewLogsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.SysCourseVideoViewLogs, err error) {
	buf := make([]*fxshop.SysCourseVideoViewLogs, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysCourseVideoViewLogsDo) FindInBatches(result *[]*fxshop.SysCourseVideoViewLogs, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysCourseVideoViewLogsDo) Attrs(attrs ...field.AssignExpr) ISysCourseVideoViewLogsDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysCourseVideoViewLogsDo) Assign(attrs ...field.AssignExpr) ISysCourseVideoViewLogsDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysCourseVideoViewLogsDo) Joins(fields ...field.RelationField) ISysCourseVideoViewLogsDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysCourseVideoViewLogsDo) Preload(fields ...field.RelationField) ISysCourseVideoViewLogsDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysCourseVideoViewLogsDo) FirstOrInit() (*fxshop.SysCourseVideoViewLogs, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysCourseVideoViewLogs), nil
	}
}

func (s sysCourseVideoViewLogsDo) FirstOrCreate() (*fxshop.SysCourseVideoViewLogs, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysCourseVideoViewLogs), nil
	}
}

func (s sysCourseVideoViewLogsDo) FindByPage(offset int, limit int) (result []*fxshop.SysCourseVideoViewLogs, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysCourseVideoViewLogsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysCourseVideoViewLogsDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysCourseVideoViewLogsDo) Delete(models ...*fxshop.SysCourseVideoViewLogs) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysCourseVideoViewLogsDo) withDO(do gen.Dao) *sysCourseVideoViewLogsDo {
	s.DO = *do.(*gen.DO)
	return s
}
