// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"exam-api-sync-go/dao/model/fxshop"
)

func newSysCourseActivation(db *gorm.DB, opts ...gen.DOOption) sysCourseActivation {
	_sysCourseActivation := sysCourseActivation{}

	_sysCourseActivation.sysCourseActivationDo.UseDB(db, opts...)
	_sysCourseActivation.sysCourseActivationDo.UseModel(&fxshop.SysCourseActivation{})

	tableName := _sysCourseActivation.sysCourseActivationDo.TableName()
	_sysCourseActivation.ALL = field.NewAsterisk(tableName)
	_sysCourseActivation.ID = field.NewInt(tableName, "id")
	_sysCourseActivation.UID = field.NewInt(tableName, "uid")
	_sysCourseActivation.ActivationCode = field.NewString(tableName, "activation_code")
	_sysCourseActivation.CourseType = field.NewInt(tableName, "course_type")
	_sysCourseActivation.UserID = field.NewInt(tableName, "user_id")
	_sysCourseActivation.CreateTime = field.NewInt(tableName, "create_time")
	_sysCourseActivation.ActivationTime = field.NewInt(tableName, "activation_time")
	_sysCourseActivation.Remark = field.NewString(tableName, "remark")
	_sysCourseActivation.Distribution = field.NewInt(tableName, "distribution")
	_sysCourseActivation.DistributionTime = field.NewInt(tableName, "distribution_time")
	_sysCourseActivation.OrderID = field.NewInt(tableName, "order_id")
	_sysCourseActivation.Source = field.NewInt(tableName, "source")
	_sysCourseActivation.Status = field.NewInt(tableName, "status")
	_sysCourseActivation.Province = field.NewString(tableName, "province")
	_sysCourseActivation.City = field.NewString(tableName, "city")
	_sysCourseActivation.District = field.NewString(tableName, "district")
	_sysCourseActivation.ExpireDays = field.NewInt(tableName, "expire_days")
	_sysCourseActivation.IsGift = field.NewInt(tableName, "is_gift")
	_sysCourseActivation.OldUID = field.NewInt(tableName, "old_uid")
	_sysCourseActivation.ViewCount = field.NewInt(tableName, "view_count")
	_sysCourseActivation.ExpireHours = field.NewInt(tableName, "expire_hours")
	_sysCourseActivation.CreateUID = field.NewInt(tableName, "create_uid")
	_sysCourseActivation.WulouActivationCode = field.NewString(tableName, "wulou_activation_code")
	_sysCourseActivation.WulouUserID = field.NewString(tableName, "wulou_user_id")
	_sysCourseActivation.MarkUID = field.NewInt(tableName, "mark_uid")
	_sysCourseActivation.DelayDays = field.NewInt(tableName, "delay_days")
	_sysCourseActivation.ImagineCourse = field.NewInt(tableName, "imagine_course")
	_sysCourseActivation.Inventory = field.NewFloat64(tableName, "inventory")
	_sysCourseActivation.CloseTime = field.NewInt(tableName, "close_time")
	_sysCourseActivation.PackageID = field.NewInt(tableName, "package_id")
	_sysCourseActivation.ParentID = field.NewInt(tableName, "parent_id")
	_sysCourseActivation.GiftType = field.NewInt(tableName, "gift_type")
	_sysCourseActivation.StoreID = field.NewInt(tableName, "store_id")
	_sysCourseActivation.ActiveStoreID = field.NewInt(tableName, "active_store_id")
	_sysCourseActivation.Location = field.NewString(tableName, "location")

	_sysCourseActivation.fillFieldMap()

	return _sysCourseActivation
}

// sysCourseActivation 视频课程激活码
type sysCourseActivation struct {
	sysCourseActivationDo

	ALL                 field.Asterisk
	ID                  field.Int     // 主键ID
	UID                 field.Int     // 大B的UID
	ActivationCode      field.String  // 激活码
	CourseType          field.Int     // 课程类型
	UserID              field.Int     // 激活码使用的UID
	CreateTime          field.Int     // 激活码创建时间
	ActivationTime      field.Int     // 激活时间
	Remark              field.String  // 备注
	Distribution        field.Int     // 是否分配 1 已分配 0 未分配
	DistributionTime    field.Int     // 分配时间
	OrderID             field.Int     // 订单Id
	Source              field.Int     // 激活码来源:1激活码商品,2预售库存,3系统生成/批量创建，4赠送库存
	Status              field.Int     // 0:正常（未激活）,1已激活，2删除
	Province            field.String  // 激活用户所在省份
	City                field.String  // 激活用户所在城市
	District            field.String  // 激活用户所在街道
	ExpireDays          field.Int     // 有效期（天）
	IsGift              field.Int     // 是否来自赠送
	OldUID              field.Int     // 激活码所属原始用户Id
	ViewCount           field.Int     // 课程完整观看次数
	ExpireHours         field.Int     // 有效时长（试用课程）
	CreateUID           field.Int     // 创建人
	WulouActivationCode field.String  // 无漏课程激活码
	WulouUserID         field.String  // 无漏用户Id
	MarkUID             field.Int     // 标记尝试激活的用户Id，用于关联无漏课程激活码
	DelayDays           field.Int     // 延期天数
	ImagineCourse       field.Int     // 想象力英语课程
	Inventory           field.Float64 // 消耗库存
	CloseTime           field.Int     // 下架时间
	PackageID           field.Int     // 组合包Id
	ParentID            field.Int     // 组合包原始激活码Id
	GiftType            field.Int     // 1赠送，2合同赠送，3当月返（购），4返库存,5助学赠送
	StoreID             field.Int     // 创建门店ID
	ActiveStoreID       field.Int     // 激活门店ID
	Location            field.String  // 激活经纬度坐标

	fieldMap map[string]field.Expr
}

func (s sysCourseActivation) Table(newTableName string) *sysCourseActivation {
	s.sysCourseActivationDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysCourseActivation) As(alias string) *sysCourseActivation {
	s.sysCourseActivationDo.DO = *(s.sysCourseActivationDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysCourseActivation) updateTableName(table string) *sysCourseActivation {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt(table, "id")
	s.UID = field.NewInt(table, "uid")
	s.ActivationCode = field.NewString(table, "activation_code")
	s.CourseType = field.NewInt(table, "course_type")
	s.UserID = field.NewInt(table, "user_id")
	s.CreateTime = field.NewInt(table, "create_time")
	s.ActivationTime = field.NewInt(table, "activation_time")
	s.Remark = field.NewString(table, "remark")
	s.Distribution = field.NewInt(table, "distribution")
	s.DistributionTime = field.NewInt(table, "distribution_time")
	s.OrderID = field.NewInt(table, "order_id")
	s.Source = field.NewInt(table, "source")
	s.Status = field.NewInt(table, "status")
	s.Province = field.NewString(table, "province")
	s.City = field.NewString(table, "city")
	s.District = field.NewString(table, "district")
	s.ExpireDays = field.NewInt(table, "expire_days")
	s.IsGift = field.NewInt(table, "is_gift")
	s.OldUID = field.NewInt(table, "old_uid")
	s.ViewCount = field.NewInt(table, "view_count")
	s.ExpireHours = field.NewInt(table, "expire_hours")
	s.CreateUID = field.NewInt(table, "create_uid")
	s.WulouActivationCode = field.NewString(table, "wulou_activation_code")
	s.WulouUserID = field.NewString(table, "wulou_user_id")
	s.MarkUID = field.NewInt(table, "mark_uid")
	s.DelayDays = field.NewInt(table, "delay_days")
	s.ImagineCourse = field.NewInt(table, "imagine_course")
	s.Inventory = field.NewFloat64(table, "inventory")
	s.CloseTime = field.NewInt(table, "close_time")
	s.PackageID = field.NewInt(table, "package_id")
	s.ParentID = field.NewInt(table, "parent_id")
	s.GiftType = field.NewInt(table, "gift_type")
	s.StoreID = field.NewInt(table, "store_id")
	s.ActiveStoreID = field.NewInt(table, "active_store_id")
	s.Location = field.NewString(table, "location")

	s.fillFieldMap()

	return s
}

func (s *sysCourseActivation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysCourseActivation) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 35)
	s.fieldMap["id"] = s.ID
	s.fieldMap["uid"] = s.UID
	s.fieldMap["activation_code"] = s.ActivationCode
	s.fieldMap["course_type"] = s.CourseType
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["activation_time"] = s.ActivationTime
	s.fieldMap["remark"] = s.Remark
	s.fieldMap["distribution"] = s.Distribution
	s.fieldMap["distribution_time"] = s.DistributionTime
	s.fieldMap["order_id"] = s.OrderID
	s.fieldMap["source"] = s.Source
	s.fieldMap["status"] = s.Status
	s.fieldMap["province"] = s.Province
	s.fieldMap["city"] = s.City
	s.fieldMap["district"] = s.District
	s.fieldMap["expire_days"] = s.ExpireDays
	s.fieldMap["is_gift"] = s.IsGift
	s.fieldMap["old_uid"] = s.OldUID
	s.fieldMap["view_count"] = s.ViewCount
	s.fieldMap["expire_hours"] = s.ExpireHours
	s.fieldMap["create_uid"] = s.CreateUID
	s.fieldMap["wulou_activation_code"] = s.WulouActivationCode
	s.fieldMap["wulou_user_id"] = s.WulouUserID
	s.fieldMap["mark_uid"] = s.MarkUID
	s.fieldMap["delay_days"] = s.DelayDays
	s.fieldMap["imagine_course"] = s.ImagineCourse
	s.fieldMap["inventory"] = s.Inventory
	s.fieldMap["close_time"] = s.CloseTime
	s.fieldMap["package_id"] = s.PackageID
	s.fieldMap["parent_id"] = s.ParentID
	s.fieldMap["gift_type"] = s.GiftType
	s.fieldMap["store_id"] = s.StoreID
	s.fieldMap["active_store_id"] = s.ActiveStoreID
	s.fieldMap["location"] = s.Location
}

func (s sysCourseActivation) clone(db *gorm.DB) sysCourseActivation {
	s.sysCourseActivationDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysCourseActivation) replaceDB(db *gorm.DB) sysCourseActivation {
	s.sysCourseActivationDo.ReplaceDB(db)
	return s
}

type sysCourseActivationDo struct{ gen.DO }

type ISysCourseActivationDo interface {
	gen.SubQuery
	Debug() ISysCourseActivationDo
	WithContext(ctx context.Context) ISysCourseActivationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysCourseActivationDo
	WriteDB() ISysCourseActivationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysCourseActivationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysCourseActivationDo
	Not(conds ...gen.Condition) ISysCourseActivationDo
	Or(conds ...gen.Condition) ISysCourseActivationDo
	Select(conds ...field.Expr) ISysCourseActivationDo
	Where(conds ...gen.Condition) ISysCourseActivationDo
	Order(conds ...field.Expr) ISysCourseActivationDo
	Distinct(cols ...field.Expr) ISysCourseActivationDo
	Omit(cols ...field.Expr) ISysCourseActivationDo
	Join(table schema.Tabler, on ...field.Expr) ISysCourseActivationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysCourseActivationDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysCourseActivationDo
	Group(cols ...field.Expr) ISysCourseActivationDo
	Having(conds ...gen.Condition) ISysCourseActivationDo
	Limit(limit int) ISysCourseActivationDo
	Offset(offset int) ISysCourseActivationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysCourseActivationDo
	Unscoped() ISysCourseActivationDo
	Create(values ...*fxshop.SysCourseActivation) error
	CreateInBatches(values []*fxshop.SysCourseActivation, batchSize int) error
	Save(values ...*fxshop.SysCourseActivation) error
	First() (*fxshop.SysCourseActivation, error)
	Take() (*fxshop.SysCourseActivation, error)
	Last() (*fxshop.SysCourseActivation, error)
	Find() ([]*fxshop.SysCourseActivation, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.SysCourseActivation, err error)
	FindInBatches(result *[]*fxshop.SysCourseActivation, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*fxshop.SysCourseActivation) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysCourseActivationDo
	Assign(attrs ...field.AssignExpr) ISysCourseActivationDo
	Joins(fields ...field.RelationField) ISysCourseActivationDo
	Preload(fields ...field.RelationField) ISysCourseActivationDo
	FirstOrInit() (*fxshop.SysCourseActivation, error)
	FirstOrCreate() (*fxshop.SysCourseActivation, error)
	FindByPage(offset int, limit int) (result []*fxshop.SysCourseActivation, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysCourseActivationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysCourseActivationDo) Debug() ISysCourseActivationDo {
	return s.withDO(s.DO.Debug())
}

func (s sysCourseActivationDo) WithContext(ctx context.Context) ISysCourseActivationDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysCourseActivationDo) ReadDB() ISysCourseActivationDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysCourseActivationDo) WriteDB() ISysCourseActivationDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysCourseActivationDo) Session(config *gorm.Session) ISysCourseActivationDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysCourseActivationDo) Clauses(conds ...clause.Expression) ISysCourseActivationDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysCourseActivationDo) Returning(value interface{}, columns ...string) ISysCourseActivationDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysCourseActivationDo) Not(conds ...gen.Condition) ISysCourseActivationDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysCourseActivationDo) Or(conds ...gen.Condition) ISysCourseActivationDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysCourseActivationDo) Select(conds ...field.Expr) ISysCourseActivationDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysCourseActivationDo) Where(conds ...gen.Condition) ISysCourseActivationDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysCourseActivationDo) Order(conds ...field.Expr) ISysCourseActivationDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysCourseActivationDo) Distinct(cols ...field.Expr) ISysCourseActivationDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysCourseActivationDo) Omit(cols ...field.Expr) ISysCourseActivationDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysCourseActivationDo) Join(table schema.Tabler, on ...field.Expr) ISysCourseActivationDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysCourseActivationDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysCourseActivationDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysCourseActivationDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysCourseActivationDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysCourseActivationDo) Group(cols ...field.Expr) ISysCourseActivationDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysCourseActivationDo) Having(conds ...gen.Condition) ISysCourseActivationDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysCourseActivationDo) Limit(limit int) ISysCourseActivationDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysCourseActivationDo) Offset(offset int) ISysCourseActivationDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysCourseActivationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysCourseActivationDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysCourseActivationDo) Unscoped() ISysCourseActivationDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysCourseActivationDo) Create(values ...*fxshop.SysCourseActivation) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysCourseActivationDo) CreateInBatches(values []*fxshop.SysCourseActivation, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysCourseActivationDo) Save(values ...*fxshop.SysCourseActivation) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysCourseActivationDo) First() (*fxshop.SysCourseActivation, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysCourseActivation), nil
	}
}

func (s sysCourseActivationDo) Take() (*fxshop.SysCourseActivation, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysCourseActivation), nil
	}
}

func (s sysCourseActivationDo) Last() (*fxshop.SysCourseActivation, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysCourseActivation), nil
	}
}

func (s sysCourseActivationDo) Find() ([]*fxshop.SysCourseActivation, error) {
	result, err := s.DO.Find()
	return result.([]*fxshop.SysCourseActivation), err
}

func (s sysCourseActivationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.SysCourseActivation, err error) {
	buf := make([]*fxshop.SysCourseActivation, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysCourseActivationDo) FindInBatches(result *[]*fxshop.SysCourseActivation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysCourseActivationDo) Attrs(attrs ...field.AssignExpr) ISysCourseActivationDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysCourseActivationDo) Assign(attrs ...field.AssignExpr) ISysCourseActivationDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysCourseActivationDo) Joins(fields ...field.RelationField) ISysCourseActivationDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysCourseActivationDo) Preload(fields ...field.RelationField) ISysCourseActivationDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysCourseActivationDo) FirstOrInit() (*fxshop.SysCourseActivation, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysCourseActivation), nil
	}
}

func (s sysCourseActivationDo) FirstOrCreate() (*fxshop.SysCourseActivation, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysCourseActivation), nil
	}
}

func (s sysCourseActivationDo) FindByPage(offset int, limit int) (result []*fxshop.SysCourseActivation, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysCourseActivationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysCourseActivationDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysCourseActivationDo) Delete(models ...*fxshop.SysCourseActivation) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysCourseActivationDo) withDO(do gen.Dao) *sysCourseActivationDo {
	s.DO = *do.(*gen.DO)
	return s
}
