// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"exam-api-sync-go/dao/model/fxshop"
)

func newSysExamUserLog(db *gorm.DB, opts ...gen.DOOption) sysExamUserLog {
	_sysExamUserLog := sysExamUserLog{}

	_sysExamUserLog.sysExamUserLogDo.UseDB(db, opts...)
	_sysExamUserLog.sysExamUserLogDo.UseModel(&fxshop.SysExamUserLog{})

	tableName := _sysExamUserLog.sysExamUserLogDo.TableName()
	_sysExamUserLog.ALL = field.NewAsterisk(tableName)
	_sysExamUserLog.ID = field.NewInt(tableName, "id")
	_sysExamUserLog.UID = field.NewInt(tableName, "uid")
	_sysExamUserLog.TestPaperID = field.NewInt(tableName, "test_paper_id")
	_sysExamUserLog.ExerciseID = field.NewInt(tableName, "exercise_id")
	_sysExamUserLog.Seconds = field.NewInt(tableName, "seconds")
	_sysExamUserLog.Answer = field.NewString(tableName, "answer")
	_sysExamUserLog.Correct = field.NewInt16(tableName, "correct")
	_sysExamUserLog.CreateTime = field.NewInt(tableName, "create_time")
	_sysExamUserLog.ParentID = field.NewInt(tableName, "parent_id")
	_sysExamUserLog.ResetAt = field.NewInt(tableName, "reset_at")
	_sysExamUserLog.State = field.NewString(tableName, "state")
	_sysExamUserLog.StepImgCount = field.NewInt8(tableName, "step_img_count")
	_sysExamUserLog.Offline = field.NewInt8(tableName, "offline")
	_sysExamUserLog.JyfsCorrectCount = field.NewInt(tableName, "jyfs_correct_count")

	_sysExamUserLog.fillFieldMap()

	return _sysExamUserLog
}

// sysExamUserLog 用户做题记录
type sysExamUserLog struct {
	sysExamUserLogDo

	ALL              field.Asterisk
	ID               field.Int    // 主键id
	UID              field.Int    // uid
	TestPaperID      field.Int    // 试卷Id(catalogue.id)
	ExerciseID       field.Int    // 试题Id(exercise.id)
	Seconds          field.Int    // 耗时(秒)
	Answer           field.String // 答案
	Correct          field.Int16  // 答案正确
	CreateTime       field.Int    // 录入时间
	ParentID         field.Int    // 用户试卷记录Id
	ResetAt          field.Int    // 重置时间
	State            field.String // 做题情况：1不会
	StepImgCount     field.Int8   // 解题步骤图片数量
	Offline          field.Int8   // 线下题
	JyfsCorrectCount field.Int    // 举一反三正确数量

	fieldMap map[string]field.Expr
}

func (s sysExamUserLog) Table(newTableName string) *sysExamUserLog {
	s.sysExamUserLogDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysExamUserLog) As(alias string) *sysExamUserLog {
	s.sysExamUserLogDo.DO = *(s.sysExamUserLogDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysExamUserLog) updateTableName(table string) *sysExamUserLog {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt(table, "id")
	s.UID = field.NewInt(table, "uid")
	s.TestPaperID = field.NewInt(table, "test_paper_id")
	s.ExerciseID = field.NewInt(table, "exercise_id")
	s.Seconds = field.NewInt(table, "seconds")
	s.Answer = field.NewString(table, "answer")
	s.Correct = field.NewInt16(table, "correct")
	s.CreateTime = field.NewInt(table, "create_time")
	s.ParentID = field.NewInt(table, "parent_id")
	s.ResetAt = field.NewInt(table, "reset_at")
	s.State = field.NewString(table, "state")
	s.StepImgCount = field.NewInt8(table, "step_img_count")
	s.Offline = field.NewInt8(table, "offline")
	s.JyfsCorrectCount = field.NewInt(table, "jyfs_correct_count")

	s.fillFieldMap()

	return s
}

func (s *sysExamUserLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysExamUserLog) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 14)
	s.fieldMap["id"] = s.ID
	s.fieldMap["uid"] = s.UID
	s.fieldMap["test_paper_id"] = s.TestPaperID
	s.fieldMap["exercise_id"] = s.ExerciseID
	s.fieldMap["seconds"] = s.Seconds
	s.fieldMap["answer"] = s.Answer
	s.fieldMap["correct"] = s.Correct
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["parent_id"] = s.ParentID
	s.fieldMap["reset_at"] = s.ResetAt
	s.fieldMap["state"] = s.State
	s.fieldMap["step_img_count"] = s.StepImgCount
	s.fieldMap["offline"] = s.Offline
	s.fieldMap["jyfs_correct_count"] = s.JyfsCorrectCount
}

func (s sysExamUserLog) clone(db *gorm.DB) sysExamUserLog {
	s.sysExamUserLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysExamUserLog) replaceDB(db *gorm.DB) sysExamUserLog {
	s.sysExamUserLogDo.ReplaceDB(db)
	return s
}

type sysExamUserLogDo struct{ gen.DO }

type ISysExamUserLogDo interface {
	gen.SubQuery
	Debug() ISysExamUserLogDo
	WithContext(ctx context.Context) ISysExamUserLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysExamUserLogDo
	WriteDB() ISysExamUserLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysExamUserLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysExamUserLogDo
	Not(conds ...gen.Condition) ISysExamUserLogDo
	Or(conds ...gen.Condition) ISysExamUserLogDo
	Select(conds ...field.Expr) ISysExamUserLogDo
	Where(conds ...gen.Condition) ISysExamUserLogDo
	Order(conds ...field.Expr) ISysExamUserLogDo
	Distinct(cols ...field.Expr) ISysExamUserLogDo
	Omit(cols ...field.Expr) ISysExamUserLogDo
	Join(table schema.Tabler, on ...field.Expr) ISysExamUserLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysExamUserLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysExamUserLogDo
	Group(cols ...field.Expr) ISysExamUserLogDo
	Having(conds ...gen.Condition) ISysExamUserLogDo
	Limit(limit int) ISysExamUserLogDo
	Offset(offset int) ISysExamUserLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysExamUserLogDo
	Unscoped() ISysExamUserLogDo
	Create(values ...*fxshop.SysExamUserLog) error
	CreateInBatches(values []*fxshop.SysExamUserLog, batchSize int) error
	Save(values ...*fxshop.SysExamUserLog) error
	First() (*fxshop.SysExamUserLog, error)
	Take() (*fxshop.SysExamUserLog, error)
	Last() (*fxshop.SysExamUserLog, error)
	Find() ([]*fxshop.SysExamUserLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.SysExamUserLog, err error)
	FindInBatches(result *[]*fxshop.SysExamUserLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*fxshop.SysExamUserLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysExamUserLogDo
	Assign(attrs ...field.AssignExpr) ISysExamUserLogDo
	Joins(fields ...field.RelationField) ISysExamUserLogDo
	Preload(fields ...field.RelationField) ISysExamUserLogDo
	FirstOrInit() (*fxshop.SysExamUserLog, error)
	FirstOrCreate() (*fxshop.SysExamUserLog, error)
	FindByPage(offset int, limit int) (result []*fxshop.SysExamUserLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysExamUserLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysExamUserLogDo) Debug() ISysExamUserLogDo {
	return s.withDO(s.DO.Debug())
}

func (s sysExamUserLogDo) WithContext(ctx context.Context) ISysExamUserLogDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysExamUserLogDo) ReadDB() ISysExamUserLogDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysExamUserLogDo) WriteDB() ISysExamUserLogDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysExamUserLogDo) Session(config *gorm.Session) ISysExamUserLogDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysExamUserLogDo) Clauses(conds ...clause.Expression) ISysExamUserLogDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysExamUserLogDo) Returning(value interface{}, columns ...string) ISysExamUserLogDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysExamUserLogDo) Not(conds ...gen.Condition) ISysExamUserLogDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysExamUserLogDo) Or(conds ...gen.Condition) ISysExamUserLogDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysExamUserLogDo) Select(conds ...field.Expr) ISysExamUserLogDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysExamUserLogDo) Where(conds ...gen.Condition) ISysExamUserLogDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysExamUserLogDo) Order(conds ...field.Expr) ISysExamUserLogDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysExamUserLogDo) Distinct(cols ...field.Expr) ISysExamUserLogDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysExamUserLogDo) Omit(cols ...field.Expr) ISysExamUserLogDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysExamUserLogDo) Join(table schema.Tabler, on ...field.Expr) ISysExamUserLogDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysExamUserLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysExamUserLogDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysExamUserLogDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysExamUserLogDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysExamUserLogDo) Group(cols ...field.Expr) ISysExamUserLogDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysExamUserLogDo) Having(conds ...gen.Condition) ISysExamUserLogDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysExamUserLogDo) Limit(limit int) ISysExamUserLogDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysExamUserLogDo) Offset(offset int) ISysExamUserLogDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysExamUserLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysExamUserLogDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysExamUserLogDo) Unscoped() ISysExamUserLogDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysExamUserLogDo) Create(values ...*fxshop.SysExamUserLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysExamUserLogDo) CreateInBatches(values []*fxshop.SysExamUserLog, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysExamUserLogDo) Save(values ...*fxshop.SysExamUserLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysExamUserLogDo) First() (*fxshop.SysExamUserLog, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysExamUserLog), nil
	}
}

func (s sysExamUserLogDo) Take() (*fxshop.SysExamUserLog, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysExamUserLog), nil
	}
}

func (s sysExamUserLogDo) Last() (*fxshop.SysExamUserLog, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysExamUserLog), nil
	}
}

func (s sysExamUserLogDo) Find() ([]*fxshop.SysExamUserLog, error) {
	result, err := s.DO.Find()
	return result.([]*fxshop.SysExamUserLog), err
}

func (s sysExamUserLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.SysExamUserLog, err error) {
	buf := make([]*fxshop.SysExamUserLog, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysExamUserLogDo) FindInBatches(result *[]*fxshop.SysExamUserLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysExamUserLogDo) Attrs(attrs ...field.AssignExpr) ISysExamUserLogDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysExamUserLogDo) Assign(attrs ...field.AssignExpr) ISysExamUserLogDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysExamUserLogDo) Joins(fields ...field.RelationField) ISysExamUserLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysExamUserLogDo) Preload(fields ...field.RelationField) ISysExamUserLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysExamUserLogDo) FirstOrInit() (*fxshop.SysExamUserLog, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysExamUserLog), nil
	}
}

func (s sysExamUserLogDo) FirstOrCreate() (*fxshop.SysExamUserLog, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysExamUserLog), nil
	}
}

func (s sysExamUserLogDo) FindByPage(offset int, limit int) (result []*fxshop.SysExamUserLog, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysExamUserLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysExamUserLogDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysExamUserLogDo) Delete(models ...*fxshop.SysExamUserLog) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysExamUserLogDo) withDO(do gen.Dao) *sysExamUserLogDo {
	s.DO = *do.(*gen.DO)
	return s
}
