// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"exam-api-sync-go/dao/model/fxshop"
)

func newSysUserZgkInventory(db *gorm.DB, opts ...gen.DOOption) sysUserZgkInventory {
	_sysUserZgkInventory := sysUserZgkInventory{}

	_sysUserZgkInventory.sysUserZgkInventoryDo.UseDB(db, opts...)
	_sysUserZgkInventory.sysUserZgkInventoryDo.UseModel(&fxshop.SysUserZgkInventory{})

	tableName := _sysUserZgkInventory.sysUserZgkInventoryDo.TableName()
	_sysUserZgkInventory.ALL = field.NewAsterisk(tableName)
	_sysUserZgkInventory.ID = field.NewInt(tableName, "id")
	_sysUserZgkInventory.UID = field.NewInt(tableName, "uid")
	_sysUserZgkInventory.Balance = field.NewFloat64(tableName, "balance")
	_sysUserZgkInventory.Consumed = field.NewFloat64(tableName, "consumed")
	_sysUserZgkInventory.CreateTime = field.NewInt(tableName, "create_time")
	_sysUserZgkInventory.Buy = field.NewFloat64(tableName, "buy")
	_sysUserZgkInventory.Receive = field.NewFloat64(tableName, "receive")
	_sysUserZgkInventory.Send = field.NewFloat64(tableName, "send")
	_sysUserZgkInventory.Gift = field.NewFloat64(tableName, "gift")
	_sysUserZgkInventory.Back = field.NewFloat64(tableName, "back")
	_sysUserZgkInventory.Type = field.NewInt(tableName, "type")
	_sysUserZgkInventory.ContractualGift = field.NewFloat64(tableName, "contractual_gift")
	_sysUserZgkInventory.BackWithinCurrentMonth = field.NewFloat64(tableName, "back_within_current_month")
	_sysUserZgkInventory.BackBeforeMonth = field.NewFloat64(tableName, "back_before_month")
	_sysUserZgkInventory.Sponsorship = field.NewFloat64(tableName, "sponsorship")

	_sysUserZgkInventory.fillFieldMap()

	return _sysUserZgkInventory
}

// sysUserZgkInventory 中高考课程激活码库存
type sysUserZgkInventory struct {
	sysUserZgkInventoryDo

	ALL                    field.Asterisk
	ID                     field.Int     // 主键id
	UID                    field.Int     // 会员id
	Balance                field.Float64 // 剩余库存
	Consumed               field.Float64 // 已消耗
	CreateTime             field.Int     // 记录时间
	Buy                    field.Float64 // 自购库存
	Receive                field.Float64 // 上级分配库存
	Send                   field.Float64 // 分配下级库存
	Gift                   field.Float64 // 赠送库存
	Back                   field.Float64 // 作废转库存，激活码退还
	Type                   field.Int     // 库存类型：1中高考库存，2限时库存
	ContractualGift        field.Float64 // 合同赠送
	BackWithinCurrentMonth field.Float64 // 返库存（当月作废的购买库存）
	BackBeforeMonth        field.Float64 // 返库存（非当月购买或当月作废的赠送库存）
	Sponsorship            field.Float64 // 助学赠送

	fieldMap map[string]field.Expr
}

func (s sysUserZgkInventory) Table(newTableName string) *sysUserZgkInventory {
	s.sysUserZgkInventoryDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysUserZgkInventory) As(alias string) *sysUserZgkInventory {
	s.sysUserZgkInventoryDo.DO = *(s.sysUserZgkInventoryDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysUserZgkInventory) updateTableName(table string) *sysUserZgkInventory {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt(table, "id")
	s.UID = field.NewInt(table, "uid")
	s.Balance = field.NewFloat64(table, "balance")
	s.Consumed = field.NewFloat64(table, "consumed")
	s.CreateTime = field.NewInt(table, "create_time")
	s.Buy = field.NewFloat64(table, "buy")
	s.Receive = field.NewFloat64(table, "receive")
	s.Send = field.NewFloat64(table, "send")
	s.Gift = field.NewFloat64(table, "gift")
	s.Back = field.NewFloat64(table, "back")
	s.Type = field.NewInt(table, "type")
	s.ContractualGift = field.NewFloat64(table, "contractual_gift")
	s.BackWithinCurrentMonth = field.NewFloat64(table, "back_within_current_month")
	s.BackBeforeMonth = field.NewFloat64(table, "back_before_month")
	s.Sponsorship = field.NewFloat64(table, "sponsorship")

	s.fillFieldMap()

	return s
}

func (s *sysUserZgkInventory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysUserZgkInventory) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 15)
	s.fieldMap["id"] = s.ID
	s.fieldMap["uid"] = s.UID
	s.fieldMap["balance"] = s.Balance
	s.fieldMap["consumed"] = s.Consumed
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["buy"] = s.Buy
	s.fieldMap["receive"] = s.Receive
	s.fieldMap["send"] = s.Send
	s.fieldMap["gift"] = s.Gift
	s.fieldMap["back"] = s.Back
	s.fieldMap["type"] = s.Type
	s.fieldMap["contractual_gift"] = s.ContractualGift
	s.fieldMap["back_within_current_month"] = s.BackWithinCurrentMonth
	s.fieldMap["back_before_month"] = s.BackBeforeMonth
	s.fieldMap["sponsorship"] = s.Sponsorship
}

func (s sysUserZgkInventory) clone(db *gorm.DB) sysUserZgkInventory {
	s.sysUserZgkInventoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysUserZgkInventory) replaceDB(db *gorm.DB) sysUserZgkInventory {
	s.sysUserZgkInventoryDo.ReplaceDB(db)
	return s
}

type sysUserZgkInventoryDo struct{ gen.DO }

type ISysUserZgkInventoryDo interface {
	gen.SubQuery
	Debug() ISysUserZgkInventoryDo
	WithContext(ctx context.Context) ISysUserZgkInventoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysUserZgkInventoryDo
	WriteDB() ISysUserZgkInventoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysUserZgkInventoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysUserZgkInventoryDo
	Not(conds ...gen.Condition) ISysUserZgkInventoryDo
	Or(conds ...gen.Condition) ISysUserZgkInventoryDo
	Select(conds ...field.Expr) ISysUserZgkInventoryDo
	Where(conds ...gen.Condition) ISysUserZgkInventoryDo
	Order(conds ...field.Expr) ISysUserZgkInventoryDo
	Distinct(cols ...field.Expr) ISysUserZgkInventoryDo
	Omit(cols ...field.Expr) ISysUserZgkInventoryDo
	Join(table schema.Tabler, on ...field.Expr) ISysUserZgkInventoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysUserZgkInventoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysUserZgkInventoryDo
	Group(cols ...field.Expr) ISysUserZgkInventoryDo
	Having(conds ...gen.Condition) ISysUserZgkInventoryDo
	Limit(limit int) ISysUserZgkInventoryDo
	Offset(offset int) ISysUserZgkInventoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysUserZgkInventoryDo
	Unscoped() ISysUserZgkInventoryDo
	Create(values ...*fxshop.SysUserZgkInventory) error
	CreateInBatches(values []*fxshop.SysUserZgkInventory, batchSize int) error
	Save(values ...*fxshop.SysUserZgkInventory) error
	First() (*fxshop.SysUserZgkInventory, error)
	Take() (*fxshop.SysUserZgkInventory, error)
	Last() (*fxshop.SysUserZgkInventory, error)
	Find() ([]*fxshop.SysUserZgkInventory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.SysUserZgkInventory, err error)
	FindInBatches(result *[]*fxshop.SysUserZgkInventory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*fxshop.SysUserZgkInventory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysUserZgkInventoryDo
	Assign(attrs ...field.AssignExpr) ISysUserZgkInventoryDo
	Joins(fields ...field.RelationField) ISysUserZgkInventoryDo
	Preload(fields ...field.RelationField) ISysUserZgkInventoryDo
	FirstOrInit() (*fxshop.SysUserZgkInventory, error)
	FirstOrCreate() (*fxshop.SysUserZgkInventory, error)
	FindByPage(offset int, limit int) (result []*fxshop.SysUserZgkInventory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysUserZgkInventoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysUserZgkInventoryDo) Debug() ISysUserZgkInventoryDo {
	return s.withDO(s.DO.Debug())
}

func (s sysUserZgkInventoryDo) WithContext(ctx context.Context) ISysUserZgkInventoryDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysUserZgkInventoryDo) ReadDB() ISysUserZgkInventoryDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysUserZgkInventoryDo) WriteDB() ISysUserZgkInventoryDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysUserZgkInventoryDo) Session(config *gorm.Session) ISysUserZgkInventoryDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysUserZgkInventoryDo) Clauses(conds ...clause.Expression) ISysUserZgkInventoryDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysUserZgkInventoryDo) Returning(value interface{}, columns ...string) ISysUserZgkInventoryDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysUserZgkInventoryDo) Not(conds ...gen.Condition) ISysUserZgkInventoryDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysUserZgkInventoryDo) Or(conds ...gen.Condition) ISysUserZgkInventoryDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysUserZgkInventoryDo) Select(conds ...field.Expr) ISysUserZgkInventoryDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysUserZgkInventoryDo) Where(conds ...gen.Condition) ISysUserZgkInventoryDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysUserZgkInventoryDo) Order(conds ...field.Expr) ISysUserZgkInventoryDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysUserZgkInventoryDo) Distinct(cols ...field.Expr) ISysUserZgkInventoryDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysUserZgkInventoryDo) Omit(cols ...field.Expr) ISysUserZgkInventoryDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysUserZgkInventoryDo) Join(table schema.Tabler, on ...field.Expr) ISysUserZgkInventoryDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysUserZgkInventoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysUserZgkInventoryDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysUserZgkInventoryDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysUserZgkInventoryDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysUserZgkInventoryDo) Group(cols ...field.Expr) ISysUserZgkInventoryDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysUserZgkInventoryDo) Having(conds ...gen.Condition) ISysUserZgkInventoryDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysUserZgkInventoryDo) Limit(limit int) ISysUserZgkInventoryDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysUserZgkInventoryDo) Offset(offset int) ISysUserZgkInventoryDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysUserZgkInventoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysUserZgkInventoryDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysUserZgkInventoryDo) Unscoped() ISysUserZgkInventoryDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysUserZgkInventoryDo) Create(values ...*fxshop.SysUserZgkInventory) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysUserZgkInventoryDo) CreateInBatches(values []*fxshop.SysUserZgkInventory, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysUserZgkInventoryDo) Save(values ...*fxshop.SysUserZgkInventory) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysUserZgkInventoryDo) First() (*fxshop.SysUserZgkInventory, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysUserZgkInventory), nil
	}
}

func (s sysUserZgkInventoryDo) Take() (*fxshop.SysUserZgkInventory, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysUserZgkInventory), nil
	}
}

func (s sysUserZgkInventoryDo) Last() (*fxshop.SysUserZgkInventory, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysUserZgkInventory), nil
	}
}

func (s sysUserZgkInventoryDo) Find() ([]*fxshop.SysUserZgkInventory, error) {
	result, err := s.DO.Find()
	return result.([]*fxshop.SysUserZgkInventory), err
}

func (s sysUserZgkInventoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.SysUserZgkInventory, err error) {
	buf := make([]*fxshop.SysUserZgkInventory, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysUserZgkInventoryDo) FindInBatches(result *[]*fxshop.SysUserZgkInventory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysUserZgkInventoryDo) Attrs(attrs ...field.AssignExpr) ISysUserZgkInventoryDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysUserZgkInventoryDo) Assign(attrs ...field.AssignExpr) ISysUserZgkInventoryDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysUserZgkInventoryDo) Joins(fields ...field.RelationField) ISysUserZgkInventoryDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysUserZgkInventoryDo) Preload(fields ...field.RelationField) ISysUserZgkInventoryDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysUserZgkInventoryDo) FirstOrInit() (*fxshop.SysUserZgkInventory, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysUserZgkInventory), nil
	}
}

func (s sysUserZgkInventoryDo) FirstOrCreate() (*fxshop.SysUserZgkInventory, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.SysUserZgkInventory), nil
	}
}

func (s sysUserZgkInventoryDo) FindByPage(offset int, limit int) (result []*fxshop.SysUserZgkInventory, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysUserZgkInventoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysUserZgkInventoryDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysUserZgkInventoryDo) Delete(models ...*fxshop.SysUserZgkInventory) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysUserZgkInventoryDo) withDO(do gen.Dao) *sysUserZgkInventoryDo {
	s.DO = *do.(*gen.DO)
	return s
}
