// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"exam-api-sync-go/dao/model/fxshop"
)

func newUserTestingInfo(db *gorm.DB, opts ...gen.DOOption) userTestingInfo {
	_userTestingInfo := userTestingInfo{}

	_userTestingInfo.userTestingInfoDo.UseDB(db, opts...)
	_userTestingInfo.userTestingInfoDo.UseModel(&fxshop.UserTestingInfo{})

	tableName := _userTestingInfo.userTestingInfoDo.TableName()
	_userTestingInfo.ALL = field.NewAsterisk(tableName)
	_userTestingInfo.InfoID = field.NewInt(tableName, "info_id")
	_userTestingInfo.UID = field.NewInt(tableName, "uid")
	_userTestingInfo.Result = field.NewString(tableName, "result")
	_userTestingInfo.ResultType = field.NewString(tableName, "result_type")
	_userTestingInfo.Ext = field.NewString(tableName, "ext")
	_userTestingInfo.TestType = field.NewInt8(tableName, "test_type")
	_userTestingInfo.CreateTime = field.NewInt(tableName, "create_time")
	_userTestingInfo.PieChart = field.NewString(tableName, "pieChart")

	_userTestingInfo.fillFieldMap()

	return _userTestingInfo
}

// userTestingInfo 用户测试表
type userTestingInfo struct {
	userTestingInfoDo

	ALL        field.Asterisk
	InfoID     field.Int
	UID        field.Int    // 会员id
	Result     field.String // 测试结果
	ResultType field.String // 结果类型
	Ext        field.String // 扩展信息
	TestType   field.Int8   // 测试类型：1天赋
	CreateTime field.Int    // 添加时间
	PieChart   field.String // 饼图数据

	fieldMap map[string]field.Expr
}

func (u userTestingInfo) Table(newTableName string) *userTestingInfo {
	u.userTestingInfoDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userTestingInfo) As(alias string) *userTestingInfo {
	u.userTestingInfoDo.DO = *(u.userTestingInfoDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userTestingInfo) updateTableName(table string) *userTestingInfo {
	u.ALL = field.NewAsterisk(table)
	u.InfoID = field.NewInt(table, "info_id")
	u.UID = field.NewInt(table, "uid")
	u.Result = field.NewString(table, "result")
	u.ResultType = field.NewString(table, "result_type")
	u.Ext = field.NewString(table, "ext")
	u.TestType = field.NewInt8(table, "test_type")
	u.CreateTime = field.NewInt(table, "create_time")
	u.PieChart = field.NewString(table, "pieChart")

	u.fillFieldMap()

	return u
}

func (u *userTestingInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userTestingInfo) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 8)
	u.fieldMap["info_id"] = u.InfoID
	u.fieldMap["uid"] = u.UID
	u.fieldMap["result"] = u.Result
	u.fieldMap["result_type"] = u.ResultType
	u.fieldMap["ext"] = u.Ext
	u.fieldMap["test_type"] = u.TestType
	u.fieldMap["create_time"] = u.CreateTime
	u.fieldMap["pieChart"] = u.PieChart
}

func (u userTestingInfo) clone(db *gorm.DB) userTestingInfo {
	u.userTestingInfoDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userTestingInfo) replaceDB(db *gorm.DB) userTestingInfo {
	u.userTestingInfoDo.ReplaceDB(db)
	return u
}

type userTestingInfoDo struct{ gen.DO }

type IUserTestingInfoDo interface {
	gen.SubQuery
	Debug() IUserTestingInfoDo
	WithContext(ctx context.Context) IUserTestingInfoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserTestingInfoDo
	WriteDB() IUserTestingInfoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserTestingInfoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserTestingInfoDo
	Not(conds ...gen.Condition) IUserTestingInfoDo
	Or(conds ...gen.Condition) IUserTestingInfoDo
	Select(conds ...field.Expr) IUserTestingInfoDo
	Where(conds ...gen.Condition) IUserTestingInfoDo
	Order(conds ...field.Expr) IUserTestingInfoDo
	Distinct(cols ...field.Expr) IUserTestingInfoDo
	Omit(cols ...field.Expr) IUserTestingInfoDo
	Join(table schema.Tabler, on ...field.Expr) IUserTestingInfoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserTestingInfoDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserTestingInfoDo
	Group(cols ...field.Expr) IUserTestingInfoDo
	Having(conds ...gen.Condition) IUserTestingInfoDo
	Limit(limit int) IUserTestingInfoDo
	Offset(offset int) IUserTestingInfoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserTestingInfoDo
	Unscoped() IUserTestingInfoDo
	Create(values ...*fxshop.UserTestingInfo) error
	CreateInBatches(values []*fxshop.UserTestingInfo, batchSize int) error
	Save(values ...*fxshop.UserTestingInfo) error
	First() (*fxshop.UserTestingInfo, error)
	Take() (*fxshop.UserTestingInfo, error)
	Last() (*fxshop.UserTestingInfo, error)
	Find() ([]*fxshop.UserTestingInfo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.UserTestingInfo, err error)
	FindInBatches(result *[]*fxshop.UserTestingInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*fxshop.UserTestingInfo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserTestingInfoDo
	Assign(attrs ...field.AssignExpr) IUserTestingInfoDo
	Joins(fields ...field.RelationField) IUserTestingInfoDo
	Preload(fields ...field.RelationField) IUserTestingInfoDo
	FirstOrInit() (*fxshop.UserTestingInfo, error)
	FirstOrCreate() (*fxshop.UserTestingInfo, error)
	FindByPage(offset int, limit int) (result []*fxshop.UserTestingInfo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserTestingInfoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userTestingInfoDo) Debug() IUserTestingInfoDo {
	return u.withDO(u.DO.Debug())
}

func (u userTestingInfoDo) WithContext(ctx context.Context) IUserTestingInfoDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userTestingInfoDo) ReadDB() IUserTestingInfoDo {
	return u.Clauses(dbresolver.Read)
}

func (u userTestingInfoDo) WriteDB() IUserTestingInfoDo {
	return u.Clauses(dbresolver.Write)
}

func (u userTestingInfoDo) Session(config *gorm.Session) IUserTestingInfoDo {
	return u.withDO(u.DO.Session(config))
}

func (u userTestingInfoDo) Clauses(conds ...clause.Expression) IUserTestingInfoDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userTestingInfoDo) Returning(value interface{}, columns ...string) IUserTestingInfoDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userTestingInfoDo) Not(conds ...gen.Condition) IUserTestingInfoDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userTestingInfoDo) Or(conds ...gen.Condition) IUserTestingInfoDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userTestingInfoDo) Select(conds ...field.Expr) IUserTestingInfoDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userTestingInfoDo) Where(conds ...gen.Condition) IUserTestingInfoDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userTestingInfoDo) Order(conds ...field.Expr) IUserTestingInfoDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userTestingInfoDo) Distinct(cols ...field.Expr) IUserTestingInfoDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userTestingInfoDo) Omit(cols ...field.Expr) IUserTestingInfoDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userTestingInfoDo) Join(table schema.Tabler, on ...field.Expr) IUserTestingInfoDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userTestingInfoDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserTestingInfoDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userTestingInfoDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserTestingInfoDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userTestingInfoDo) Group(cols ...field.Expr) IUserTestingInfoDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userTestingInfoDo) Having(conds ...gen.Condition) IUserTestingInfoDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userTestingInfoDo) Limit(limit int) IUserTestingInfoDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userTestingInfoDo) Offset(offset int) IUserTestingInfoDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userTestingInfoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserTestingInfoDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userTestingInfoDo) Unscoped() IUserTestingInfoDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userTestingInfoDo) Create(values ...*fxshop.UserTestingInfo) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userTestingInfoDo) CreateInBatches(values []*fxshop.UserTestingInfo, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userTestingInfoDo) Save(values ...*fxshop.UserTestingInfo) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userTestingInfoDo) First() (*fxshop.UserTestingInfo, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.UserTestingInfo), nil
	}
}

func (u userTestingInfoDo) Take() (*fxshop.UserTestingInfo, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.UserTestingInfo), nil
	}
}

func (u userTestingInfoDo) Last() (*fxshop.UserTestingInfo, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.UserTestingInfo), nil
	}
}

func (u userTestingInfoDo) Find() ([]*fxshop.UserTestingInfo, error) {
	result, err := u.DO.Find()
	return result.([]*fxshop.UserTestingInfo), err
}

func (u userTestingInfoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.UserTestingInfo, err error) {
	buf := make([]*fxshop.UserTestingInfo, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userTestingInfoDo) FindInBatches(result *[]*fxshop.UserTestingInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userTestingInfoDo) Attrs(attrs ...field.AssignExpr) IUserTestingInfoDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userTestingInfoDo) Assign(attrs ...field.AssignExpr) IUserTestingInfoDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userTestingInfoDo) Joins(fields ...field.RelationField) IUserTestingInfoDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userTestingInfoDo) Preload(fields ...field.RelationField) IUserTestingInfoDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userTestingInfoDo) FirstOrInit() (*fxshop.UserTestingInfo, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.UserTestingInfo), nil
	}
}

func (u userTestingInfoDo) FirstOrCreate() (*fxshop.UserTestingInfo, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.UserTestingInfo), nil
	}
}

func (u userTestingInfoDo) FindByPage(offset int, limit int) (result []*fxshop.UserTestingInfo, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userTestingInfoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userTestingInfoDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userTestingInfoDo) Delete(models ...*fxshop.UserTestingInfo) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userTestingInfoDo) withDO(do gen.Dao) *userTestingInfoDo {
	u.DO = *do.(*gen.DO)
	return u
}
