// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"exam-api-sync-go/dao/model/fxshop"
)

func newVslPromotionMansong(db *gorm.DB, opts ...gen.DOOption) vslPromotionMansong {
	_vslPromotionMansong := vslPromotionMansong{}

	_vslPromotionMansong.vslPromotionMansongDo.UseDB(db, opts...)
	_vslPromotionMansong.vslPromotionMansongDo.UseModel(&fxshop.VslPromotionMansong{})

	tableName := _vslPromotionMansong.vslPromotionMansongDo.TableName()
	_vslPromotionMansong.ALL = field.NewAsterisk(tableName)
	_vslPromotionMansong.MansongID = field.NewInt(tableName, "mansong_id")
	_vslPromotionMansong.MansongName = field.NewString(tableName, "mansong_name")
	_vslPromotionMansong.ShopID = field.NewInt(tableName, "shop_id")
	_vslPromotionMansong.ShopName = field.NewString(tableName, "shop_name")
	_vslPromotionMansong.Status = field.NewInt8(tableName, "status")
	_vslPromotionMansong.Remark = field.NewString(tableName, "remark")
	_vslPromotionMansong.Type = field.NewInt8(tableName, "type")
	_vslPromotionMansong.RangeType = field.NewInt8(tableName, "range_type")
	_vslPromotionMansong.StartTime = field.NewInt(tableName, "start_time")
	_vslPromotionMansong.EndTime = field.NewInt(tableName, "end_time")
	_vslPromotionMansong.CreateTime = field.NewInt(tableName, "create_time")
	_vslPromotionMansong.ModifyTime = field.NewInt(tableName, "modify_time")
	_vslPromotionMansong.WebsiteID = field.NewInt(tableName, "website_id")
	_vslPromotionMansong.Range = field.NewInt8(tableName, "range")
	_vslPromotionMansong.Level = field.NewInt(tableName, "level")
	_vslPromotionMansong.CategoryExtendID = field.NewString(tableName, "category_extend_id")
	_vslPromotionMansong.ExtendCategoryId1S = field.NewString(tableName, "extend_category_id_1s")
	_vslPromotionMansong.ExtendCategoryId2S = field.NewString(tableName, "extend_category_id_2s")
	_vslPromotionMansong.ExtendCategoryId3S = field.NewString(tableName, "extend_category_id_3s")

	_vslPromotionMansong.fillFieldMap()

	return _vslPromotionMansong
}

// vslPromotionMansong 满就送活动表
type vslPromotionMansong struct {
	vslPromotionMansongDo

	ALL                field.Asterisk
	MansongID          field.Int    // 满送活动编号
	MansongName        field.String // 活动名称
	ShopID             field.Int    // 店铺编号
	ShopName           field.String // 店铺名称
	Status             field.Int8   // 活动状态(0-未发布/1-正常/3-关闭/4-结束)
	Remark             field.String // 备注
	Type               field.Int8   // 1.普通优惠  2.多级优惠
	RangeType          field.Int8   // 1全部商品 0部分商品
	StartTime          field.Int    // 活动开始时间
	EndTime            field.Int    // 活动结束时间
	CreateTime         field.Int    // 创建时间
	ModifyTime         field.Int    // 修改时间
	WebsiteID          field.Int    // 实例信息
	Range              field.Int8   // 1:自营店 2:全平台
	Level              field.Int    // 优先级
	CategoryExtendID   field.String // 分类
	ExtendCategoryId1S field.String
	ExtendCategoryId2S field.String
	ExtendCategoryId3S field.String

	fieldMap map[string]field.Expr
}

func (v vslPromotionMansong) Table(newTableName string) *vslPromotionMansong {
	v.vslPromotionMansongDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v vslPromotionMansong) As(alias string) *vslPromotionMansong {
	v.vslPromotionMansongDo.DO = *(v.vslPromotionMansongDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *vslPromotionMansong) updateTableName(table string) *vslPromotionMansong {
	v.ALL = field.NewAsterisk(table)
	v.MansongID = field.NewInt(table, "mansong_id")
	v.MansongName = field.NewString(table, "mansong_name")
	v.ShopID = field.NewInt(table, "shop_id")
	v.ShopName = field.NewString(table, "shop_name")
	v.Status = field.NewInt8(table, "status")
	v.Remark = field.NewString(table, "remark")
	v.Type = field.NewInt8(table, "type")
	v.RangeType = field.NewInt8(table, "range_type")
	v.StartTime = field.NewInt(table, "start_time")
	v.EndTime = field.NewInt(table, "end_time")
	v.CreateTime = field.NewInt(table, "create_time")
	v.ModifyTime = field.NewInt(table, "modify_time")
	v.WebsiteID = field.NewInt(table, "website_id")
	v.Range = field.NewInt8(table, "range")
	v.Level = field.NewInt(table, "level")
	v.CategoryExtendID = field.NewString(table, "category_extend_id")
	v.ExtendCategoryId1S = field.NewString(table, "extend_category_id_1s")
	v.ExtendCategoryId2S = field.NewString(table, "extend_category_id_2s")
	v.ExtendCategoryId3S = field.NewString(table, "extend_category_id_3s")

	v.fillFieldMap()

	return v
}

func (v *vslPromotionMansong) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *vslPromotionMansong) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 19)
	v.fieldMap["mansong_id"] = v.MansongID
	v.fieldMap["mansong_name"] = v.MansongName
	v.fieldMap["shop_id"] = v.ShopID
	v.fieldMap["shop_name"] = v.ShopName
	v.fieldMap["status"] = v.Status
	v.fieldMap["remark"] = v.Remark
	v.fieldMap["type"] = v.Type
	v.fieldMap["range_type"] = v.RangeType
	v.fieldMap["start_time"] = v.StartTime
	v.fieldMap["end_time"] = v.EndTime
	v.fieldMap["create_time"] = v.CreateTime
	v.fieldMap["modify_time"] = v.ModifyTime
	v.fieldMap["website_id"] = v.WebsiteID
	v.fieldMap["range"] = v.Range
	v.fieldMap["level"] = v.Level
	v.fieldMap["category_extend_id"] = v.CategoryExtendID
	v.fieldMap["extend_category_id_1s"] = v.ExtendCategoryId1S
	v.fieldMap["extend_category_id_2s"] = v.ExtendCategoryId2S
	v.fieldMap["extend_category_id_3s"] = v.ExtendCategoryId3S
}

func (v vslPromotionMansong) clone(db *gorm.DB) vslPromotionMansong {
	v.vslPromotionMansongDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v vslPromotionMansong) replaceDB(db *gorm.DB) vslPromotionMansong {
	v.vslPromotionMansongDo.ReplaceDB(db)
	return v
}

type vslPromotionMansongDo struct{ gen.DO }

type IVslPromotionMansongDo interface {
	gen.SubQuery
	Debug() IVslPromotionMansongDo
	WithContext(ctx context.Context) IVslPromotionMansongDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IVslPromotionMansongDo
	WriteDB() IVslPromotionMansongDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IVslPromotionMansongDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IVslPromotionMansongDo
	Not(conds ...gen.Condition) IVslPromotionMansongDo
	Or(conds ...gen.Condition) IVslPromotionMansongDo
	Select(conds ...field.Expr) IVslPromotionMansongDo
	Where(conds ...gen.Condition) IVslPromotionMansongDo
	Order(conds ...field.Expr) IVslPromotionMansongDo
	Distinct(cols ...field.Expr) IVslPromotionMansongDo
	Omit(cols ...field.Expr) IVslPromotionMansongDo
	Join(table schema.Tabler, on ...field.Expr) IVslPromotionMansongDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IVslPromotionMansongDo
	RightJoin(table schema.Tabler, on ...field.Expr) IVslPromotionMansongDo
	Group(cols ...field.Expr) IVslPromotionMansongDo
	Having(conds ...gen.Condition) IVslPromotionMansongDo
	Limit(limit int) IVslPromotionMansongDo
	Offset(offset int) IVslPromotionMansongDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IVslPromotionMansongDo
	Unscoped() IVslPromotionMansongDo
	Create(values ...*fxshop.VslPromotionMansong) error
	CreateInBatches(values []*fxshop.VslPromotionMansong, batchSize int) error
	Save(values ...*fxshop.VslPromotionMansong) error
	First() (*fxshop.VslPromotionMansong, error)
	Take() (*fxshop.VslPromotionMansong, error)
	Last() (*fxshop.VslPromotionMansong, error)
	Find() ([]*fxshop.VslPromotionMansong, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.VslPromotionMansong, err error)
	FindInBatches(result *[]*fxshop.VslPromotionMansong, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*fxshop.VslPromotionMansong) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IVslPromotionMansongDo
	Assign(attrs ...field.AssignExpr) IVslPromotionMansongDo
	Joins(fields ...field.RelationField) IVslPromotionMansongDo
	Preload(fields ...field.RelationField) IVslPromotionMansongDo
	FirstOrInit() (*fxshop.VslPromotionMansong, error)
	FirstOrCreate() (*fxshop.VslPromotionMansong, error)
	FindByPage(offset int, limit int) (result []*fxshop.VslPromotionMansong, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IVslPromotionMansongDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (v vslPromotionMansongDo) Debug() IVslPromotionMansongDo {
	return v.withDO(v.DO.Debug())
}

func (v vslPromotionMansongDo) WithContext(ctx context.Context) IVslPromotionMansongDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v vslPromotionMansongDo) ReadDB() IVslPromotionMansongDo {
	return v.Clauses(dbresolver.Read)
}

func (v vslPromotionMansongDo) WriteDB() IVslPromotionMansongDo {
	return v.Clauses(dbresolver.Write)
}

func (v vslPromotionMansongDo) Session(config *gorm.Session) IVslPromotionMansongDo {
	return v.withDO(v.DO.Session(config))
}

func (v vslPromotionMansongDo) Clauses(conds ...clause.Expression) IVslPromotionMansongDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v vslPromotionMansongDo) Returning(value interface{}, columns ...string) IVslPromotionMansongDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v vslPromotionMansongDo) Not(conds ...gen.Condition) IVslPromotionMansongDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v vslPromotionMansongDo) Or(conds ...gen.Condition) IVslPromotionMansongDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v vslPromotionMansongDo) Select(conds ...field.Expr) IVslPromotionMansongDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v vslPromotionMansongDo) Where(conds ...gen.Condition) IVslPromotionMansongDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v vslPromotionMansongDo) Order(conds ...field.Expr) IVslPromotionMansongDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v vslPromotionMansongDo) Distinct(cols ...field.Expr) IVslPromotionMansongDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v vslPromotionMansongDo) Omit(cols ...field.Expr) IVslPromotionMansongDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v vslPromotionMansongDo) Join(table schema.Tabler, on ...field.Expr) IVslPromotionMansongDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v vslPromotionMansongDo) LeftJoin(table schema.Tabler, on ...field.Expr) IVslPromotionMansongDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v vslPromotionMansongDo) RightJoin(table schema.Tabler, on ...field.Expr) IVslPromotionMansongDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v vslPromotionMansongDo) Group(cols ...field.Expr) IVslPromotionMansongDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v vslPromotionMansongDo) Having(conds ...gen.Condition) IVslPromotionMansongDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v vslPromotionMansongDo) Limit(limit int) IVslPromotionMansongDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v vslPromotionMansongDo) Offset(offset int) IVslPromotionMansongDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v vslPromotionMansongDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IVslPromotionMansongDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v vslPromotionMansongDo) Unscoped() IVslPromotionMansongDo {
	return v.withDO(v.DO.Unscoped())
}

func (v vslPromotionMansongDo) Create(values ...*fxshop.VslPromotionMansong) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v vslPromotionMansongDo) CreateInBatches(values []*fxshop.VslPromotionMansong, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v vslPromotionMansongDo) Save(values ...*fxshop.VslPromotionMansong) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v vslPromotionMansongDo) First() (*fxshop.VslPromotionMansong, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslPromotionMansong), nil
	}
}

func (v vslPromotionMansongDo) Take() (*fxshop.VslPromotionMansong, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslPromotionMansong), nil
	}
}

func (v vslPromotionMansongDo) Last() (*fxshop.VslPromotionMansong, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslPromotionMansong), nil
	}
}

func (v vslPromotionMansongDo) Find() ([]*fxshop.VslPromotionMansong, error) {
	result, err := v.DO.Find()
	return result.([]*fxshop.VslPromotionMansong), err
}

func (v vslPromotionMansongDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.VslPromotionMansong, err error) {
	buf := make([]*fxshop.VslPromotionMansong, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v vslPromotionMansongDo) FindInBatches(result *[]*fxshop.VslPromotionMansong, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v vslPromotionMansongDo) Attrs(attrs ...field.AssignExpr) IVslPromotionMansongDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v vslPromotionMansongDo) Assign(attrs ...field.AssignExpr) IVslPromotionMansongDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v vslPromotionMansongDo) Joins(fields ...field.RelationField) IVslPromotionMansongDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v vslPromotionMansongDo) Preload(fields ...field.RelationField) IVslPromotionMansongDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v vslPromotionMansongDo) FirstOrInit() (*fxshop.VslPromotionMansong, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslPromotionMansong), nil
	}
}

func (v vslPromotionMansongDo) FirstOrCreate() (*fxshop.VslPromotionMansong, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslPromotionMansong), nil
	}
}

func (v vslPromotionMansongDo) FindByPage(offset int, limit int) (result []*fxshop.VslPromotionMansong, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v vslPromotionMansongDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v vslPromotionMansongDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v vslPromotionMansongDo) Delete(models ...*fxshop.VslPromotionMansong) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *vslPromotionMansongDo) withDO(do gen.Dao) *vslPromotionMansongDo {
	v.DO = *do.(*gen.DO)
	return v
}
