// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"exam-api-sync-go/dao/model/fxshop"
)

func newVslOrderGoodsPromotionDetails(db *gorm.DB, opts ...gen.DOOption) vslOrderGoodsPromotionDetails {
	_vslOrderGoodsPromotionDetails := vslOrderGoodsPromotionDetails{}

	_vslOrderGoodsPromotionDetails.vslOrderGoodsPromotionDetailsDo.UseDB(db, opts...)
	_vslOrderGoodsPromotionDetails.vslOrderGoodsPromotionDetailsDo.UseModel(&fxshop.VslOrderGoodsPromotionDetails{})

	tableName := _vslOrderGoodsPromotionDetails.vslOrderGoodsPromotionDetailsDo.TableName()
	_vslOrderGoodsPromotionDetails.ALL = field.NewAsterisk(tableName)
	_vslOrderGoodsPromotionDetails.ID = field.NewInt(tableName, "id")
	_vslOrderGoodsPromotionDetails.OrderID = field.NewInt(tableName, "order_id")
	_vslOrderGoodsPromotionDetails.SkuID = field.NewInt(tableName, "sku_id")
	_vslOrderGoodsPromotionDetails.PromotionType = field.NewBytes(tableName, "promotion_type")
	_vslOrderGoodsPromotionDetails.PromotionID = field.NewInt(tableName, "promotion_id")
	_vslOrderGoodsPromotionDetails.DiscountMoney = field.NewFloat64(tableName, "discount_money")
	_vslOrderGoodsPromotionDetails.UsedTime = field.NewInt(tableName, "used_time")
	_vslOrderGoodsPromotionDetails.WebsiteID = field.NewInt(tableName, "website_id")

	_vslOrderGoodsPromotionDetails.fillFieldMap()

	return _vslOrderGoodsPromotionDetails
}

// vslOrderGoodsPromotionDetails 订单商品优惠详情
type vslOrderGoodsPromotionDetails struct {
	vslOrderGoodsPromotionDetailsDo

	ALL           field.Asterisk
	ID            field.Int
	OrderID       field.Int     // 订单ID
	SkuID         field.Int     // 商品skuid
	PromotionType field.Bytes   // 优惠类型规则ID（满减对应规则）
	PromotionID   field.Int     // 优惠ID
	DiscountMoney field.Float64 // 优惠的金额，单位：元，精确到小数点后两位
	UsedTime      field.Int     // 使用时间
	WebsiteID     field.Int     // 实例信息

	fieldMap map[string]field.Expr
}

func (v vslOrderGoodsPromotionDetails) Table(newTableName string) *vslOrderGoodsPromotionDetails {
	v.vslOrderGoodsPromotionDetailsDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v vslOrderGoodsPromotionDetails) As(alias string) *vslOrderGoodsPromotionDetails {
	v.vslOrderGoodsPromotionDetailsDo.DO = *(v.vslOrderGoodsPromotionDetailsDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *vslOrderGoodsPromotionDetails) updateTableName(table string) *vslOrderGoodsPromotionDetails {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewInt(table, "id")
	v.OrderID = field.NewInt(table, "order_id")
	v.SkuID = field.NewInt(table, "sku_id")
	v.PromotionType = field.NewBytes(table, "promotion_type")
	v.PromotionID = field.NewInt(table, "promotion_id")
	v.DiscountMoney = field.NewFloat64(table, "discount_money")
	v.UsedTime = field.NewInt(table, "used_time")
	v.WebsiteID = field.NewInt(table, "website_id")

	v.fillFieldMap()

	return v
}

func (v *vslOrderGoodsPromotionDetails) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *vslOrderGoodsPromotionDetails) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 8)
	v.fieldMap["id"] = v.ID
	v.fieldMap["order_id"] = v.OrderID
	v.fieldMap["sku_id"] = v.SkuID
	v.fieldMap["promotion_type"] = v.PromotionType
	v.fieldMap["promotion_id"] = v.PromotionID
	v.fieldMap["discount_money"] = v.DiscountMoney
	v.fieldMap["used_time"] = v.UsedTime
	v.fieldMap["website_id"] = v.WebsiteID
}

func (v vslOrderGoodsPromotionDetails) clone(db *gorm.DB) vslOrderGoodsPromotionDetails {
	v.vslOrderGoodsPromotionDetailsDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v vslOrderGoodsPromotionDetails) replaceDB(db *gorm.DB) vslOrderGoodsPromotionDetails {
	v.vslOrderGoodsPromotionDetailsDo.ReplaceDB(db)
	return v
}

type vslOrderGoodsPromotionDetailsDo struct{ gen.DO }

type IVslOrderGoodsPromotionDetailsDo interface {
	gen.SubQuery
	Debug() IVslOrderGoodsPromotionDetailsDo
	WithContext(ctx context.Context) IVslOrderGoodsPromotionDetailsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IVslOrderGoodsPromotionDetailsDo
	WriteDB() IVslOrderGoodsPromotionDetailsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IVslOrderGoodsPromotionDetailsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IVslOrderGoodsPromotionDetailsDo
	Not(conds ...gen.Condition) IVslOrderGoodsPromotionDetailsDo
	Or(conds ...gen.Condition) IVslOrderGoodsPromotionDetailsDo
	Select(conds ...field.Expr) IVslOrderGoodsPromotionDetailsDo
	Where(conds ...gen.Condition) IVslOrderGoodsPromotionDetailsDo
	Order(conds ...field.Expr) IVslOrderGoodsPromotionDetailsDo
	Distinct(cols ...field.Expr) IVslOrderGoodsPromotionDetailsDo
	Omit(cols ...field.Expr) IVslOrderGoodsPromotionDetailsDo
	Join(table schema.Tabler, on ...field.Expr) IVslOrderGoodsPromotionDetailsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IVslOrderGoodsPromotionDetailsDo
	RightJoin(table schema.Tabler, on ...field.Expr) IVslOrderGoodsPromotionDetailsDo
	Group(cols ...field.Expr) IVslOrderGoodsPromotionDetailsDo
	Having(conds ...gen.Condition) IVslOrderGoodsPromotionDetailsDo
	Limit(limit int) IVslOrderGoodsPromotionDetailsDo
	Offset(offset int) IVslOrderGoodsPromotionDetailsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IVslOrderGoodsPromotionDetailsDo
	Unscoped() IVslOrderGoodsPromotionDetailsDo
	Create(values ...*fxshop.VslOrderGoodsPromotionDetails) error
	CreateInBatches(values []*fxshop.VslOrderGoodsPromotionDetails, batchSize int) error
	Save(values ...*fxshop.VslOrderGoodsPromotionDetails) error
	First() (*fxshop.VslOrderGoodsPromotionDetails, error)
	Take() (*fxshop.VslOrderGoodsPromotionDetails, error)
	Last() (*fxshop.VslOrderGoodsPromotionDetails, error)
	Find() ([]*fxshop.VslOrderGoodsPromotionDetails, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.VslOrderGoodsPromotionDetails, err error)
	FindInBatches(result *[]*fxshop.VslOrderGoodsPromotionDetails, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*fxshop.VslOrderGoodsPromotionDetails) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IVslOrderGoodsPromotionDetailsDo
	Assign(attrs ...field.AssignExpr) IVslOrderGoodsPromotionDetailsDo
	Joins(fields ...field.RelationField) IVslOrderGoodsPromotionDetailsDo
	Preload(fields ...field.RelationField) IVslOrderGoodsPromotionDetailsDo
	FirstOrInit() (*fxshop.VslOrderGoodsPromotionDetails, error)
	FirstOrCreate() (*fxshop.VslOrderGoodsPromotionDetails, error)
	FindByPage(offset int, limit int) (result []*fxshop.VslOrderGoodsPromotionDetails, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IVslOrderGoodsPromotionDetailsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (v vslOrderGoodsPromotionDetailsDo) Debug() IVslOrderGoodsPromotionDetailsDo {
	return v.withDO(v.DO.Debug())
}

func (v vslOrderGoodsPromotionDetailsDo) WithContext(ctx context.Context) IVslOrderGoodsPromotionDetailsDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v vslOrderGoodsPromotionDetailsDo) ReadDB() IVslOrderGoodsPromotionDetailsDo {
	return v.Clauses(dbresolver.Read)
}

func (v vslOrderGoodsPromotionDetailsDo) WriteDB() IVslOrderGoodsPromotionDetailsDo {
	return v.Clauses(dbresolver.Write)
}

func (v vslOrderGoodsPromotionDetailsDo) Session(config *gorm.Session) IVslOrderGoodsPromotionDetailsDo {
	return v.withDO(v.DO.Session(config))
}

func (v vslOrderGoodsPromotionDetailsDo) Clauses(conds ...clause.Expression) IVslOrderGoodsPromotionDetailsDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v vslOrderGoodsPromotionDetailsDo) Returning(value interface{}, columns ...string) IVslOrderGoodsPromotionDetailsDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v vslOrderGoodsPromotionDetailsDo) Not(conds ...gen.Condition) IVslOrderGoodsPromotionDetailsDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v vslOrderGoodsPromotionDetailsDo) Or(conds ...gen.Condition) IVslOrderGoodsPromotionDetailsDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v vslOrderGoodsPromotionDetailsDo) Select(conds ...field.Expr) IVslOrderGoodsPromotionDetailsDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v vslOrderGoodsPromotionDetailsDo) Where(conds ...gen.Condition) IVslOrderGoodsPromotionDetailsDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v vslOrderGoodsPromotionDetailsDo) Order(conds ...field.Expr) IVslOrderGoodsPromotionDetailsDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v vslOrderGoodsPromotionDetailsDo) Distinct(cols ...field.Expr) IVslOrderGoodsPromotionDetailsDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v vslOrderGoodsPromotionDetailsDo) Omit(cols ...field.Expr) IVslOrderGoodsPromotionDetailsDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v vslOrderGoodsPromotionDetailsDo) Join(table schema.Tabler, on ...field.Expr) IVslOrderGoodsPromotionDetailsDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v vslOrderGoodsPromotionDetailsDo) LeftJoin(table schema.Tabler, on ...field.Expr) IVslOrderGoodsPromotionDetailsDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v vslOrderGoodsPromotionDetailsDo) RightJoin(table schema.Tabler, on ...field.Expr) IVslOrderGoodsPromotionDetailsDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v vslOrderGoodsPromotionDetailsDo) Group(cols ...field.Expr) IVslOrderGoodsPromotionDetailsDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v vslOrderGoodsPromotionDetailsDo) Having(conds ...gen.Condition) IVslOrderGoodsPromotionDetailsDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v vslOrderGoodsPromotionDetailsDo) Limit(limit int) IVslOrderGoodsPromotionDetailsDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v vslOrderGoodsPromotionDetailsDo) Offset(offset int) IVslOrderGoodsPromotionDetailsDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v vslOrderGoodsPromotionDetailsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IVslOrderGoodsPromotionDetailsDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v vslOrderGoodsPromotionDetailsDo) Unscoped() IVslOrderGoodsPromotionDetailsDo {
	return v.withDO(v.DO.Unscoped())
}

func (v vslOrderGoodsPromotionDetailsDo) Create(values ...*fxshop.VslOrderGoodsPromotionDetails) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v vslOrderGoodsPromotionDetailsDo) CreateInBatches(values []*fxshop.VslOrderGoodsPromotionDetails, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v vslOrderGoodsPromotionDetailsDo) Save(values ...*fxshop.VslOrderGoodsPromotionDetails) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v vslOrderGoodsPromotionDetailsDo) First() (*fxshop.VslOrderGoodsPromotionDetails, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslOrderGoodsPromotionDetails), nil
	}
}

func (v vslOrderGoodsPromotionDetailsDo) Take() (*fxshop.VslOrderGoodsPromotionDetails, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslOrderGoodsPromotionDetails), nil
	}
}

func (v vslOrderGoodsPromotionDetailsDo) Last() (*fxshop.VslOrderGoodsPromotionDetails, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslOrderGoodsPromotionDetails), nil
	}
}

func (v vslOrderGoodsPromotionDetailsDo) Find() ([]*fxshop.VslOrderGoodsPromotionDetails, error) {
	result, err := v.DO.Find()
	return result.([]*fxshop.VslOrderGoodsPromotionDetails), err
}

func (v vslOrderGoodsPromotionDetailsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.VslOrderGoodsPromotionDetails, err error) {
	buf := make([]*fxshop.VslOrderGoodsPromotionDetails, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v vslOrderGoodsPromotionDetailsDo) FindInBatches(result *[]*fxshop.VslOrderGoodsPromotionDetails, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v vslOrderGoodsPromotionDetailsDo) Attrs(attrs ...field.AssignExpr) IVslOrderGoodsPromotionDetailsDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v vslOrderGoodsPromotionDetailsDo) Assign(attrs ...field.AssignExpr) IVslOrderGoodsPromotionDetailsDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v vslOrderGoodsPromotionDetailsDo) Joins(fields ...field.RelationField) IVslOrderGoodsPromotionDetailsDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v vslOrderGoodsPromotionDetailsDo) Preload(fields ...field.RelationField) IVslOrderGoodsPromotionDetailsDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v vslOrderGoodsPromotionDetailsDo) FirstOrInit() (*fxshop.VslOrderGoodsPromotionDetails, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslOrderGoodsPromotionDetails), nil
	}
}

func (v vslOrderGoodsPromotionDetailsDo) FirstOrCreate() (*fxshop.VslOrderGoodsPromotionDetails, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslOrderGoodsPromotionDetails), nil
	}
}

func (v vslOrderGoodsPromotionDetailsDo) FindByPage(offset int, limit int) (result []*fxshop.VslOrderGoodsPromotionDetails, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v vslOrderGoodsPromotionDetailsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v vslOrderGoodsPromotionDetailsDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v vslOrderGoodsPromotionDetailsDo) Delete(models ...*fxshop.VslOrderGoodsPromotionDetails) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *vslOrderGoodsPromotionDetailsDo) withDO(do gen.Dao) *vslOrderGoodsPromotionDetailsDo {
	v.DO = *do.(*gen.DO)
	return v
}
