// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"exam-api-sync-go/dao/model/fxshop"
)

func newVslDistributorRefereeLog(db *gorm.DB, opts ...gen.DOOption) vslDistributorRefereeLog {
	_vslDistributorRefereeLog := vslDistributorRefereeLog{}

	_vslDistributorRefereeLog.vslDistributorRefereeLogDo.UseDB(db, opts...)
	_vslDistributorRefereeLog.vslDistributorRefereeLogDo.UseModel(&fxshop.VslDistributorRefereeLog{})

	tableName := _vslDistributorRefereeLog.vslDistributorRefereeLogDo.TableName()
	_vslDistributorRefereeLog.ALL = field.NewAsterisk(tableName)
	_vslDistributorRefereeLog.ID = field.NewInt(tableName, "id")
	_vslDistributorRefereeLog.UID = field.NewInt(tableName, "uid")
	_vslDistributorRefereeLog.RefereeID = field.NewInt(tableName, "referee_id")
	_vslDistributorRefereeLog.WebsiteID = field.NewInt(tableName, "website_id")
	_vslDistributorRefereeLog.ShopID = field.NewInt(tableName, "shop_id")
	_vslDistributorRefereeLog.AddTime = field.NewInt(tableName, "add_time")
	_vslDistributorRefereeLog.RefereeId2 = field.NewString(tableName, "referee_id2")
	_vslDistributorRefereeLog.RefereeId3 = field.NewString(tableName, "referee_id3")

	_vslDistributorRefereeLog.fillFieldMap()

	return _vslDistributorRefereeLog
}

type vslDistributorRefereeLog struct {
	vslDistributorRefereeLogDo

	ALL        field.Asterisk
	ID         field.Int
	UID        field.Int // 会员id
	RefereeID  field.Int // 推荐人id
	WebsiteID  field.Int
	ShopID     field.Int
	AddTime    field.Int    // 绑定时间
	RefereeId2 field.String // 1,2推荐人id
	RefereeId3 field.String // 1,2,3推荐人id

	fieldMap map[string]field.Expr
}

func (v vslDistributorRefereeLog) Table(newTableName string) *vslDistributorRefereeLog {
	v.vslDistributorRefereeLogDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v vslDistributorRefereeLog) As(alias string) *vslDistributorRefereeLog {
	v.vslDistributorRefereeLogDo.DO = *(v.vslDistributorRefereeLogDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *vslDistributorRefereeLog) updateTableName(table string) *vslDistributorRefereeLog {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewInt(table, "id")
	v.UID = field.NewInt(table, "uid")
	v.RefereeID = field.NewInt(table, "referee_id")
	v.WebsiteID = field.NewInt(table, "website_id")
	v.ShopID = field.NewInt(table, "shop_id")
	v.AddTime = field.NewInt(table, "add_time")
	v.RefereeId2 = field.NewString(table, "referee_id2")
	v.RefereeId3 = field.NewString(table, "referee_id3")

	v.fillFieldMap()

	return v
}

func (v *vslDistributorRefereeLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *vslDistributorRefereeLog) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 8)
	v.fieldMap["id"] = v.ID
	v.fieldMap["uid"] = v.UID
	v.fieldMap["referee_id"] = v.RefereeID
	v.fieldMap["website_id"] = v.WebsiteID
	v.fieldMap["shop_id"] = v.ShopID
	v.fieldMap["add_time"] = v.AddTime
	v.fieldMap["referee_id2"] = v.RefereeId2
	v.fieldMap["referee_id3"] = v.RefereeId3
}

func (v vslDistributorRefereeLog) clone(db *gorm.DB) vslDistributorRefereeLog {
	v.vslDistributorRefereeLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v vslDistributorRefereeLog) replaceDB(db *gorm.DB) vslDistributorRefereeLog {
	v.vslDistributorRefereeLogDo.ReplaceDB(db)
	return v
}

type vslDistributorRefereeLogDo struct{ gen.DO }

type IVslDistributorRefereeLogDo interface {
	gen.SubQuery
	Debug() IVslDistributorRefereeLogDo
	WithContext(ctx context.Context) IVslDistributorRefereeLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IVslDistributorRefereeLogDo
	WriteDB() IVslDistributorRefereeLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IVslDistributorRefereeLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IVslDistributorRefereeLogDo
	Not(conds ...gen.Condition) IVslDistributorRefereeLogDo
	Or(conds ...gen.Condition) IVslDistributorRefereeLogDo
	Select(conds ...field.Expr) IVslDistributorRefereeLogDo
	Where(conds ...gen.Condition) IVslDistributorRefereeLogDo
	Order(conds ...field.Expr) IVslDistributorRefereeLogDo
	Distinct(cols ...field.Expr) IVslDistributorRefereeLogDo
	Omit(cols ...field.Expr) IVslDistributorRefereeLogDo
	Join(table schema.Tabler, on ...field.Expr) IVslDistributorRefereeLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IVslDistributorRefereeLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IVslDistributorRefereeLogDo
	Group(cols ...field.Expr) IVslDistributorRefereeLogDo
	Having(conds ...gen.Condition) IVslDistributorRefereeLogDo
	Limit(limit int) IVslDistributorRefereeLogDo
	Offset(offset int) IVslDistributorRefereeLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IVslDistributorRefereeLogDo
	Unscoped() IVslDistributorRefereeLogDo
	Create(values ...*fxshop.VslDistributorRefereeLog) error
	CreateInBatches(values []*fxshop.VslDistributorRefereeLog, batchSize int) error
	Save(values ...*fxshop.VslDistributorRefereeLog) error
	First() (*fxshop.VslDistributorRefereeLog, error)
	Take() (*fxshop.VslDistributorRefereeLog, error)
	Last() (*fxshop.VslDistributorRefereeLog, error)
	Find() ([]*fxshop.VslDistributorRefereeLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.VslDistributorRefereeLog, err error)
	FindInBatches(result *[]*fxshop.VslDistributorRefereeLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*fxshop.VslDistributorRefereeLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IVslDistributorRefereeLogDo
	Assign(attrs ...field.AssignExpr) IVslDistributorRefereeLogDo
	Joins(fields ...field.RelationField) IVslDistributorRefereeLogDo
	Preload(fields ...field.RelationField) IVslDistributorRefereeLogDo
	FirstOrInit() (*fxshop.VslDistributorRefereeLog, error)
	FirstOrCreate() (*fxshop.VslDistributorRefereeLog, error)
	FindByPage(offset int, limit int) (result []*fxshop.VslDistributorRefereeLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IVslDistributorRefereeLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (v vslDistributorRefereeLogDo) Debug() IVslDistributorRefereeLogDo {
	return v.withDO(v.DO.Debug())
}

func (v vslDistributorRefereeLogDo) WithContext(ctx context.Context) IVslDistributorRefereeLogDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v vslDistributorRefereeLogDo) ReadDB() IVslDistributorRefereeLogDo {
	return v.Clauses(dbresolver.Read)
}

func (v vslDistributorRefereeLogDo) WriteDB() IVslDistributorRefereeLogDo {
	return v.Clauses(dbresolver.Write)
}

func (v vslDistributorRefereeLogDo) Session(config *gorm.Session) IVslDistributorRefereeLogDo {
	return v.withDO(v.DO.Session(config))
}

func (v vslDistributorRefereeLogDo) Clauses(conds ...clause.Expression) IVslDistributorRefereeLogDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v vslDistributorRefereeLogDo) Returning(value interface{}, columns ...string) IVslDistributorRefereeLogDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v vslDistributorRefereeLogDo) Not(conds ...gen.Condition) IVslDistributorRefereeLogDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v vslDistributorRefereeLogDo) Or(conds ...gen.Condition) IVslDistributorRefereeLogDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v vslDistributorRefereeLogDo) Select(conds ...field.Expr) IVslDistributorRefereeLogDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v vslDistributorRefereeLogDo) Where(conds ...gen.Condition) IVslDistributorRefereeLogDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v vslDistributorRefereeLogDo) Order(conds ...field.Expr) IVslDistributorRefereeLogDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v vslDistributorRefereeLogDo) Distinct(cols ...field.Expr) IVslDistributorRefereeLogDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v vslDistributorRefereeLogDo) Omit(cols ...field.Expr) IVslDistributorRefereeLogDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v vslDistributorRefereeLogDo) Join(table schema.Tabler, on ...field.Expr) IVslDistributorRefereeLogDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v vslDistributorRefereeLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IVslDistributorRefereeLogDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v vslDistributorRefereeLogDo) RightJoin(table schema.Tabler, on ...field.Expr) IVslDistributorRefereeLogDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v vslDistributorRefereeLogDo) Group(cols ...field.Expr) IVslDistributorRefereeLogDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v vslDistributorRefereeLogDo) Having(conds ...gen.Condition) IVslDistributorRefereeLogDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v vslDistributorRefereeLogDo) Limit(limit int) IVslDistributorRefereeLogDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v vslDistributorRefereeLogDo) Offset(offset int) IVslDistributorRefereeLogDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v vslDistributorRefereeLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IVslDistributorRefereeLogDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v vslDistributorRefereeLogDo) Unscoped() IVslDistributorRefereeLogDo {
	return v.withDO(v.DO.Unscoped())
}

func (v vslDistributorRefereeLogDo) Create(values ...*fxshop.VslDistributorRefereeLog) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v vslDistributorRefereeLogDo) CreateInBatches(values []*fxshop.VslDistributorRefereeLog, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v vslDistributorRefereeLogDo) Save(values ...*fxshop.VslDistributorRefereeLog) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v vslDistributorRefereeLogDo) First() (*fxshop.VslDistributorRefereeLog, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslDistributorRefereeLog), nil
	}
}

func (v vslDistributorRefereeLogDo) Take() (*fxshop.VslDistributorRefereeLog, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslDistributorRefereeLog), nil
	}
}

func (v vslDistributorRefereeLogDo) Last() (*fxshop.VslDistributorRefereeLog, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslDistributorRefereeLog), nil
	}
}

func (v vslDistributorRefereeLogDo) Find() ([]*fxshop.VslDistributorRefereeLog, error) {
	result, err := v.DO.Find()
	return result.([]*fxshop.VslDistributorRefereeLog), err
}

func (v vslDistributorRefereeLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.VslDistributorRefereeLog, err error) {
	buf := make([]*fxshop.VslDistributorRefereeLog, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v vslDistributorRefereeLogDo) FindInBatches(result *[]*fxshop.VslDistributorRefereeLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v vslDistributorRefereeLogDo) Attrs(attrs ...field.AssignExpr) IVslDistributorRefereeLogDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v vslDistributorRefereeLogDo) Assign(attrs ...field.AssignExpr) IVslDistributorRefereeLogDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v vslDistributorRefereeLogDo) Joins(fields ...field.RelationField) IVslDistributorRefereeLogDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v vslDistributorRefereeLogDo) Preload(fields ...field.RelationField) IVslDistributorRefereeLogDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v vslDistributorRefereeLogDo) FirstOrInit() (*fxshop.VslDistributorRefereeLog, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslDistributorRefereeLog), nil
	}
}

func (v vslDistributorRefereeLogDo) FirstOrCreate() (*fxshop.VslDistributorRefereeLog, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslDistributorRefereeLog), nil
	}
}

func (v vslDistributorRefereeLogDo) FindByPage(offset int, limit int) (result []*fxshop.VslDistributorRefereeLog, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v vslDistributorRefereeLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v vslDistributorRefereeLogDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v vslDistributorRefereeLogDo) Delete(models ...*fxshop.VslDistributorRefereeLog) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *vslDistributorRefereeLogDo) withDO(do gen.Dao) *vslDistributorRefereeLogDo {
	v.DO = *do.(*gen.DO)
	return v
}
