// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"exam-api-sync-go/dao/model/fxshop"
)

func newVslGoodsSkuDeleted(db *gorm.DB, opts ...gen.DOOption) vslGoodsSkuDeleted {
	_vslGoodsSkuDeleted := vslGoodsSkuDeleted{}

	_vslGoodsSkuDeleted.vslGoodsSkuDeletedDo.UseDB(db, opts...)
	_vslGoodsSkuDeleted.vslGoodsSkuDeletedDo.UseModel(&fxshop.VslGoodsSkuDeleted{})

	tableName := _vslGoodsSkuDeleted.vslGoodsSkuDeletedDo.TableName()
	_vslGoodsSkuDeleted.ALL = field.NewAsterisk(tableName)
	_vslGoodsSkuDeleted.SkuID = field.NewInt(tableName, "sku_id")
	_vslGoodsSkuDeleted.GoodsID = field.NewInt(tableName, "goods_id")
	_vslGoodsSkuDeleted.SkuName = field.NewString(tableName, "sku_name")
	_vslGoodsSkuDeleted.AttrValueItems = field.NewString(tableName, "attr_value_items")
	_vslGoodsSkuDeleted.AttrValueItemsFormat = field.NewString(tableName, "attr_value_items_format")
	_vslGoodsSkuDeleted.MarketPrice = field.NewFloat64(tableName, "market_price")
	_vslGoodsSkuDeleted.Price = field.NewFloat64(tableName, "price")
	_vslGoodsSkuDeleted.PromotePrice = field.NewFloat64(tableName, "promote_price")
	_vslGoodsSkuDeleted.CostPrice = field.NewFloat64(tableName, "cost_price")
	_vslGoodsSkuDeleted.Stock = field.NewInt(tableName, "stock")
	_vslGoodsSkuDeleted.Picture = field.NewInt(tableName, "picture")
	_vslGoodsSkuDeleted.Code = field.NewString(tableName, "code")
	_vslGoodsSkuDeleted.QRcode = field.NewString(tableName, "QRcode")
	_vslGoodsSkuDeleted.CreateDate = field.NewInt(tableName, "create_date")
	_vslGoodsSkuDeleted.UpdateDate = field.NewInt(tableName, "update_date")
	_vslGoodsSkuDeleted.WebsiteID = field.NewInt(tableName, "website_id")
	_vslGoodsSkuDeleted.GjpSkuID = field.NewInt(tableName, "gjp_sku_id")
	_vslGoodsSkuDeleted.SkuMaxBuy = field.NewInt16(tableName, "sku_max_buy")
	_vslGoodsSkuDeleted.SkuMaxBuyTime = field.NewInt(tableName, "sku_max_buy_time")
	_vslGoodsSkuDeleted.SupplierSkuID = field.NewInt(tableName, "supplier_sku_id")

	_vslGoodsSkuDeleted.fillFieldMap()

	return _vslGoodsSkuDeleted
}

// vslGoodsSkuDeleted 商品skui规格价格库存信息回收站表
type vslGoodsSkuDeleted struct {
	vslGoodsSkuDeletedDo

	ALL                  field.Asterisk
	SkuID                field.Int     // 表序号
	GoodsID              field.Int     // 商品编号
	SkuName              field.String  // SKU名称
	AttrValueItems       field.String  // 属性和属性值 id串 attribute + attribute value 表ID分号分隔
	AttrValueItemsFormat field.String  // 属性和属性值id串组合json格式
	MarketPrice          field.Float64 // 市场价
	Price                field.Float64 // 价格
	PromotePrice         field.Float64 // 促销价格
	CostPrice            field.Float64 // 成本价
	Stock                field.Int     // 库存
	Picture              field.Int     // 如果是第一个sku编码, 可以加图片
	Code                 field.String  // 商家编码
	QRcode               field.String  // 商品二维码
	CreateDate           field.Int     // 创建时间
	UpdateDate           field.Int     // 修改时间
	WebsiteID            field.Int     // 实例信息
	GjpSkuID             field.Int     // 管家婆ERP定义的  对接了管家婆ERP才会有
	SkuMaxBuy            field.Int16   // 商品规格限购
	SkuMaxBuyTime        field.Int     // 商品规格限购设置的时间
	SupplierSkuID        field.Int     // 对应的供应商商品的sku_id

	fieldMap map[string]field.Expr
}

func (v vslGoodsSkuDeleted) Table(newTableName string) *vslGoodsSkuDeleted {
	v.vslGoodsSkuDeletedDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v vslGoodsSkuDeleted) As(alias string) *vslGoodsSkuDeleted {
	v.vslGoodsSkuDeletedDo.DO = *(v.vslGoodsSkuDeletedDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *vslGoodsSkuDeleted) updateTableName(table string) *vslGoodsSkuDeleted {
	v.ALL = field.NewAsterisk(table)
	v.SkuID = field.NewInt(table, "sku_id")
	v.GoodsID = field.NewInt(table, "goods_id")
	v.SkuName = field.NewString(table, "sku_name")
	v.AttrValueItems = field.NewString(table, "attr_value_items")
	v.AttrValueItemsFormat = field.NewString(table, "attr_value_items_format")
	v.MarketPrice = field.NewFloat64(table, "market_price")
	v.Price = field.NewFloat64(table, "price")
	v.PromotePrice = field.NewFloat64(table, "promote_price")
	v.CostPrice = field.NewFloat64(table, "cost_price")
	v.Stock = field.NewInt(table, "stock")
	v.Picture = field.NewInt(table, "picture")
	v.Code = field.NewString(table, "code")
	v.QRcode = field.NewString(table, "QRcode")
	v.CreateDate = field.NewInt(table, "create_date")
	v.UpdateDate = field.NewInt(table, "update_date")
	v.WebsiteID = field.NewInt(table, "website_id")
	v.GjpSkuID = field.NewInt(table, "gjp_sku_id")
	v.SkuMaxBuy = field.NewInt16(table, "sku_max_buy")
	v.SkuMaxBuyTime = field.NewInt(table, "sku_max_buy_time")
	v.SupplierSkuID = field.NewInt(table, "supplier_sku_id")

	v.fillFieldMap()

	return v
}

func (v *vslGoodsSkuDeleted) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *vslGoodsSkuDeleted) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 20)
	v.fieldMap["sku_id"] = v.SkuID
	v.fieldMap["goods_id"] = v.GoodsID
	v.fieldMap["sku_name"] = v.SkuName
	v.fieldMap["attr_value_items"] = v.AttrValueItems
	v.fieldMap["attr_value_items_format"] = v.AttrValueItemsFormat
	v.fieldMap["market_price"] = v.MarketPrice
	v.fieldMap["price"] = v.Price
	v.fieldMap["promote_price"] = v.PromotePrice
	v.fieldMap["cost_price"] = v.CostPrice
	v.fieldMap["stock"] = v.Stock
	v.fieldMap["picture"] = v.Picture
	v.fieldMap["code"] = v.Code
	v.fieldMap["QRcode"] = v.QRcode
	v.fieldMap["create_date"] = v.CreateDate
	v.fieldMap["update_date"] = v.UpdateDate
	v.fieldMap["website_id"] = v.WebsiteID
	v.fieldMap["gjp_sku_id"] = v.GjpSkuID
	v.fieldMap["sku_max_buy"] = v.SkuMaxBuy
	v.fieldMap["sku_max_buy_time"] = v.SkuMaxBuyTime
	v.fieldMap["supplier_sku_id"] = v.SupplierSkuID
}

func (v vslGoodsSkuDeleted) clone(db *gorm.DB) vslGoodsSkuDeleted {
	v.vslGoodsSkuDeletedDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v vslGoodsSkuDeleted) replaceDB(db *gorm.DB) vslGoodsSkuDeleted {
	v.vslGoodsSkuDeletedDo.ReplaceDB(db)
	return v
}

type vslGoodsSkuDeletedDo struct{ gen.DO }

type IVslGoodsSkuDeletedDo interface {
	gen.SubQuery
	Debug() IVslGoodsSkuDeletedDo
	WithContext(ctx context.Context) IVslGoodsSkuDeletedDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IVslGoodsSkuDeletedDo
	WriteDB() IVslGoodsSkuDeletedDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IVslGoodsSkuDeletedDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IVslGoodsSkuDeletedDo
	Not(conds ...gen.Condition) IVslGoodsSkuDeletedDo
	Or(conds ...gen.Condition) IVslGoodsSkuDeletedDo
	Select(conds ...field.Expr) IVslGoodsSkuDeletedDo
	Where(conds ...gen.Condition) IVslGoodsSkuDeletedDo
	Order(conds ...field.Expr) IVslGoodsSkuDeletedDo
	Distinct(cols ...field.Expr) IVslGoodsSkuDeletedDo
	Omit(cols ...field.Expr) IVslGoodsSkuDeletedDo
	Join(table schema.Tabler, on ...field.Expr) IVslGoodsSkuDeletedDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IVslGoodsSkuDeletedDo
	RightJoin(table schema.Tabler, on ...field.Expr) IVslGoodsSkuDeletedDo
	Group(cols ...field.Expr) IVslGoodsSkuDeletedDo
	Having(conds ...gen.Condition) IVslGoodsSkuDeletedDo
	Limit(limit int) IVslGoodsSkuDeletedDo
	Offset(offset int) IVslGoodsSkuDeletedDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IVslGoodsSkuDeletedDo
	Unscoped() IVslGoodsSkuDeletedDo
	Create(values ...*fxshop.VslGoodsSkuDeleted) error
	CreateInBatches(values []*fxshop.VslGoodsSkuDeleted, batchSize int) error
	Save(values ...*fxshop.VslGoodsSkuDeleted) error
	First() (*fxshop.VslGoodsSkuDeleted, error)
	Take() (*fxshop.VslGoodsSkuDeleted, error)
	Last() (*fxshop.VslGoodsSkuDeleted, error)
	Find() ([]*fxshop.VslGoodsSkuDeleted, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.VslGoodsSkuDeleted, err error)
	FindInBatches(result *[]*fxshop.VslGoodsSkuDeleted, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*fxshop.VslGoodsSkuDeleted) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IVslGoodsSkuDeletedDo
	Assign(attrs ...field.AssignExpr) IVslGoodsSkuDeletedDo
	Joins(fields ...field.RelationField) IVslGoodsSkuDeletedDo
	Preload(fields ...field.RelationField) IVslGoodsSkuDeletedDo
	FirstOrInit() (*fxshop.VslGoodsSkuDeleted, error)
	FirstOrCreate() (*fxshop.VslGoodsSkuDeleted, error)
	FindByPage(offset int, limit int) (result []*fxshop.VslGoodsSkuDeleted, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IVslGoodsSkuDeletedDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (v vslGoodsSkuDeletedDo) Debug() IVslGoodsSkuDeletedDo {
	return v.withDO(v.DO.Debug())
}

func (v vslGoodsSkuDeletedDo) WithContext(ctx context.Context) IVslGoodsSkuDeletedDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v vslGoodsSkuDeletedDo) ReadDB() IVslGoodsSkuDeletedDo {
	return v.Clauses(dbresolver.Read)
}

func (v vslGoodsSkuDeletedDo) WriteDB() IVslGoodsSkuDeletedDo {
	return v.Clauses(dbresolver.Write)
}

func (v vslGoodsSkuDeletedDo) Session(config *gorm.Session) IVslGoodsSkuDeletedDo {
	return v.withDO(v.DO.Session(config))
}

func (v vslGoodsSkuDeletedDo) Clauses(conds ...clause.Expression) IVslGoodsSkuDeletedDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v vslGoodsSkuDeletedDo) Returning(value interface{}, columns ...string) IVslGoodsSkuDeletedDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v vslGoodsSkuDeletedDo) Not(conds ...gen.Condition) IVslGoodsSkuDeletedDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v vslGoodsSkuDeletedDo) Or(conds ...gen.Condition) IVslGoodsSkuDeletedDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v vslGoodsSkuDeletedDo) Select(conds ...field.Expr) IVslGoodsSkuDeletedDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v vslGoodsSkuDeletedDo) Where(conds ...gen.Condition) IVslGoodsSkuDeletedDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v vslGoodsSkuDeletedDo) Order(conds ...field.Expr) IVslGoodsSkuDeletedDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v vslGoodsSkuDeletedDo) Distinct(cols ...field.Expr) IVslGoodsSkuDeletedDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v vslGoodsSkuDeletedDo) Omit(cols ...field.Expr) IVslGoodsSkuDeletedDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v vslGoodsSkuDeletedDo) Join(table schema.Tabler, on ...field.Expr) IVslGoodsSkuDeletedDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v vslGoodsSkuDeletedDo) LeftJoin(table schema.Tabler, on ...field.Expr) IVslGoodsSkuDeletedDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v vslGoodsSkuDeletedDo) RightJoin(table schema.Tabler, on ...field.Expr) IVslGoodsSkuDeletedDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v vslGoodsSkuDeletedDo) Group(cols ...field.Expr) IVslGoodsSkuDeletedDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v vslGoodsSkuDeletedDo) Having(conds ...gen.Condition) IVslGoodsSkuDeletedDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v vslGoodsSkuDeletedDo) Limit(limit int) IVslGoodsSkuDeletedDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v vslGoodsSkuDeletedDo) Offset(offset int) IVslGoodsSkuDeletedDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v vslGoodsSkuDeletedDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IVslGoodsSkuDeletedDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v vslGoodsSkuDeletedDo) Unscoped() IVslGoodsSkuDeletedDo {
	return v.withDO(v.DO.Unscoped())
}

func (v vslGoodsSkuDeletedDo) Create(values ...*fxshop.VslGoodsSkuDeleted) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v vslGoodsSkuDeletedDo) CreateInBatches(values []*fxshop.VslGoodsSkuDeleted, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v vslGoodsSkuDeletedDo) Save(values ...*fxshop.VslGoodsSkuDeleted) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v vslGoodsSkuDeletedDo) First() (*fxshop.VslGoodsSkuDeleted, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslGoodsSkuDeleted), nil
	}
}

func (v vslGoodsSkuDeletedDo) Take() (*fxshop.VslGoodsSkuDeleted, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslGoodsSkuDeleted), nil
	}
}

func (v vslGoodsSkuDeletedDo) Last() (*fxshop.VslGoodsSkuDeleted, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslGoodsSkuDeleted), nil
	}
}

func (v vslGoodsSkuDeletedDo) Find() ([]*fxshop.VslGoodsSkuDeleted, error) {
	result, err := v.DO.Find()
	return result.([]*fxshop.VslGoodsSkuDeleted), err
}

func (v vslGoodsSkuDeletedDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.VslGoodsSkuDeleted, err error) {
	buf := make([]*fxshop.VslGoodsSkuDeleted, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v vslGoodsSkuDeletedDo) FindInBatches(result *[]*fxshop.VslGoodsSkuDeleted, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v vslGoodsSkuDeletedDo) Attrs(attrs ...field.AssignExpr) IVslGoodsSkuDeletedDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v vslGoodsSkuDeletedDo) Assign(attrs ...field.AssignExpr) IVslGoodsSkuDeletedDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v vslGoodsSkuDeletedDo) Joins(fields ...field.RelationField) IVslGoodsSkuDeletedDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v vslGoodsSkuDeletedDo) Preload(fields ...field.RelationField) IVslGoodsSkuDeletedDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v vslGoodsSkuDeletedDo) FirstOrInit() (*fxshop.VslGoodsSkuDeleted, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslGoodsSkuDeleted), nil
	}
}

func (v vslGoodsSkuDeletedDo) FirstOrCreate() (*fxshop.VslGoodsSkuDeleted, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslGoodsSkuDeleted), nil
	}
}

func (v vslGoodsSkuDeletedDo) FindByPage(offset int, limit int) (result []*fxshop.VslGoodsSkuDeleted, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v vslGoodsSkuDeletedDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v vslGoodsSkuDeletedDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v vslGoodsSkuDeletedDo) Delete(models ...*fxshop.VslGoodsSkuDeleted) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *vslGoodsSkuDeletedDo) withDO(do gen.Dao) *vslGoodsSkuDeletedDo {
	v.DO = *do.(*gen.DO)
	return v
}
