// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"exam-api-sync-go/dao/model/fxshop"
)

func newVslElectroncardBase(db *gorm.DB, opts ...gen.DOOption) vslElectroncardBase {
	_vslElectroncardBase := vslElectroncardBase{}

	_vslElectroncardBase.vslElectroncardBaseDo.UseDB(db, opts...)
	_vslElectroncardBase.vslElectroncardBaseDo.UseModel(&fxshop.VslElectroncardBase{})

	tableName := _vslElectroncardBase.vslElectroncardBaseDo.TableName()
	_vslElectroncardBase.ALL = field.NewAsterisk(tableName)
	_vslElectroncardBase.ID = field.NewInt(tableName, "id")
	_vslElectroncardBase.ElectroncardBaseName = field.NewString(tableName, "electroncard_base_name")
	_vslElectroncardBase.ElectroncardBaseCategoryID = field.NewInt(tableName, "electroncard_base_category_id")
	_vslElectroncardBase.Memo = field.NewString(tableName, "memo")
	_vslElectroncardBase.Description = field.NewString(tableName, "description")
	_vslElectroncardBase.IsDataDifferent = field.NewInt8(tableName, "is_data_different")
	_vslElectroncardBase.KeyName = field.NewString(tableName, "key_name")
	_vslElectroncardBase.ShopID = field.NewInt(tableName, "shop_id")
	_vslElectroncardBase.WebsiteID = field.NewInt(tableName, "website_id")
	_vslElectroncardBase.CreateTime = field.NewInt(tableName, "create_time")

	_vslElectroncardBase.fillFieldMap()

	return _vslElectroncardBase
}

type vslElectroncardBase struct {
	vslElectroncardBaseDo

	ALL                        field.Asterisk
	ID                         field.Int
	ElectroncardBaseName       field.String // 卡密库名称
	ElectroncardBaseCategoryID field.Int    // 卡密库分类id
	Memo                       field.String // 备注
	Description                field.String // 使用说明
	IsDataDifferent            field.Int8   // 数据去重   0:关闭  1:开启
	KeyName                    field.String // 字段名，多个字段名用，分隔
	ShopID                     field.Int    // 店铺id
	WebsiteID                  field.Int
	CreateTime                 field.Int // 添加时间

	fieldMap map[string]field.Expr
}

func (v vslElectroncardBase) Table(newTableName string) *vslElectroncardBase {
	v.vslElectroncardBaseDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v vslElectroncardBase) As(alias string) *vslElectroncardBase {
	v.vslElectroncardBaseDo.DO = *(v.vslElectroncardBaseDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *vslElectroncardBase) updateTableName(table string) *vslElectroncardBase {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewInt(table, "id")
	v.ElectroncardBaseName = field.NewString(table, "electroncard_base_name")
	v.ElectroncardBaseCategoryID = field.NewInt(table, "electroncard_base_category_id")
	v.Memo = field.NewString(table, "memo")
	v.Description = field.NewString(table, "description")
	v.IsDataDifferent = field.NewInt8(table, "is_data_different")
	v.KeyName = field.NewString(table, "key_name")
	v.ShopID = field.NewInt(table, "shop_id")
	v.WebsiteID = field.NewInt(table, "website_id")
	v.CreateTime = field.NewInt(table, "create_time")

	v.fillFieldMap()

	return v
}

func (v *vslElectroncardBase) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *vslElectroncardBase) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 10)
	v.fieldMap["id"] = v.ID
	v.fieldMap["electroncard_base_name"] = v.ElectroncardBaseName
	v.fieldMap["electroncard_base_category_id"] = v.ElectroncardBaseCategoryID
	v.fieldMap["memo"] = v.Memo
	v.fieldMap["description"] = v.Description
	v.fieldMap["is_data_different"] = v.IsDataDifferent
	v.fieldMap["key_name"] = v.KeyName
	v.fieldMap["shop_id"] = v.ShopID
	v.fieldMap["website_id"] = v.WebsiteID
	v.fieldMap["create_time"] = v.CreateTime
}

func (v vslElectroncardBase) clone(db *gorm.DB) vslElectroncardBase {
	v.vslElectroncardBaseDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v vslElectroncardBase) replaceDB(db *gorm.DB) vslElectroncardBase {
	v.vslElectroncardBaseDo.ReplaceDB(db)
	return v
}

type vslElectroncardBaseDo struct{ gen.DO }

type IVslElectroncardBaseDo interface {
	gen.SubQuery
	Debug() IVslElectroncardBaseDo
	WithContext(ctx context.Context) IVslElectroncardBaseDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IVslElectroncardBaseDo
	WriteDB() IVslElectroncardBaseDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IVslElectroncardBaseDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IVslElectroncardBaseDo
	Not(conds ...gen.Condition) IVslElectroncardBaseDo
	Or(conds ...gen.Condition) IVslElectroncardBaseDo
	Select(conds ...field.Expr) IVslElectroncardBaseDo
	Where(conds ...gen.Condition) IVslElectroncardBaseDo
	Order(conds ...field.Expr) IVslElectroncardBaseDo
	Distinct(cols ...field.Expr) IVslElectroncardBaseDo
	Omit(cols ...field.Expr) IVslElectroncardBaseDo
	Join(table schema.Tabler, on ...field.Expr) IVslElectroncardBaseDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IVslElectroncardBaseDo
	RightJoin(table schema.Tabler, on ...field.Expr) IVslElectroncardBaseDo
	Group(cols ...field.Expr) IVslElectroncardBaseDo
	Having(conds ...gen.Condition) IVslElectroncardBaseDo
	Limit(limit int) IVslElectroncardBaseDo
	Offset(offset int) IVslElectroncardBaseDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IVslElectroncardBaseDo
	Unscoped() IVslElectroncardBaseDo
	Create(values ...*fxshop.VslElectroncardBase) error
	CreateInBatches(values []*fxshop.VslElectroncardBase, batchSize int) error
	Save(values ...*fxshop.VslElectroncardBase) error
	First() (*fxshop.VslElectroncardBase, error)
	Take() (*fxshop.VslElectroncardBase, error)
	Last() (*fxshop.VslElectroncardBase, error)
	Find() ([]*fxshop.VslElectroncardBase, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.VslElectroncardBase, err error)
	FindInBatches(result *[]*fxshop.VslElectroncardBase, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*fxshop.VslElectroncardBase) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IVslElectroncardBaseDo
	Assign(attrs ...field.AssignExpr) IVslElectroncardBaseDo
	Joins(fields ...field.RelationField) IVslElectroncardBaseDo
	Preload(fields ...field.RelationField) IVslElectroncardBaseDo
	FirstOrInit() (*fxshop.VslElectroncardBase, error)
	FirstOrCreate() (*fxshop.VslElectroncardBase, error)
	FindByPage(offset int, limit int) (result []*fxshop.VslElectroncardBase, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IVslElectroncardBaseDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (v vslElectroncardBaseDo) Debug() IVslElectroncardBaseDo {
	return v.withDO(v.DO.Debug())
}

func (v vslElectroncardBaseDo) WithContext(ctx context.Context) IVslElectroncardBaseDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v vslElectroncardBaseDo) ReadDB() IVslElectroncardBaseDo {
	return v.Clauses(dbresolver.Read)
}

func (v vslElectroncardBaseDo) WriteDB() IVslElectroncardBaseDo {
	return v.Clauses(dbresolver.Write)
}

func (v vslElectroncardBaseDo) Session(config *gorm.Session) IVslElectroncardBaseDo {
	return v.withDO(v.DO.Session(config))
}

func (v vslElectroncardBaseDo) Clauses(conds ...clause.Expression) IVslElectroncardBaseDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v vslElectroncardBaseDo) Returning(value interface{}, columns ...string) IVslElectroncardBaseDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v vslElectroncardBaseDo) Not(conds ...gen.Condition) IVslElectroncardBaseDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v vslElectroncardBaseDo) Or(conds ...gen.Condition) IVslElectroncardBaseDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v vslElectroncardBaseDo) Select(conds ...field.Expr) IVslElectroncardBaseDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v vslElectroncardBaseDo) Where(conds ...gen.Condition) IVslElectroncardBaseDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v vslElectroncardBaseDo) Order(conds ...field.Expr) IVslElectroncardBaseDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v vslElectroncardBaseDo) Distinct(cols ...field.Expr) IVslElectroncardBaseDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v vslElectroncardBaseDo) Omit(cols ...field.Expr) IVslElectroncardBaseDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v vslElectroncardBaseDo) Join(table schema.Tabler, on ...field.Expr) IVslElectroncardBaseDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v vslElectroncardBaseDo) LeftJoin(table schema.Tabler, on ...field.Expr) IVslElectroncardBaseDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v vslElectroncardBaseDo) RightJoin(table schema.Tabler, on ...field.Expr) IVslElectroncardBaseDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v vslElectroncardBaseDo) Group(cols ...field.Expr) IVslElectroncardBaseDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v vslElectroncardBaseDo) Having(conds ...gen.Condition) IVslElectroncardBaseDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v vslElectroncardBaseDo) Limit(limit int) IVslElectroncardBaseDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v vslElectroncardBaseDo) Offset(offset int) IVslElectroncardBaseDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v vslElectroncardBaseDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IVslElectroncardBaseDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v vslElectroncardBaseDo) Unscoped() IVslElectroncardBaseDo {
	return v.withDO(v.DO.Unscoped())
}

func (v vslElectroncardBaseDo) Create(values ...*fxshop.VslElectroncardBase) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v vslElectroncardBaseDo) CreateInBatches(values []*fxshop.VslElectroncardBase, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v vslElectroncardBaseDo) Save(values ...*fxshop.VslElectroncardBase) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v vslElectroncardBaseDo) First() (*fxshop.VslElectroncardBase, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslElectroncardBase), nil
	}
}

func (v vslElectroncardBaseDo) Take() (*fxshop.VslElectroncardBase, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslElectroncardBase), nil
	}
}

func (v vslElectroncardBaseDo) Last() (*fxshop.VslElectroncardBase, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslElectroncardBase), nil
	}
}

func (v vslElectroncardBaseDo) Find() ([]*fxshop.VslElectroncardBase, error) {
	result, err := v.DO.Find()
	return result.([]*fxshop.VslElectroncardBase), err
}

func (v vslElectroncardBaseDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.VslElectroncardBase, err error) {
	buf := make([]*fxshop.VslElectroncardBase, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v vslElectroncardBaseDo) FindInBatches(result *[]*fxshop.VslElectroncardBase, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v vslElectroncardBaseDo) Attrs(attrs ...field.AssignExpr) IVslElectroncardBaseDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v vslElectroncardBaseDo) Assign(attrs ...field.AssignExpr) IVslElectroncardBaseDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v vslElectroncardBaseDo) Joins(fields ...field.RelationField) IVslElectroncardBaseDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v vslElectroncardBaseDo) Preload(fields ...field.RelationField) IVslElectroncardBaseDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v vslElectroncardBaseDo) FirstOrInit() (*fxshop.VslElectroncardBase, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslElectroncardBase), nil
	}
}

func (v vslElectroncardBaseDo) FirstOrCreate() (*fxshop.VslElectroncardBase, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslElectroncardBase), nil
	}
}

func (v vslElectroncardBaseDo) FindByPage(offset int, limit int) (result []*fxshop.VslElectroncardBase, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v vslElectroncardBaseDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v vslElectroncardBaseDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v vslElectroncardBaseDo) Delete(models ...*fxshop.VslElectroncardBase) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *vslElectroncardBaseDo) withDO(do gen.Dao) *vslElectroncardBaseDo {
	v.DO = *do.(*gen.DO)
	return v
}
