// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"exam-api-sync-go/dao/model/fxshop"
)

func newVslMemberBalanceWithdraw(db *gorm.DB, opts ...gen.DOOption) vslMemberBalanceWithdraw {
	_vslMemberBalanceWithdraw := vslMemberBalanceWithdraw{}

	_vslMemberBalanceWithdraw.vslMemberBalanceWithdrawDo.UseDB(db, opts...)
	_vslMemberBalanceWithdraw.vslMemberBalanceWithdrawDo.UseModel(&fxshop.VslMemberBalanceWithdraw{})

	tableName := _vslMemberBalanceWithdraw.vslMemberBalanceWithdrawDo.TableName()
	_vslMemberBalanceWithdraw.ALL = field.NewAsterisk(tableName)
	_vslMemberBalanceWithdraw.ID = field.NewInt(tableName, "id")
	_vslMemberBalanceWithdraw.ShopID = field.NewInt(tableName, "shop_id")
	_vslMemberBalanceWithdraw.WithdrawNo = field.NewString(tableName, "withdraw_no")
	_vslMemberBalanceWithdraw.UID = field.NewInt(tableName, "uid")
	_vslMemberBalanceWithdraw.AccountNumber = field.NewString(tableName, "account_number")
	_vslMemberBalanceWithdraw.Realname = field.NewString(tableName, "realname")
	_vslMemberBalanceWithdraw.Type = field.NewInt8(tableName, "type")
	_vslMemberBalanceWithdraw.Cash = field.NewFloat64(tableName, "cash")
	_vslMemberBalanceWithdraw.Status = field.NewInt16(tableName, "status")
	_vslMemberBalanceWithdraw.Memo = field.NewString(tableName, "memo")
	_vslMemberBalanceWithdraw.AskForDate = field.NewInt(tableName, "ask_for_date")
	_vslMemberBalanceWithdraw.PaymentDate = field.NewInt(tableName, "payment_date")
	_vslMemberBalanceWithdraw.ModifyDate = field.NewInt(tableName, "modify_date")
	_vslMemberBalanceWithdraw.WebsiteID = field.NewInt(tableName, "website_id")
	_vslMemberBalanceWithdraw.ServiceCharge = field.NewFloat64(tableName, "service_charge")
	_vslMemberBalanceWithdraw.FormID = field.NewString(tableName, "form_id")
	_vslMemberBalanceWithdraw.Charge = field.NewFloat64(tableName, "charge")

	_vslMemberBalanceWithdraw.fillFieldMap()

	return _vslMemberBalanceWithdraw
}

// vslMemberBalanceWithdraw 会员余额提现记录表
type vslMemberBalanceWithdraw struct {
	vslMemberBalanceWithdrawDo

	ALL           field.Asterisk
	ID            field.Int
	ShopID        field.Int     // 店铺编号
	WithdrawNo    field.String  // 提现流水号
	UID           field.Int     // 会员id
	AccountNumber field.String  // 提现账号
	Realname      field.String  // 提现账户姓名
	Type          field.Int8    // 提现类型1银行卡2微信3支付宝
	Cash          field.Float64 // 提现金额
	Status        field.Int16   // 当前状态 1待审核2待打款3已打款4拒绝打款 -1审核不通过
	Memo          field.String  // 备注
	AskForDate    field.Int     // 提现日期
	PaymentDate   field.Int     // 到账日期
	ModifyDate    field.Int     // 修改日期
	WebsiteID     field.Int     // 实例信息
	ServiceCharge field.Float64 // 手续费
	FormID        field.String  // 小程序模板消息form_id
	Charge        field.Float64 // 手续费

	fieldMap map[string]field.Expr
}

func (v vslMemberBalanceWithdraw) Table(newTableName string) *vslMemberBalanceWithdraw {
	v.vslMemberBalanceWithdrawDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v vslMemberBalanceWithdraw) As(alias string) *vslMemberBalanceWithdraw {
	v.vslMemberBalanceWithdrawDo.DO = *(v.vslMemberBalanceWithdrawDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *vslMemberBalanceWithdraw) updateTableName(table string) *vslMemberBalanceWithdraw {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewInt(table, "id")
	v.ShopID = field.NewInt(table, "shop_id")
	v.WithdrawNo = field.NewString(table, "withdraw_no")
	v.UID = field.NewInt(table, "uid")
	v.AccountNumber = field.NewString(table, "account_number")
	v.Realname = field.NewString(table, "realname")
	v.Type = field.NewInt8(table, "type")
	v.Cash = field.NewFloat64(table, "cash")
	v.Status = field.NewInt16(table, "status")
	v.Memo = field.NewString(table, "memo")
	v.AskForDate = field.NewInt(table, "ask_for_date")
	v.PaymentDate = field.NewInt(table, "payment_date")
	v.ModifyDate = field.NewInt(table, "modify_date")
	v.WebsiteID = field.NewInt(table, "website_id")
	v.ServiceCharge = field.NewFloat64(table, "service_charge")
	v.FormID = field.NewString(table, "form_id")
	v.Charge = field.NewFloat64(table, "charge")

	v.fillFieldMap()

	return v
}

func (v *vslMemberBalanceWithdraw) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *vslMemberBalanceWithdraw) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 17)
	v.fieldMap["id"] = v.ID
	v.fieldMap["shop_id"] = v.ShopID
	v.fieldMap["withdraw_no"] = v.WithdrawNo
	v.fieldMap["uid"] = v.UID
	v.fieldMap["account_number"] = v.AccountNumber
	v.fieldMap["realname"] = v.Realname
	v.fieldMap["type"] = v.Type
	v.fieldMap["cash"] = v.Cash
	v.fieldMap["status"] = v.Status
	v.fieldMap["memo"] = v.Memo
	v.fieldMap["ask_for_date"] = v.AskForDate
	v.fieldMap["payment_date"] = v.PaymentDate
	v.fieldMap["modify_date"] = v.ModifyDate
	v.fieldMap["website_id"] = v.WebsiteID
	v.fieldMap["service_charge"] = v.ServiceCharge
	v.fieldMap["form_id"] = v.FormID
	v.fieldMap["charge"] = v.Charge
}

func (v vslMemberBalanceWithdraw) clone(db *gorm.DB) vslMemberBalanceWithdraw {
	v.vslMemberBalanceWithdrawDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v vslMemberBalanceWithdraw) replaceDB(db *gorm.DB) vslMemberBalanceWithdraw {
	v.vslMemberBalanceWithdrawDo.ReplaceDB(db)
	return v
}

type vslMemberBalanceWithdrawDo struct{ gen.DO }

type IVslMemberBalanceWithdrawDo interface {
	gen.SubQuery
	Debug() IVslMemberBalanceWithdrawDo
	WithContext(ctx context.Context) IVslMemberBalanceWithdrawDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IVslMemberBalanceWithdrawDo
	WriteDB() IVslMemberBalanceWithdrawDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IVslMemberBalanceWithdrawDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IVslMemberBalanceWithdrawDo
	Not(conds ...gen.Condition) IVslMemberBalanceWithdrawDo
	Or(conds ...gen.Condition) IVslMemberBalanceWithdrawDo
	Select(conds ...field.Expr) IVslMemberBalanceWithdrawDo
	Where(conds ...gen.Condition) IVslMemberBalanceWithdrawDo
	Order(conds ...field.Expr) IVslMemberBalanceWithdrawDo
	Distinct(cols ...field.Expr) IVslMemberBalanceWithdrawDo
	Omit(cols ...field.Expr) IVslMemberBalanceWithdrawDo
	Join(table schema.Tabler, on ...field.Expr) IVslMemberBalanceWithdrawDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IVslMemberBalanceWithdrawDo
	RightJoin(table schema.Tabler, on ...field.Expr) IVslMemberBalanceWithdrawDo
	Group(cols ...field.Expr) IVslMemberBalanceWithdrawDo
	Having(conds ...gen.Condition) IVslMemberBalanceWithdrawDo
	Limit(limit int) IVslMemberBalanceWithdrawDo
	Offset(offset int) IVslMemberBalanceWithdrawDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IVslMemberBalanceWithdrawDo
	Unscoped() IVslMemberBalanceWithdrawDo
	Create(values ...*fxshop.VslMemberBalanceWithdraw) error
	CreateInBatches(values []*fxshop.VslMemberBalanceWithdraw, batchSize int) error
	Save(values ...*fxshop.VslMemberBalanceWithdraw) error
	First() (*fxshop.VslMemberBalanceWithdraw, error)
	Take() (*fxshop.VslMemberBalanceWithdraw, error)
	Last() (*fxshop.VslMemberBalanceWithdraw, error)
	Find() ([]*fxshop.VslMemberBalanceWithdraw, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.VslMemberBalanceWithdraw, err error)
	FindInBatches(result *[]*fxshop.VslMemberBalanceWithdraw, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*fxshop.VslMemberBalanceWithdraw) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IVslMemberBalanceWithdrawDo
	Assign(attrs ...field.AssignExpr) IVslMemberBalanceWithdrawDo
	Joins(fields ...field.RelationField) IVslMemberBalanceWithdrawDo
	Preload(fields ...field.RelationField) IVslMemberBalanceWithdrawDo
	FirstOrInit() (*fxshop.VslMemberBalanceWithdraw, error)
	FirstOrCreate() (*fxshop.VslMemberBalanceWithdraw, error)
	FindByPage(offset int, limit int) (result []*fxshop.VslMemberBalanceWithdraw, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IVslMemberBalanceWithdrawDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (v vslMemberBalanceWithdrawDo) Debug() IVslMemberBalanceWithdrawDo {
	return v.withDO(v.DO.Debug())
}

func (v vslMemberBalanceWithdrawDo) WithContext(ctx context.Context) IVslMemberBalanceWithdrawDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v vslMemberBalanceWithdrawDo) ReadDB() IVslMemberBalanceWithdrawDo {
	return v.Clauses(dbresolver.Read)
}

func (v vslMemberBalanceWithdrawDo) WriteDB() IVslMemberBalanceWithdrawDo {
	return v.Clauses(dbresolver.Write)
}

func (v vslMemberBalanceWithdrawDo) Session(config *gorm.Session) IVslMemberBalanceWithdrawDo {
	return v.withDO(v.DO.Session(config))
}

func (v vslMemberBalanceWithdrawDo) Clauses(conds ...clause.Expression) IVslMemberBalanceWithdrawDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v vslMemberBalanceWithdrawDo) Returning(value interface{}, columns ...string) IVslMemberBalanceWithdrawDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v vslMemberBalanceWithdrawDo) Not(conds ...gen.Condition) IVslMemberBalanceWithdrawDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v vslMemberBalanceWithdrawDo) Or(conds ...gen.Condition) IVslMemberBalanceWithdrawDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v vslMemberBalanceWithdrawDo) Select(conds ...field.Expr) IVslMemberBalanceWithdrawDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v vslMemberBalanceWithdrawDo) Where(conds ...gen.Condition) IVslMemberBalanceWithdrawDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v vslMemberBalanceWithdrawDo) Order(conds ...field.Expr) IVslMemberBalanceWithdrawDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v vslMemberBalanceWithdrawDo) Distinct(cols ...field.Expr) IVslMemberBalanceWithdrawDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v vslMemberBalanceWithdrawDo) Omit(cols ...field.Expr) IVslMemberBalanceWithdrawDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v vslMemberBalanceWithdrawDo) Join(table schema.Tabler, on ...field.Expr) IVslMemberBalanceWithdrawDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v vslMemberBalanceWithdrawDo) LeftJoin(table schema.Tabler, on ...field.Expr) IVslMemberBalanceWithdrawDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v vslMemberBalanceWithdrawDo) RightJoin(table schema.Tabler, on ...field.Expr) IVslMemberBalanceWithdrawDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v vslMemberBalanceWithdrawDo) Group(cols ...field.Expr) IVslMemberBalanceWithdrawDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v vslMemberBalanceWithdrawDo) Having(conds ...gen.Condition) IVslMemberBalanceWithdrawDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v vslMemberBalanceWithdrawDo) Limit(limit int) IVslMemberBalanceWithdrawDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v vslMemberBalanceWithdrawDo) Offset(offset int) IVslMemberBalanceWithdrawDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v vslMemberBalanceWithdrawDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IVslMemberBalanceWithdrawDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v vslMemberBalanceWithdrawDo) Unscoped() IVslMemberBalanceWithdrawDo {
	return v.withDO(v.DO.Unscoped())
}

func (v vslMemberBalanceWithdrawDo) Create(values ...*fxshop.VslMemberBalanceWithdraw) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v vslMemberBalanceWithdrawDo) CreateInBatches(values []*fxshop.VslMemberBalanceWithdraw, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v vslMemberBalanceWithdrawDo) Save(values ...*fxshop.VslMemberBalanceWithdraw) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v vslMemberBalanceWithdrawDo) First() (*fxshop.VslMemberBalanceWithdraw, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslMemberBalanceWithdraw), nil
	}
}

func (v vslMemberBalanceWithdrawDo) Take() (*fxshop.VslMemberBalanceWithdraw, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslMemberBalanceWithdraw), nil
	}
}

func (v vslMemberBalanceWithdrawDo) Last() (*fxshop.VslMemberBalanceWithdraw, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslMemberBalanceWithdraw), nil
	}
}

func (v vslMemberBalanceWithdrawDo) Find() ([]*fxshop.VslMemberBalanceWithdraw, error) {
	result, err := v.DO.Find()
	return result.([]*fxshop.VslMemberBalanceWithdraw), err
}

func (v vslMemberBalanceWithdrawDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.VslMemberBalanceWithdraw, err error) {
	buf := make([]*fxshop.VslMemberBalanceWithdraw, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v vslMemberBalanceWithdrawDo) FindInBatches(result *[]*fxshop.VslMemberBalanceWithdraw, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v vslMemberBalanceWithdrawDo) Attrs(attrs ...field.AssignExpr) IVslMemberBalanceWithdrawDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v vslMemberBalanceWithdrawDo) Assign(attrs ...field.AssignExpr) IVslMemberBalanceWithdrawDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v vslMemberBalanceWithdrawDo) Joins(fields ...field.RelationField) IVslMemberBalanceWithdrawDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v vslMemberBalanceWithdrawDo) Preload(fields ...field.RelationField) IVslMemberBalanceWithdrawDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v vslMemberBalanceWithdrawDo) FirstOrInit() (*fxshop.VslMemberBalanceWithdraw, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslMemberBalanceWithdraw), nil
	}
}

func (v vslMemberBalanceWithdrawDo) FirstOrCreate() (*fxshop.VslMemberBalanceWithdraw, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslMemberBalanceWithdraw), nil
	}
}

func (v vslMemberBalanceWithdrawDo) FindByPage(offset int, limit int) (result []*fxshop.VslMemberBalanceWithdraw, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v vslMemberBalanceWithdrawDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v vslMemberBalanceWithdrawDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v vslMemberBalanceWithdrawDo) Delete(models ...*fxshop.VslMemberBalanceWithdraw) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *vslMemberBalanceWithdrawDo) withDO(do gen.Dao) *vslMemberBalanceWithdrawDo {
	v.DO = *do.(*gen.DO)
	return v
}
