// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"exam-api-sync-go/dao/model/fxshop"
)

func newVslCouponType(db *gorm.DB, opts ...gen.DOOption) vslCouponType {
	_vslCouponType := vslCouponType{}

	_vslCouponType.vslCouponTypeDo.UseDB(db, opts...)
	_vslCouponType.vslCouponTypeDo.UseModel(&fxshop.VslCouponType{})

	tableName := _vslCouponType.vslCouponTypeDo.TableName()
	_vslCouponType.ALL = field.NewAsterisk(tableName)
	_vslCouponType.CouponTypeID = field.NewInt(tableName, "coupon_type_id")
	_vslCouponType.ShopID = field.NewInt(tableName, "shop_id")
	_vslCouponType.ShopRangeType = field.NewInt8(tableName, "shop_range_type")
	_vslCouponType.CouponGenre = field.NewInt8(tableName, "coupon_genre")
	_vslCouponType.CouponName = field.NewString(tableName, "coupon_name")
	_vslCouponType.Money = field.NewFloat64(tableName, "money")
	_vslCouponType.Count_ = field.NewInt(tableName, "count")
	_vslCouponType.MaxFetch = field.NewInt(tableName, "max_fetch")
	_vslCouponType.AtLeast = field.NewFloat64(tableName, "at_least")
	_vslCouponType.Discount = field.NewFloat64(tableName, "discount")
	_vslCouponType.RangeType = field.NewInt8(tableName, "range_type")
	_vslCouponType.StartTime = field.NewInt(tableName, "start_time")
	_vslCouponType.EndTime = field.NewInt(tableName, "end_time")
	_vslCouponType.CreateTime = field.NewInt(tableName, "create_time")
	_vslCouponType.UpdateTime = field.NewInt(tableName, "update_time")
	_vslCouponType.StartReceiveTime = field.NewInt(tableName, "start_receive_time")
	_vslCouponType.EndReceiveTime = field.NewInt(tableName, "end_receive_time")
	_vslCouponType.IsFetch = field.NewInt8(tableName, "is_fetch")
	_vslCouponType.IsSendFriend = field.NewInt8(tableName, "is_send_friend")
	_vslCouponType.ExpireTime = field.NewInt(tableName, "expire_time")
	_vslCouponType.WebsiteID = field.NewInt(tableName, "website_id")
	_vslCouponType.Desc = field.NewString(tableName, "desc")
	_vslCouponType.CategoryExtendID = field.NewString(tableName, "category_extend_id")
	_vslCouponType.ExtendCategoryId1S = field.NewString(tableName, "extend_category_id_1s")
	_vslCouponType.ExtendCategoryId2S = field.NewString(tableName, "extend_category_id_2s")
	_vslCouponType.ExtendCategoryId3S = field.NewString(tableName, "extend_category_id_3s")

	_vslCouponType.fillFieldMap()

	return _vslCouponType
}

// vslCouponType 优惠券类型表
type vslCouponType struct {
	vslCouponTypeDo

	ALL                field.Asterisk
	CouponTypeID       field.Int     // 优惠券类型Id
	ShopID             field.Int     // 店铺ID
	ShopRangeType      field.Int8    // 优惠券适用范围，1-直营店，2-全平台
	CouponGenre        field.Int8    // 优惠券类型，1-无门槛，2-满减，3-折扣
	CouponName         field.String  // 优惠券名称
	Money              field.Float64 // 发放面额
	Count_             field.Int     // 发放数量
	MaxFetch           field.Int     // 每人最大领取个数 0无限制
	AtLeast            field.Float64 // 满多少元使用
	Discount           field.Float64 // 10.00不打折，0.00免费
	RangeType          field.Int8    // 使用范围0部分产品使用 1全场产品使用
	StartTime          field.Int     // 有效日期开始时间
	EndTime            field.Int     // 有效日期结束时间
	CreateTime         field.Int     // 创建时间
	UpdateTime         field.Int     // 修改时间
	StartReceiveTime   field.Int     // 开始领券时间
	EndReceiveTime     field.Int     // 最后领券时间
	IsFetch            field.Int8    // 0->用户不能主动获取，用于注册奖励等，1->用户可以主动获取
	IsSendFriend       field.Int8    // //是否赠送朋友
	ExpireTime         field.Int     // //赠送过期时间
	WebsiteID          field.Int     // 实例信息
	Desc               field.String  // 优惠券说明
	CategoryExtendID   field.String  // 商品分类
	ExtendCategoryId1S field.String
	ExtendCategoryId2S field.String
	ExtendCategoryId3S field.String

	fieldMap map[string]field.Expr
}

func (v vslCouponType) Table(newTableName string) *vslCouponType {
	v.vslCouponTypeDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v vslCouponType) As(alias string) *vslCouponType {
	v.vslCouponTypeDo.DO = *(v.vslCouponTypeDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *vslCouponType) updateTableName(table string) *vslCouponType {
	v.ALL = field.NewAsterisk(table)
	v.CouponTypeID = field.NewInt(table, "coupon_type_id")
	v.ShopID = field.NewInt(table, "shop_id")
	v.ShopRangeType = field.NewInt8(table, "shop_range_type")
	v.CouponGenre = field.NewInt8(table, "coupon_genre")
	v.CouponName = field.NewString(table, "coupon_name")
	v.Money = field.NewFloat64(table, "money")
	v.Count_ = field.NewInt(table, "count")
	v.MaxFetch = field.NewInt(table, "max_fetch")
	v.AtLeast = field.NewFloat64(table, "at_least")
	v.Discount = field.NewFloat64(table, "discount")
	v.RangeType = field.NewInt8(table, "range_type")
	v.StartTime = field.NewInt(table, "start_time")
	v.EndTime = field.NewInt(table, "end_time")
	v.CreateTime = field.NewInt(table, "create_time")
	v.UpdateTime = field.NewInt(table, "update_time")
	v.StartReceiveTime = field.NewInt(table, "start_receive_time")
	v.EndReceiveTime = field.NewInt(table, "end_receive_time")
	v.IsFetch = field.NewInt8(table, "is_fetch")
	v.IsSendFriend = field.NewInt8(table, "is_send_friend")
	v.ExpireTime = field.NewInt(table, "expire_time")
	v.WebsiteID = field.NewInt(table, "website_id")
	v.Desc = field.NewString(table, "desc")
	v.CategoryExtendID = field.NewString(table, "category_extend_id")
	v.ExtendCategoryId1S = field.NewString(table, "extend_category_id_1s")
	v.ExtendCategoryId2S = field.NewString(table, "extend_category_id_2s")
	v.ExtendCategoryId3S = field.NewString(table, "extend_category_id_3s")

	v.fillFieldMap()

	return v
}

func (v *vslCouponType) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *vslCouponType) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 26)
	v.fieldMap["coupon_type_id"] = v.CouponTypeID
	v.fieldMap["shop_id"] = v.ShopID
	v.fieldMap["shop_range_type"] = v.ShopRangeType
	v.fieldMap["coupon_genre"] = v.CouponGenre
	v.fieldMap["coupon_name"] = v.CouponName
	v.fieldMap["money"] = v.Money
	v.fieldMap["count"] = v.Count_
	v.fieldMap["max_fetch"] = v.MaxFetch
	v.fieldMap["at_least"] = v.AtLeast
	v.fieldMap["discount"] = v.Discount
	v.fieldMap["range_type"] = v.RangeType
	v.fieldMap["start_time"] = v.StartTime
	v.fieldMap["end_time"] = v.EndTime
	v.fieldMap["create_time"] = v.CreateTime
	v.fieldMap["update_time"] = v.UpdateTime
	v.fieldMap["start_receive_time"] = v.StartReceiveTime
	v.fieldMap["end_receive_time"] = v.EndReceiveTime
	v.fieldMap["is_fetch"] = v.IsFetch
	v.fieldMap["is_send_friend"] = v.IsSendFriend
	v.fieldMap["expire_time"] = v.ExpireTime
	v.fieldMap["website_id"] = v.WebsiteID
	v.fieldMap["desc"] = v.Desc
	v.fieldMap["category_extend_id"] = v.CategoryExtendID
	v.fieldMap["extend_category_id_1s"] = v.ExtendCategoryId1S
	v.fieldMap["extend_category_id_2s"] = v.ExtendCategoryId2S
	v.fieldMap["extend_category_id_3s"] = v.ExtendCategoryId3S
}

func (v vslCouponType) clone(db *gorm.DB) vslCouponType {
	v.vslCouponTypeDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v vslCouponType) replaceDB(db *gorm.DB) vslCouponType {
	v.vslCouponTypeDo.ReplaceDB(db)
	return v
}

type vslCouponTypeDo struct{ gen.DO }

type IVslCouponTypeDo interface {
	gen.SubQuery
	Debug() IVslCouponTypeDo
	WithContext(ctx context.Context) IVslCouponTypeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IVslCouponTypeDo
	WriteDB() IVslCouponTypeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IVslCouponTypeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IVslCouponTypeDo
	Not(conds ...gen.Condition) IVslCouponTypeDo
	Or(conds ...gen.Condition) IVslCouponTypeDo
	Select(conds ...field.Expr) IVslCouponTypeDo
	Where(conds ...gen.Condition) IVslCouponTypeDo
	Order(conds ...field.Expr) IVslCouponTypeDo
	Distinct(cols ...field.Expr) IVslCouponTypeDo
	Omit(cols ...field.Expr) IVslCouponTypeDo
	Join(table schema.Tabler, on ...field.Expr) IVslCouponTypeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IVslCouponTypeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IVslCouponTypeDo
	Group(cols ...field.Expr) IVslCouponTypeDo
	Having(conds ...gen.Condition) IVslCouponTypeDo
	Limit(limit int) IVslCouponTypeDo
	Offset(offset int) IVslCouponTypeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IVslCouponTypeDo
	Unscoped() IVslCouponTypeDo
	Create(values ...*fxshop.VslCouponType) error
	CreateInBatches(values []*fxshop.VslCouponType, batchSize int) error
	Save(values ...*fxshop.VslCouponType) error
	First() (*fxshop.VslCouponType, error)
	Take() (*fxshop.VslCouponType, error)
	Last() (*fxshop.VslCouponType, error)
	Find() ([]*fxshop.VslCouponType, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.VslCouponType, err error)
	FindInBatches(result *[]*fxshop.VslCouponType, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*fxshop.VslCouponType) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IVslCouponTypeDo
	Assign(attrs ...field.AssignExpr) IVslCouponTypeDo
	Joins(fields ...field.RelationField) IVslCouponTypeDo
	Preload(fields ...field.RelationField) IVslCouponTypeDo
	FirstOrInit() (*fxshop.VslCouponType, error)
	FirstOrCreate() (*fxshop.VslCouponType, error)
	FindByPage(offset int, limit int) (result []*fxshop.VslCouponType, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IVslCouponTypeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (v vslCouponTypeDo) Debug() IVslCouponTypeDo {
	return v.withDO(v.DO.Debug())
}

func (v vslCouponTypeDo) WithContext(ctx context.Context) IVslCouponTypeDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v vslCouponTypeDo) ReadDB() IVslCouponTypeDo {
	return v.Clauses(dbresolver.Read)
}

func (v vslCouponTypeDo) WriteDB() IVslCouponTypeDo {
	return v.Clauses(dbresolver.Write)
}

func (v vslCouponTypeDo) Session(config *gorm.Session) IVslCouponTypeDo {
	return v.withDO(v.DO.Session(config))
}

func (v vslCouponTypeDo) Clauses(conds ...clause.Expression) IVslCouponTypeDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v vslCouponTypeDo) Returning(value interface{}, columns ...string) IVslCouponTypeDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v vslCouponTypeDo) Not(conds ...gen.Condition) IVslCouponTypeDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v vslCouponTypeDo) Or(conds ...gen.Condition) IVslCouponTypeDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v vslCouponTypeDo) Select(conds ...field.Expr) IVslCouponTypeDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v vslCouponTypeDo) Where(conds ...gen.Condition) IVslCouponTypeDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v vslCouponTypeDo) Order(conds ...field.Expr) IVslCouponTypeDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v vslCouponTypeDo) Distinct(cols ...field.Expr) IVslCouponTypeDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v vslCouponTypeDo) Omit(cols ...field.Expr) IVslCouponTypeDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v vslCouponTypeDo) Join(table schema.Tabler, on ...field.Expr) IVslCouponTypeDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v vslCouponTypeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IVslCouponTypeDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v vslCouponTypeDo) RightJoin(table schema.Tabler, on ...field.Expr) IVslCouponTypeDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v vslCouponTypeDo) Group(cols ...field.Expr) IVslCouponTypeDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v vslCouponTypeDo) Having(conds ...gen.Condition) IVslCouponTypeDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v vslCouponTypeDo) Limit(limit int) IVslCouponTypeDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v vslCouponTypeDo) Offset(offset int) IVslCouponTypeDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v vslCouponTypeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IVslCouponTypeDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v vslCouponTypeDo) Unscoped() IVslCouponTypeDo {
	return v.withDO(v.DO.Unscoped())
}

func (v vslCouponTypeDo) Create(values ...*fxshop.VslCouponType) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v vslCouponTypeDo) CreateInBatches(values []*fxshop.VslCouponType, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v vslCouponTypeDo) Save(values ...*fxshop.VslCouponType) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v vslCouponTypeDo) First() (*fxshop.VslCouponType, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslCouponType), nil
	}
}

func (v vslCouponTypeDo) Take() (*fxshop.VslCouponType, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslCouponType), nil
	}
}

func (v vslCouponTypeDo) Last() (*fxshop.VslCouponType, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslCouponType), nil
	}
}

func (v vslCouponTypeDo) Find() ([]*fxshop.VslCouponType, error) {
	result, err := v.DO.Find()
	return result.([]*fxshop.VslCouponType), err
}

func (v vslCouponTypeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.VslCouponType, err error) {
	buf := make([]*fxshop.VslCouponType, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v vslCouponTypeDo) FindInBatches(result *[]*fxshop.VslCouponType, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v vslCouponTypeDo) Attrs(attrs ...field.AssignExpr) IVslCouponTypeDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v vslCouponTypeDo) Assign(attrs ...field.AssignExpr) IVslCouponTypeDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v vslCouponTypeDo) Joins(fields ...field.RelationField) IVslCouponTypeDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v vslCouponTypeDo) Preload(fields ...field.RelationField) IVslCouponTypeDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v vslCouponTypeDo) FirstOrInit() (*fxshop.VslCouponType, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslCouponType), nil
	}
}

func (v vslCouponTypeDo) FirstOrCreate() (*fxshop.VslCouponType, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslCouponType), nil
	}
}

func (v vslCouponTypeDo) FindByPage(offset int, limit int) (result []*fxshop.VslCouponType, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v vslCouponTypeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v vslCouponTypeDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v vslCouponTypeDo) Delete(models ...*fxshop.VslCouponType) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *vslCouponTypeDo) withDO(do gen.Dao) *vslCouponTypeDo {
	v.DO = *do.(*gen.DO)
	return v
}
