// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"exam-api-sync-go/dao/model/fxshop"
)

func newVslMemberExpressAddress(db *gorm.DB, opts ...gen.DOOption) vslMemberExpressAddress {
	_vslMemberExpressAddress := vslMemberExpressAddress{}

	_vslMemberExpressAddress.vslMemberExpressAddressDo.UseDB(db, opts...)
	_vslMemberExpressAddress.vslMemberExpressAddressDo.UseModel(&fxshop.VslMemberExpressAddress{})

	tableName := _vslMemberExpressAddress.vslMemberExpressAddressDo.TableName()
	_vslMemberExpressAddress.ALL = field.NewAsterisk(tableName)
	_vslMemberExpressAddress.ID = field.NewInt(tableName, "id")
	_vslMemberExpressAddress.UID = field.NewInt(tableName, "uid")
	_vslMemberExpressAddress.Consigner = field.NewString(tableName, "consigner")
	_vslMemberExpressAddress.Mobile = field.NewString(tableName, "mobile")
	_vslMemberExpressAddress.Phone = field.NewString(tableName, "phone")
	_vslMemberExpressAddress.Province = field.NewInt(tableName, "province")
	_vslMemberExpressAddress.City = field.NewInt(tableName, "city")
	_vslMemberExpressAddress.District = field.NewInt(tableName, "district")
	_vslMemberExpressAddress.Address = field.NewString(tableName, "address")
	_vslMemberExpressAddress.ZipCode = field.NewString(tableName, "zip_code")
	_vslMemberExpressAddress.Alias_ = field.NewString(tableName, "alias")
	_vslMemberExpressAddress.IsDefault = field.NewInt(tableName, "is_default")
	_vslMemberExpressAddress.WebsiteID = field.NewInt(tableName, "website_id")
	_vslMemberExpressAddress.AreaCode = field.NewString(tableName, "area_code")
	_vslMemberExpressAddress.Type = field.NewInt8(tableName, "type")
	_vslMemberExpressAddress.CountryID = field.NewInt(tableName, "country_id")

	_vslMemberExpressAddress.fillFieldMap()

	return _vslMemberExpressAddress
}

// vslMemberExpressAddress 会员收货地址管理
type vslMemberExpressAddress struct {
	vslMemberExpressAddressDo

	ALL       field.Asterisk
	ID        field.Int
	UID       field.Int    // 会员基本资料表ID
	Consigner field.String // 收件人
	Mobile    field.String // 手机
	Phone     field.String // 固定电话
	Province  field.Int    // 省
	City      field.Int    // 市
	District  field.Int    // 区县
	Address   field.String // 详细地址
	ZipCode   field.String // 邮编
	Alias_    field.String // 地址别名
	IsDefault field.Int    // 默认收货地址
	WebsiteID field.Int    // 实例信息
	AreaCode  field.String // wap 地区选择器
	Type      field.Int8   // 类型： 0：国内  1：国外
	CountryID field.Int    // 国家id

	fieldMap map[string]field.Expr
}

func (v vslMemberExpressAddress) Table(newTableName string) *vslMemberExpressAddress {
	v.vslMemberExpressAddressDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v vslMemberExpressAddress) As(alias string) *vslMemberExpressAddress {
	v.vslMemberExpressAddressDo.DO = *(v.vslMemberExpressAddressDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *vslMemberExpressAddress) updateTableName(table string) *vslMemberExpressAddress {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewInt(table, "id")
	v.UID = field.NewInt(table, "uid")
	v.Consigner = field.NewString(table, "consigner")
	v.Mobile = field.NewString(table, "mobile")
	v.Phone = field.NewString(table, "phone")
	v.Province = field.NewInt(table, "province")
	v.City = field.NewInt(table, "city")
	v.District = field.NewInt(table, "district")
	v.Address = field.NewString(table, "address")
	v.ZipCode = field.NewString(table, "zip_code")
	v.Alias_ = field.NewString(table, "alias")
	v.IsDefault = field.NewInt(table, "is_default")
	v.WebsiteID = field.NewInt(table, "website_id")
	v.AreaCode = field.NewString(table, "area_code")
	v.Type = field.NewInt8(table, "type")
	v.CountryID = field.NewInt(table, "country_id")

	v.fillFieldMap()

	return v
}

func (v *vslMemberExpressAddress) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *vslMemberExpressAddress) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 16)
	v.fieldMap["id"] = v.ID
	v.fieldMap["uid"] = v.UID
	v.fieldMap["consigner"] = v.Consigner
	v.fieldMap["mobile"] = v.Mobile
	v.fieldMap["phone"] = v.Phone
	v.fieldMap["province"] = v.Province
	v.fieldMap["city"] = v.City
	v.fieldMap["district"] = v.District
	v.fieldMap["address"] = v.Address
	v.fieldMap["zip_code"] = v.ZipCode
	v.fieldMap["alias"] = v.Alias_
	v.fieldMap["is_default"] = v.IsDefault
	v.fieldMap["website_id"] = v.WebsiteID
	v.fieldMap["area_code"] = v.AreaCode
	v.fieldMap["type"] = v.Type
	v.fieldMap["country_id"] = v.CountryID
}

func (v vslMemberExpressAddress) clone(db *gorm.DB) vslMemberExpressAddress {
	v.vslMemberExpressAddressDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v vslMemberExpressAddress) replaceDB(db *gorm.DB) vslMemberExpressAddress {
	v.vslMemberExpressAddressDo.ReplaceDB(db)
	return v
}

type vslMemberExpressAddressDo struct{ gen.DO }

type IVslMemberExpressAddressDo interface {
	gen.SubQuery
	Debug() IVslMemberExpressAddressDo
	WithContext(ctx context.Context) IVslMemberExpressAddressDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IVslMemberExpressAddressDo
	WriteDB() IVslMemberExpressAddressDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IVslMemberExpressAddressDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IVslMemberExpressAddressDo
	Not(conds ...gen.Condition) IVslMemberExpressAddressDo
	Or(conds ...gen.Condition) IVslMemberExpressAddressDo
	Select(conds ...field.Expr) IVslMemberExpressAddressDo
	Where(conds ...gen.Condition) IVslMemberExpressAddressDo
	Order(conds ...field.Expr) IVslMemberExpressAddressDo
	Distinct(cols ...field.Expr) IVslMemberExpressAddressDo
	Omit(cols ...field.Expr) IVslMemberExpressAddressDo
	Join(table schema.Tabler, on ...field.Expr) IVslMemberExpressAddressDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IVslMemberExpressAddressDo
	RightJoin(table schema.Tabler, on ...field.Expr) IVslMemberExpressAddressDo
	Group(cols ...field.Expr) IVslMemberExpressAddressDo
	Having(conds ...gen.Condition) IVslMemberExpressAddressDo
	Limit(limit int) IVslMemberExpressAddressDo
	Offset(offset int) IVslMemberExpressAddressDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IVslMemberExpressAddressDo
	Unscoped() IVslMemberExpressAddressDo
	Create(values ...*fxshop.VslMemberExpressAddress) error
	CreateInBatches(values []*fxshop.VslMemberExpressAddress, batchSize int) error
	Save(values ...*fxshop.VslMemberExpressAddress) error
	First() (*fxshop.VslMemberExpressAddress, error)
	Take() (*fxshop.VslMemberExpressAddress, error)
	Last() (*fxshop.VslMemberExpressAddress, error)
	Find() ([]*fxshop.VslMemberExpressAddress, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.VslMemberExpressAddress, err error)
	FindInBatches(result *[]*fxshop.VslMemberExpressAddress, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*fxshop.VslMemberExpressAddress) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IVslMemberExpressAddressDo
	Assign(attrs ...field.AssignExpr) IVslMemberExpressAddressDo
	Joins(fields ...field.RelationField) IVslMemberExpressAddressDo
	Preload(fields ...field.RelationField) IVslMemberExpressAddressDo
	FirstOrInit() (*fxshop.VslMemberExpressAddress, error)
	FirstOrCreate() (*fxshop.VslMemberExpressAddress, error)
	FindByPage(offset int, limit int) (result []*fxshop.VslMemberExpressAddress, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IVslMemberExpressAddressDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (v vslMemberExpressAddressDo) Debug() IVslMemberExpressAddressDo {
	return v.withDO(v.DO.Debug())
}

func (v vslMemberExpressAddressDo) WithContext(ctx context.Context) IVslMemberExpressAddressDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v vslMemberExpressAddressDo) ReadDB() IVslMemberExpressAddressDo {
	return v.Clauses(dbresolver.Read)
}

func (v vslMemberExpressAddressDo) WriteDB() IVslMemberExpressAddressDo {
	return v.Clauses(dbresolver.Write)
}

func (v vslMemberExpressAddressDo) Session(config *gorm.Session) IVslMemberExpressAddressDo {
	return v.withDO(v.DO.Session(config))
}

func (v vslMemberExpressAddressDo) Clauses(conds ...clause.Expression) IVslMemberExpressAddressDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v vslMemberExpressAddressDo) Returning(value interface{}, columns ...string) IVslMemberExpressAddressDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v vslMemberExpressAddressDo) Not(conds ...gen.Condition) IVslMemberExpressAddressDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v vslMemberExpressAddressDo) Or(conds ...gen.Condition) IVslMemberExpressAddressDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v vslMemberExpressAddressDo) Select(conds ...field.Expr) IVslMemberExpressAddressDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v vslMemberExpressAddressDo) Where(conds ...gen.Condition) IVslMemberExpressAddressDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v vslMemberExpressAddressDo) Order(conds ...field.Expr) IVslMemberExpressAddressDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v vslMemberExpressAddressDo) Distinct(cols ...field.Expr) IVslMemberExpressAddressDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v vslMemberExpressAddressDo) Omit(cols ...field.Expr) IVslMemberExpressAddressDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v vslMemberExpressAddressDo) Join(table schema.Tabler, on ...field.Expr) IVslMemberExpressAddressDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v vslMemberExpressAddressDo) LeftJoin(table schema.Tabler, on ...field.Expr) IVslMemberExpressAddressDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v vslMemberExpressAddressDo) RightJoin(table schema.Tabler, on ...field.Expr) IVslMemberExpressAddressDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v vslMemberExpressAddressDo) Group(cols ...field.Expr) IVslMemberExpressAddressDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v vslMemberExpressAddressDo) Having(conds ...gen.Condition) IVslMemberExpressAddressDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v vslMemberExpressAddressDo) Limit(limit int) IVslMemberExpressAddressDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v vslMemberExpressAddressDo) Offset(offset int) IVslMemberExpressAddressDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v vslMemberExpressAddressDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IVslMemberExpressAddressDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v vslMemberExpressAddressDo) Unscoped() IVslMemberExpressAddressDo {
	return v.withDO(v.DO.Unscoped())
}

func (v vslMemberExpressAddressDo) Create(values ...*fxshop.VslMemberExpressAddress) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v vslMemberExpressAddressDo) CreateInBatches(values []*fxshop.VslMemberExpressAddress, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v vslMemberExpressAddressDo) Save(values ...*fxshop.VslMemberExpressAddress) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v vslMemberExpressAddressDo) First() (*fxshop.VslMemberExpressAddress, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslMemberExpressAddress), nil
	}
}

func (v vslMemberExpressAddressDo) Take() (*fxshop.VslMemberExpressAddress, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslMemberExpressAddress), nil
	}
}

func (v vslMemberExpressAddressDo) Last() (*fxshop.VslMemberExpressAddress, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslMemberExpressAddress), nil
	}
}

func (v vslMemberExpressAddressDo) Find() ([]*fxshop.VslMemberExpressAddress, error) {
	result, err := v.DO.Find()
	return result.([]*fxshop.VslMemberExpressAddress), err
}

func (v vslMemberExpressAddressDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.VslMemberExpressAddress, err error) {
	buf := make([]*fxshop.VslMemberExpressAddress, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v vslMemberExpressAddressDo) FindInBatches(result *[]*fxshop.VslMemberExpressAddress, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v vslMemberExpressAddressDo) Attrs(attrs ...field.AssignExpr) IVslMemberExpressAddressDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v vslMemberExpressAddressDo) Assign(attrs ...field.AssignExpr) IVslMemberExpressAddressDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v vslMemberExpressAddressDo) Joins(fields ...field.RelationField) IVslMemberExpressAddressDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v vslMemberExpressAddressDo) Preload(fields ...field.RelationField) IVslMemberExpressAddressDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v vslMemberExpressAddressDo) FirstOrInit() (*fxshop.VslMemberExpressAddress, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslMemberExpressAddress), nil
	}
}

func (v vslMemberExpressAddressDo) FirstOrCreate() (*fxshop.VslMemberExpressAddress, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslMemberExpressAddress), nil
	}
}

func (v vslMemberExpressAddressDo) FindByPage(offset int, limit int) (result []*fxshop.VslMemberExpressAddress, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v vslMemberExpressAddressDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v vslMemberExpressAddressDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v vslMemberExpressAddressDo) Delete(models ...*fxshop.VslMemberExpressAddress) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *vslMemberExpressAddressDo) withDO(do gen.Dao) *vslMemberExpressAddressDo {
	v.DO = *do.(*gen.DO)
	return v
}
