// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package fxshop

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"exam-api-sync-go/dao/model/fxshop"
)

func newVslGoods(db *gorm.DB, opts ...gen.DOOption) vslGoods {
	_vslGoods := vslGoods{}

	_vslGoods.vslGoodsDo.UseDB(db, opts...)
	_vslGoods.vslGoodsDo.UseModel(&fxshop.VslGoods{})

	tableName := _vslGoods.vslGoodsDo.TableName()
	_vslGoods.ALL = field.NewAsterisk(tableName)
	_vslGoods.GoodsID = field.NewInt(tableName, "goods_id")
	_vslGoods.GoodsName = field.NewString(tableName, "goods_name")
	_vslGoods.WebsiteID = field.NewInt(tableName, "website_id")
	_vslGoods.ShopID = field.NewInt(tableName, "shop_id")
	_vslGoods.CategoryID = field.NewInt(tableName, "category_id")
	_vslGoods.CategoryId1 = field.NewInt(tableName, "category_id_1")
	_vslGoods.CategoryId2 = field.NewInt(tableName, "category_id_2")
	_vslGoods.CategoryId3 = field.NewInt(tableName, "category_id_3")
	_vslGoods.BrandID = field.NewInt(tableName, "brand_id")
	_vslGoods.GroupIDArray = field.NewString(tableName, "group_id_array")
	_vslGoods.PromotionType = field.NewInt8(tableName, "promotion_type")
	_vslGoods.PromoteID = field.NewInt(tableName, "promote_id")
	_vslGoods.GoodsType = field.NewInt8(tableName, "goods_type")
	_vslGoods.MarketPrice = field.NewFloat64(tableName, "market_price")
	_vslGoods.Price = field.NewFloat64(tableName, "price")
	_vslGoods.PromotionPrice = field.NewFloat64(tableName, "promotion_price")
	_vslGoods.CostPrice = field.NewFloat64(tableName, "cost_price")
	_vslGoods.PointExchangeType = field.NewInt8(tableName, "point_exchange_type")
	_vslGoods.PointExchange = field.NewInt(tableName, "point_exchange")
	_vslGoods.GivePoint = field.NewInt(tableName, "give_point")
	_vslGoods.IsMemberDiscount = field.NewInt(tableName, "is_member_discount")
	_vslGoods.ShippingFee = field.NewFloat64(tableName, "shipping_fee")
	_vslGoods.ShippingFeeID = field.NewInt(tableName, "shipping_fee_id")
	_vslGoods.Stock = field.NewInt(tableName, "stock")
	_vslGoods.MaxBuy = field.NewInt(tableName, "max_buy")
	_vslGoods.LeastBuy = field.NewInt(tableName, "least_buy")
	_vslGoods.MaxBuyTime = field.NewInt(tableName, "max_buy_time")
	_vslGoods.Clicks = field.NewInt(tableName, "clicks")
	_vslGoods.MinStockAlarm = field.NewInt(tableName, "min_stock_alarm")
	_vslGoods.Sales = field.NewInt(tableName, "sales")
	_vslGoods.Collects = field.NewInt(tableName, "collects")
	_vslGoods.Star = field.NewInt8(tableName, "star")
	_vslGoods.Evaluates = field.NewInt(tableName, "evaluates")
	_vslGoods.Shares = field.NewInt(tableName, "shares")
	_vslGoods.ProvinceID = field.NewInt(tableName, "province_id")
	_vslGoods.CityID = field.NewInt(tableName, "city_id")
	_vslGoods.Picture = field.NewInt(tableName, "picture")
	_vslGoods.Keywords = field.NewString(tableName, "keywords")
	_vslGoods.Introduction = field.NewString(tableName, "introduction")
	_vslGoods.Description = field.NewString(tableName, "description")
	_vslGoods.QRcode = field.NewString(tableName, "QRcode")
	_vslGoods.Code = field.NewString(tableName, "code")
	_vslGoods.IsStockVisible = field.NewInt(tableName, "is_stock_visible")
	_vslGoods.IsPromotion = field.NewInt(tableName, "is_promotion")
	_vslGoods.IsShippingFree = field.NewInt(tableName, "is_shipping_free")
	_vslGoods.IsHot = field.NewInt(tableName, "is_hot")
	_vslGoods.IsRecommend = field.NewInt(tableName, "is_recommend")
	_vslGoods.IsNew = field.NewInt(tableName, "is_new")
	_vslGoods.IsPreSale = field.NewInt(tableName, "is_pre_sale")
	_vslGoods.IsBill = field.NewInt(tableName, "is_bill")
	_vslGoods.State = field.NewInt8(tableName, "state")
	_vslGoods.Sort = field.NewInt(tableName, "sort")
	_vslGoods.ImgIDArray = field.NewString(tableName, "img_id_array")
	_vslGoods.SkuImgArray = field.NewString(tableName, "sku_img_array")
	_vslGoods.MatchPoint = field.NewFloat32(tableName, "match_point")
	_vslGoods.MatchRatio = field.NewFloat32(tableName, "match_ratio")
	_vslGoods.RealSales = field.NewInt(tableName, "real_sales")
	_vslGoods.GoodsAttributeID = field.NewInt(tableName, "goods_attribute_id")
	_vslGoods.GoodsSpecFormat = field.NewString(tableName, "goods_spec_format")
	_vslGoods.GoodsWeight = field.NewFloat64(tableName, "goods_weight")
	_vslGoods.GoodsVolume = field.NewFloat64(tableName, "goods_volume")
	_vslGoods.ShippingFeeType = field.NewInt(tableName, "shipping_fee_type")
	_vslGoods.ExtendCategoryID = field.NewString(tableName, "extend_category_id")
	_vslGoods.ExtendCategoryId1 = field.NewString(tableName, "extend_category_id_1")
	_vslGoods.ExtendCategoryId2 = field.NewString(tableName, "extend_category_id_2")
	_vslGoods.ExtendCategoryId3 = field.NewString(tableName, "extend_category_id_3")
	_vslGoods.SaleDate = field.NewInt(tableName, "sale_date")
	_vslGoods.CreateTime = field.NewInt(tableName, "create_time")
	_vslGoods.UpdateTime = field.NewInt(tableName, "update_time")
	_vslGoods.MinBuy = field.NewInt(tableName, "min_buy")
	_vslGoods.ItemNo = field.NewString(tableName, "item_no")
	_vslGoods.IsDistribution = field.NewInt(tableName, "is_distribution")
	_vslGoods.DistributionRule = field.NewInt(tableName, "distribution_rule")
	_vslGoods.IsBonusGlobal = field.NewInt(tableName, "is_bonus_global")
	_vslGoods.IsBonusArea = field.NewInt(tableName, "is_bonus_area")
	_vslGoods.IsBonusTeam = field.NewInt(tableName, "is_bonus_team")
	_vslGoods.BonusRule = field.NewInt(tableName, "bonus_rule")
	_vslGoods.DistributionRuleVal = field.NewString(tableName, "distribution_rule_val")
	_vslGoods.BonusType = field.NewInt8(tableName, "bonus_type")
	_vslGoods.BonusRuleVal = field.NewString(tableName, "bonus_rule_val")
	_vslGoods.TeambonusRuleVal = field.NewString(tableName, "teambonus_rule_val")
	_vslGoods.TaobaoID = field.NewString(tableName, "taobao_id")
	_vslGoods.ShortName = field.NewString(tableName, "short_name")
	_vslGoods.GoodsMedia = field.NewString(tableName, "goods_media")
	_vslGoods.CancleTimes = field.NewInt(tableName, "cancle_times")
	_vslGoods.CartType = field.NewInt8(tableName, "cart_type")
	_vslGoods.ValidType = field.NewInt8(tableName, "valid_type")
	_vslGoods.InvalidTime = field.NewInt(tableName, "invalid_time")
	_vslGoods.StoreList = field.NewString(tableName, "store_list")
	_vslGoods.ValidDays = field.NewInt(tableName, "valid_days")
	_vslGoods.IsWxcard = field.NewInt8(tableName, "is_wxcard")
	_vslGoods.GoodsAttrString = field.NewString(tableName, "goods_attr_string")
	_vslGoods.WxCardID = field.NewString(tableName, "wx_card_id")
	_vslGoods.VideoID = field.NewInt(tableName, "video_id")
	_vslGoods.PointDeductionMax = field.NewString(tableName, "point_deduction_max")
	_vslGoods.PointReturnMax = field.NewString(tableName, "point_return_max")
	_vslGoods.IllegalReason = field.NewString(tableName, "illegal_reason")
	_vslGoods.GoodsCount = field.NewInt(tableName, "goods_count")
	_vslGoods.SingleLimitBuy = field.NewInt(tableName, "single_limit_buy")
	_vslGoods.Buyagain = field.NewInt(tableName, "buyagain")
	_vslGoods.BuyagainLevelRule = field.NewInt(tableName, "buyagain_level_rule")
	_vslGoods.BuyagainRecommendType = field.NewInt(tableName, "buyagain_recommend_type")
	_vslGoods.BuyagainDistributionVal = field.NewString(tableName, "buyagain_distribution_val")
	_vslGoods.GjpGoodsID = field.NewInt(tableName, "gjp_goods_id")
	_vslGoods.Wurl = field.NewString(tableName, "wurl")
	_vslGoods.WplatForm = field.NewString(tableName, "wplatForm")
	_vslGoods.ForStore = field.NewInt8(tableName, "for_store")
	_vslGoods.IsGoodsPosterOpen = field.NewInt8(tableName, "is_goods_poster_open")
	_vslGoods.PosterData = field.NewString(tableName, "poster_data")
	_vslGoods.PxType = field.NewInt8(tableName, "px_type")
	_vslGoods.ElectroncardBaseID = field.NewInt(tableName, "electroncard_base_id")
	_vslGoods.DeliveryType = field.NewInt8(tableName, "delivery_type")
	_vslGoods.EvaluateGivePoint = field.NewString(tableName, "evaluate_give_point")
	_vslGoods.AreaBonus = field.NewString(tableName, "area_bonus")
	_vslGoods.GlobalBonus = field.NewString(tableName, "global_bonus")
	_vslGoods.GlobalBonusChoose = field.NewInt(tableName, "global_bonus_choose")
	_vslGoods.GlobalBonusCalculation = field.NewInt(tableName, "global_bonus_calculation")
	_vslGoods.AreaBonusChoose = field.NewInt(tableName, "area_bonus_choose")
	_vslGoods.AreaBonusCalculation = field.NewInt(tableName, "area_bonus_calculation")
	_vslGoods.TeamBonusChoose = field.NewInt(tableName, "team_bonus_choose")
	_vslGoods.TeamBonusCalculation = field.NewInt(tableName, "team_bonus_calculation")
	_vslGoods.DistributionBonusChoose = field.NewInt(tableName, "distribution_bonus_choose")
	_vslGoods.DistributionBonusCalculation = field.NewInt(tableName, "distribution_bonus_calculation")
	_vslGoods.AreaList = field.NewString(tableName, "area_list")
	_vslGoods.PlusMember = field.NewInt8(tableName, "plus_member")
	_vslGoods.SupplierID = field.NewInt(tableName, "supplier_id")
	_vslGoods.PaymentType = field.NewInt8(tableName, "payment_type")
	_vslGoods.SupplierRebate = field.NewFloat64(tableName, "supplier_rebate")
	_vslGoods.ShopList = field.NewString(tableName, "shop_list")
	_vslGoods.ShopListSecond = field.NewString(tableName, "shop_list_second")
	_vslGoods.SupplierInfo = field.NewInt(tableName, "supplier_info")
	_vslGoods.SupplierGoodsID = field.NewInt(tableName, "supplier_goods_id")
	_vslGoods.SupplierOperation = field.NewInt8(tableName, "supplier_operation")
	_vslGoods.SupplierPickCoverNums = field.NewInt(tableName, "supplier_pick_cover_nums")
	_vslGoods.SupplierPickStatus = field.NewInt8(tableName, "supplier_pick_status")
	_vslGoods.LockVersion = field.NewInt(tableName, "lock_version")
	_vslGoods.OriginalSkuIds = field.NewString(tableName, "original_sku_ids")
	_vslGoods.FormBaseID = field.NewInt(tableName, "form_base_id")
	_vslGoods.SubTitle = field.NewString(tableName, "sub_title")
	_vslGoods.ActivityPic = field.NewInt32(tableName, "activity_pic")

	_vslGoods.fillFieldMap()

	return _vslGoods
}

// vslGoods 商品表
type vslGoods struct {
	vslGoodsDo

	ALL                          field.Asterisk
	GoodsID                      field.Int     // 商品id(SKU)
	GoodsName                    field.String  // 商品名称
	WebsiteID                    field.Int     // 实例信息
	ShopID                       field.Int     // 店铺id    -1为供应商发布的商品
	CategoryID                   field.Int     // 商品分类id
	CategoryId1                  field.Int     // 一级分类id
	CategoryId2                  field.Int     // 二级分类id
	CategoryId3                  field.Int     // 三级分类id
	BrandID                      field.Int     // 品牌id
	GroupIDArray                 field.String  // 店铺分类id 首尾用,隔开
	PromotionType                field.Int8    // 促销类型 0无促销，1秒杀，2团购, 3预售, 4砍价，5限时折扣
	PromoteID                    field.Int     // 促销活动ID
	GoodsType                    field.Int8    // 实物或虚拟商品标志 1实物商品 0计时计次商品 3虚拟商品 2 F码商品 4知识付费  5电子卡密
	MarketPrice                  field.Float64 // 市场价
	Price                        field.Float64 // 商品原价格
	PromotionPrice               field.Float64 // 商品促销价格
	CostPrice                    field.Float64 // 成本价
	PointExchangeType            field.Int8    // 积分兑换类型 0 非积分兑换 1 只能积分兑换
	PointExchange                field.Int     // 积分兑换
	GivePoint                    field.Int     // 购买商品赠送积分
	IsMemberDiscount             field.Int     // 参与会员折扣
	ShippingFee                  field.Float64 // 统一运费
	ShippingFeeID                field.Int     // 售卖区域id 物流模板id  vsl_order_shipping_fee 表id
	Stock                        field.Int     // 商品库存
	MaxBuy                       field.Int     // 限购 0 不限购
	LeastBuy                     field.Int     // 普通商品最低起购
	MaxBuyTime                   field.Int     // 限购设置的时间
	Clicks                       field.Int     // 商品点击数量
	MinStockAlarm                field.Int     // 库存预警值
	Sales                        field.Int     // 真实数量
	Collects                     field.Int     // 收藏数量
	Star                         field.Int8    // 好评星级
	Evaluates                    field.Int     // 评价数
	Shares                       field.Int     // 分享数
	ProvinceID                   field.Int     // 一级地区id
	CityID                       field.Int     // 二级地区id
	Picture                      field.Int     // 商品主图
	Keywords                     field.String  // 商品关键词
	Introduction                 field.String  // 商品简介，促销语
	Description                  field.String  // 商品详情
	QRcode                       field.String  // 商品二维码
	Code                         field.String  // 商家编号
	IsStockVisible               field.Int     // 页面不显示库存
	IsPromotion                  field.Int     // 是否促销 1:是
	IsShippingFree               field.Int     // 是否包邮 1: 是
	IsHot                        field.Int     // 是否热销商品
	IsRecommend                  field.Int     // 是否推荐
	IsNew                        field.Int     // 是否新品
	IsPreSale                    field.Int
	IsBill                       field.Int     // 是否开具增值税发票 1是，0否
	State                        field.Int8    // 商品状态 0下架，1正常，10违规（禁售），11待审核，12审核不通过
	Sort                         field.Int     // 排序
	ImgIDArray                   field.String  // 商品图片序列
	SkuImgArray                  field.String  // 商品sku应用图片列表  属性,属性值，图片ID
	MatchPoint                   field.Float32 // 实物与描述相符（根据评价计算）
	MatchRatio                   field.Float32 // 实物与描述相符（根据评价计算）百分比
	RealSales                    field.Int     // 虚拟销量
	GoodsAttributeID             field.Int     // 商品类型
	GoodsSpecFormat              field.String  // 商品规格
	GoodsWeight                  field.Float64 // 商品重量
	GoodsVolume                  field.Float64 // 商品体积
	ShippingFeeType              field.Int     // 运费类型：0免运费，1统一运费，2选择模板
	ExtendCategoryID             field.String
	ExtendCategoryId1            field.String
	ExtendCategoryId2            field.String
	ExtendCategoryId3            field.String
	SaleDate                     field.Int    // 上下架时间
	CreateTime                   field.Int    // 商品添加时间
	UpdateTime                   field.Int    // 商品编辑时间
	MinBuy                       field.Int    // (渠道商、门店)最少买几件
	ItemNo                       field.String // 商品货号
	IsDistribution               field.Int    // 是否参与分销
	DistributionRule             field.Int    // 独立分销规则是否开启
	IsBonusGlobal                field.Int    // 是否参与全球分红
	IsBonusArea                  field.Int    // 是否参与区域分红
	IsBonusTeam                  field.Int    // 是否参与团队分红
	BonusRule                    field.Int    // 独立分红规则是否开启
	DistributionRuleVal          field.String // 独立分销规则
	BonusType                    field.Int8   // //1-独立分红比例  2-独立分红固定金额
	BonusRuleVal                 field.String // 独立分红规则
	TeambonusRuleVal             field.String // //团队分红商品独立规则：比例/金额
	TaobaoID                     field.String // 淘宝商品id
	ShortName                    field.String // 简称
	GoodsMedia                   field.String // 商品视频
	CancleTimes                  field.Int    // 核销次数
	CartType                     field.Int8   // 卡包类型 1:单卡  2:多卡
	ValidType                    field.Int8   // 有效类型 1:固定天数 2:过期时间
	InvalidTime                  field.Int    // 失效时间
	StoreList                    field.String // 核销门店
	ValidDays                    field.Int    // 有效天数
	IsWxcard                     field.Int8   // 微信卡券:1 开启   2:关闭
	GoodsAttrString              field.String // 商品属性
	WxCardID                     field.String // 微信卡券ID
	VideoID                      field.Int    // 视频id
	PointDeductionMax            field.String // 积分最大抵扣
	PointReturnMax               field.String // 购物返积分
	IllegalReason                field.String // 审核不通过/违规下架 原因
	GoodsCount                   field.Int    // 商品数量，用于运费模板
	SingleLimitBuy               field.Int    // 单次限购
	Buyagain                     field.Int
	BuyagainLevelRule            field.Int
	BuyagainRecommendType        field.Int
	BuyagainDistributionVal      field.String
	GjpGoodsID                   field.Int     // 管家婆ERP定义的商品id，对接了管家婆ERP才会有
	Wurl                         field.String  // 商品外链
	WplatForm                    field.String  // 商品外来源
	ForStore                     field.Int8    // 门店快捷收银商品, 0否,1是
	IsGoodsPosterOpen            field.Int8    // //是否开启独立商品海报 0-否 1-是。
	PosterData                   field.String  // //商品海报内容
	PxType                       field.Int8    // //海报的像素 1- 640*1008 2- 1080*1920
	ElectroncardBaseID           field.Int     // 电子卡密商品选择的卡密库id
	DeliveryType                 field.Int8    // 发货设置  1:自动发货  2:自动发货并确认收货  3:自动发货并订单完成  4:手动发货
	EvaluateGivePoint            field.String  // 好评送积分的数量
	AreaBonus                    field.String  // 独立区域分红规则
	GlobalBonus                  field.String  // 独立全球分红规则
	GlobalBonusChoose            field.Int     // 1开启独立结算节点
	GlobalBonusCalculation       field.Int     // 全球分红独立结算节点
	AreaBonusChoose              field.Int     // 1开启独立结算节点
	AreaBonusCalculation         field.Int     // 区域分红独立结算节点
	TeamBonusChoose              field.Int     // 1开启独立结算节点
	TeamBonusCalculation         field.Int     // 团队分红独立结算节点
	DistributionBonusChoose      field.Int     // 1开启独立结算节点
	DistributionBonusCalculation field.Int     // 团队分红独立结算节点
	AreaList                     field.String  // 限购地区（省、市、区）
	PlusMember                   field.Int8    // 是否开启plus会员价  1：开启   0：关闭
	SupplierID                   field.Int     // 供应商id
	PaymentType                  field.Int8    // 供应商商品的结算方式  1：成本价  2：扣除佣金
	SupplierRebate               field.Float64 // 供应商商品的分佣比例
	ShopList                     field.String  // 供应商商品被哪些店铺上架过  多个店铺用，分隔
	ShopListSecond               field.String  // 供应商商品重新编辑后，哪些店铺已经挑选过该商品。用，分隔。用于供销市场的判断同时展示店铺原有商品以及新编辑商品
	SupplierInfo                 field.Int     // 归属于哪个供应商
	SupplierGoodsID              field.Int     // 上架供应商商品时的供应商商品id
	SupplierOperation            field.Int8    // 供应端的操作   1：删除商品   2：下架商品
	SupplierPickCoverNums        field.Int     // 已选该商品店铺重新挑选覆盖次数
	SupplierPickStatus           field.Int8    // 供应商商品被挑选状态 0初始化1已编辑2重新编辑（只有已挑选店铺数等于重新挑选数，该值才会重置为0）
	LockVersion                  field.Int     // //创建订单乐观锁标识
	OriginalSkuIds               field.String  // 商品创建时原始sku_id用,分割。（供应商重新编辑规格后，可能会删掉原来的规格，所以记录该值为了店铺端重新使用该商品覆盖原有商品数据时候，循环该值去删掉原来关联的商品规格数据，重新复制新的供应商规格数据）
	FormBaseID                   field.Int     // 表单id
	SubTitle                     field.String  // 副标题
	ActivityPic                  field.Int32   // 活动图

	fieldMap map[string]field.Expr
}

func (v vslGoods) Table(newTableName string) *vslGoods {
	v.vslGoodsDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v vslGoods) As(alias string) *vslGoods {
	v.vslGoodsDo.DO = *(v.vslGoodsDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *vslGoods) updateTableName(table string) *vslGoods {
	v.ALL = field.NewAsterisk(table)
	v.GoodsID = field.NewInt(table, "goods_id")
	v.GoodsName = field.NewString(table, "goods_name")
	v.WebsiteID = field.NewInt(table, "website_id")
	v.ShopID = field.NewInt(table, "shop_id")
	v.CategoryID = field.NewInt(table, "category_id")
	v.CategoryId1 = field.NewInt(table, "category_id_1")
	v.CategoryId2 = field.NewInt(table, "category_id_2")
	v.CategoryId3 = field.NewInt(table, "category_id_3")
	v.BrandID = field.NewInt(table, "brand_id")
	v.GroupIDArray = field.NewString(table, "group_id_array")
	v.PromotionType = field.NewInt8(table, "promotion_type")
	v.PromoteID = field.NewInt(table, "promote_id")
	v.GoodsType = field.NewInt8(table, "goods_type")
	v.MarketPrice = field.NewFloat64(table, "market_price")
	v.Price = field.NewFloat64(table, "price")
	v.PromotionPrice = field.NewFloat64(table, "promotion_price")
	v.CostPrice = field.NewFloat64(table, "cost_price")
	v.PointExchangeType = field.NewInt8(table, "point_exchange_type")
	v.PointExchange = field.NewInt(table, "point_exchange")
	v.GivePoint = field.NewInt(table, "give_point")
	v.IsMemberDiscount = field.NewInt(table, "is_member_discount")
	v.ShippingFee = field.NewFloat64(table, "shipping_fee")
	v.ShippingFeeID = field.NewInt(table, "shipping_fee_id")
	v.Stock = field.NewInt(table, "stock")
	v.MaxBuy = field.NewInt(table, "max_buy")
	v.LeastBuy = field.NewInt(table, "least_buy")
	v.MaxBuyTime = field.NewInt(table, "max_buy_time")
	v.Clicks = field.NewInt(table, "clicks")
	v.MinStockAlarm = field.NewInt(table, "min_stock_alarm")
	v.Sales = field.NewInt(table, "sales")
	v.Collects = field.NewInt(table, "collects")
	v.Star = field.NewInt8(table, "star")
	v.Evaluates = field.NewInt(table, "evaluates")
	v.Shares = field.NewInt(table, "shares")
	v.ProvinceID = field.NewInt(table, "province_id")
	v.CityID = field.NewInt(table, "city_id")
	v.Picture = field.NewInt(table, "picture")
	v.Keywords = field.NewString(table, "keywords")
	v.Introduction = field.NewString(table, "introduction")
	v.Description = field.NewString(table, "description")
	v.QRcode = field.NewString(table, "QRcode")
	v.Code = field.NewString(table, "code")
	v.IsStockVisible = field.NewInt(table, "is_stock_visible")
	v.IsPromotion = field.NewInt(table, "is_promotion")
	v.IsShippingFree = field.NewInt(table, "is_shipping_free")
	v.IsHot = field.NewInt(table, "is_hot")
	v.IsRecommend = field.NewInt(table, "is_recommend")
	v.IsNew = field.NewInt(table, "is_new")
	v.IsPreSale = field.NewInt(table, "is_pre_sale")
	v.IsBill = field.NewInt(table, "is_bill")
	v.State = field.NewInt8(table, "state")
	v.Sort = field.NewInt(table, "sort")
	v.ImgIDArray = field.NewString(table, "img_id_array")
	v.SkuImgArray = field.NewString(table, "sku_img_array")
	v.MatchPoint = field.NewFloat32(table, "match_point")
	v.MatchRatio = field.NewFloat32(table, "match_ratio")
	v.RealSales = field.NewInt(table, "real_sales")
	v.GoodsAttributeID = field.NewInt(table, "goods_attribute_id")
	v.GoodsSpecFormat = field.NewString(table, "goods_spec_format")
	v.GoodsWeight = field.NewFloat64(table, "goods_weight")
	v.GoodsVolume = field.NewFloat64(table, "goods_volume")
	v.ShippingFeeType = field.NewInt(table, "shipping_fee_type")
	v.ExtendCategoryID = field.NewString(table, "extend_category_id")
	v.ExtendCategoryId1 = field.NewString(table, "extend_category_id_1")
	v.ExtendCategoryId2 = field.NewString(table, "extend_category_id_2")
	v.ExtendCategoryId3 = field.NewString(table, "extend_category_id_3")
	v.SaleDate = field.NewInt(table, "sale_date")
	v.CreateTime = field.NewInt(table, "create_time")
	v.UpdateTime = field.NewInt(table, "update_time")
	v.MinBuy = field.NewInt(table, "min_buy")
	v.ItemNo = field.NewString(table, "item_no")
	v.IsDistribution = field.NewInt(table, "is_distribution")
	v.DistributionRule = field.NewInt(table, "distribution_rule")
	v.IsBonusGlobal = field.NewInt(table, "is_bonus_global")
	v.IsBonusArea = field.NewInt(table, "is_bonus_area")
	v.IsBonusTeam = field.NewInt(table, "is_bonus_team")
	v.BonusRule = field.NewInt(table, "bonus_rule")
	v.DistributionRuleVal = field.NewString(table, "distribution_rule_val")
	v.BonusType = field.NewInt8(table, "bonus_type")
	v.BonusRuleVal = field.NewString(table, "bonus_rule_val")
	v.TeambonusRuleVal = field.NewString(table, "teambonus_rule_val")
	v.TaobaoID = field.NewString(table, "taobao_id")
	v.ShortName = field.NewString(table, "short_name")
	v.GoodsMedia = field.NewString(table, "goods_media")
	v.CancleTimes = field.NewInt(table, "cancle_times")
	v.CartType = field.NewInt8(table, "cart_type")
	v.ValidType = field.NewInt8(table, "valid_type")
	v.InvalidTime = field.NewInt(table, "invalid_time")
	v.StoreList = field.NewString(table, "store_list")
	v.ValidDays = field.NewInt(table, "valid_days")
	v.IsWxcard = field.NewInt8(table, "is_wxcard")
	v.GoodsAttrString = field.NewString(table, "goods_attr_string")
	v.WxCardID = field.NewString(table, "wx_card_id")
	v.VideoID = field.NewInt(table, "video_id")
	v.PointDeductionMax = field.NewString(table, "point_deduction_max")
	v.PointReturnMax = field.NewString(table, "point_return_max")
	v.IllegalReason = field.NewString(table, "illegal_reason")
	v.GoodsCount = field.NewInt(table, "goods_count")
	v.SingleLimitBuy = field.NewInt(table, "single_limit_buy")
	v.Buyagain = field.NewInt(table, "buyagain")
	v.BuyagainLevelRule = field.NewInt(table, "buyagain_level_rule")
	v.BuyagainRecommendType = field.NewInt(table, "buyagain_recommend_type")
	v.BuyagainDistributionVal = field.NewString(table, "buyagain_distribution_val")
	v.GjpGoodsID = field.NewInt(table, "gjp_goods_id")
	v.Wurl = field.NewString(table, "wurl")
	v.WplatForm = field.NewString(table, "wplatForm")
	v.ForStore = field.NewInt8(table, "for_store")
	v.IsGoodsPosterOpen = field.NewInt8(table, "is_goods_poster_open")
	v.PosterData = field.NewString(table, "poster_data")
	v.PxType = field.NewInt8(table, "px_type")
	v.ElectroncardBaseID = field.NewInt(table, "electroncard_base_id")
	v.DeliveryType = field.NewInt8(table, "delivery_type")
	v.EvaluateGivePoint = field.NewString(table, "evaluate_give_point")
	v.AreaBonus = field.NewString(table, "area_bonus")
	v.GlobalBonus = field.NewString(table, "global_bonus")
	v.GlobalBonusChoose = field.NewInt(table, "global_bonus_choose")
	v.GlobalBonusCalculation = field.NewInt(table, "global_bonus_calculation")
	v.AreaBonusChoose = field.NewInt(table, "area_bonus_choose")
	v.AreaBonusCalculation = field.NewInt(table, "area_bonus_calculation")
	v.TeamBonusChoose = field.NewInt(table, "team_bonus_choose")
	v.TeamBonusCalculation = field.NewInt(table, "team_bonus_calculation")
	v.DistributionBonusChoose = field.NewInt(table, "distribution_bonus_choose")
	v.DistributionBonusCalculation = field.NewInt(table, "distribution_bonus_calculation")
	v.AreaList = field.NewString(table, "area_list")
	v.PlusMember = field.NewInt8(table, "plus_member")
	v.SupplierID = field.NewInt(table, "supplier_id")
	v.PaymentType = field.NewInt8(table, "payment_type")
	v.SupplierRebate = field.NewFloat64(table, "supplier_rebate")
	v.ShopList = field.NewString(table, "shop_list")
	v.ShopListSecond = field.NewString(table, "shop_list_second")
	v.SupplierInfo = field.NewInt(table, "supplier_info")
	v.SupplierGoodsID = field.NewInt(table, "supplier_goods_id")
	v.SupplierOperation = field.NewInt8(table, "supplier_operation")
	v.SupplierPickCoverNums = field.NewInt(table, "supplier_pick_cover_nums")
	v.SupplierPickStatus = field.NewInt8(table, "supplier_pick_status")
	v.LockVersion = field.NewInt(table, "lock_version")
	v.OriginalSkuIds = field.NewString(table, "original_sku_ids")
	v.FormBaseID = field.NewInt(table, "form_base_id")
	v.SubTitle = field.NewString(table, "sub_title")
	v.ActivityPic = field.NewInt32(table, "activity_pic")

	v.fillFieldMap()

	return v
}

func (v *vslGoods) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *vslGoods) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 140)
	v.fieldMap["goods_id"] = v.GoodsID
	v.fieldMap["goods_name"] = v.GoodsName
	v.fieldMap["website_id"] = v.WebsiteID
	v.fieldMap["shop_id"] = v.ShopID
	v.fieldMap["category_id"] = v.CategoryID
	v.fieldMap["category_id_1"] = v.CategoryId1
	v.fieldMap["category_id_2"] = v.CategoryId2
	v.fieldMap["category_id_3"] = v.CategoryId3
	v.fieldMap["brand_id"] = v.BrandID
	v.fieldMap["group_id_array"] = v.GroupIDArray
	v.fieldMap["promotion_type"] = v.PromotionType
	v.fieldMap["promote_id"] = v.PromoteID
	v.fieldMap["goods_type"] = v.GoodsType
	v.fieldMap["market_price"] = v.MarketPrice
	v.fieldMap["price"] = v.Price
	v.fieldMap["promotion_price"] = v.PromotionPrice
	v.fieldMap["cost_price"] = v.CostPrice
	v.fieldMap["point_exchange_type"] = v.PointExchangeType
	v.fieldMap["point_exchange"] = v.PointExchange
	v.fieldMap["give_point"] = v.GivePoint
	v.fieldMap["is_member_discount"] = v.IsMemberDiscount
	v.fieldMap["shipping_fee"] = v.ShippingFee
	v.fieldMap["shipping_fee_id"] = v.ShippingFeeID
	v.fieldMap["stock"] = v.Stock
	v.fieldMap["max_buy"] = v.MaxBuy
	v.fieldMap["least_buy"] = v.LeastBuy
	v.fieldMap["max_buy_time"] = v.MaxBuyTime
	v.fieldMap["clicks"] = v.Clicks
	v.fieldMap["min_stock_alarm"] = v.MinStockAlarm
	v.fieldMap["sales"] = v.Sales
	v.fieldMap["collects"] = v.Collects
	v.fieldMap["star"] = v.Star
	v.fieldMap["evaluates"] = v.Evaluates
	v.fieldMap["shares"] = v.Shares
	v.fieldMap["province_id"] = v.ProvinceID
	v.fieldMap["city_id"] = v.CityID
	v.fieldMap["picture"] = v.Picture
	v.fieldMap["keywords"] = v.Keywords
	v.fieldMap["introduction"] = v.Introduction
	v.fieldMap["description"] = v.Description
	v.fieldMap["QRcode"] = v.QRcode
	v.fieldMap["code"] = v.Code
	v.fieldMap["is_stock_visible"] = v.IsStockVisible
	v.fieldMap["is_promotion"] = v.IsPromotion
	v.fieldMap["is_shipping_free"] = v.IsShippingFree
	v.fieldMap["is_hot"] = v.IsHot
	v.fieldMap["is_recommend"] = v.IsRecommend
	v.fieldMap["is_new"] = v.IsNew
	v.fieldMap["is_pre_sale"] = v.IsPreSale
	v.fieldMap["is_bill"] = v.IsBill
	v.fieldMap["state"] = v.State
	v.fieldMap["sort"] = v.Sort
	v.fieldMap["img_id_array"] = v.ImgIDArray
	v.fieldMap["sku_img_array"] = v.SkuImgArray
	v.fieldMap["match_point"] = v.MatchPoint
	v.fieldMap["match_ratio"] = v.MatchRatio
	v.fieldMap["real_sales"] = v.RealSales
	v.fieldMap["goods_attribute_id"] = v.GoodsAttributeID
	v.fieldMap["goods_spec_format"] = v.GoodsSpecFormat
	v.fieldMap["goods_weight"] = v.GoodsWeight
	v.fieldMap["goods_volume"] = v.GoodsVolume
	v.fieldMap["shipping_fee_type"] = v.ShippingFeeType
	v.fieldMap["extend_category_id"] = v.ExtendCategoryID
	v.fieldMap["extend_category_id_1"] = v.ExtendCategoryId1
	v.fieldMap["extend_category_id_2"] = v.ExtendCategoryId2
	v.fieldMap["extend_category_id_3"] = v.ExtendCategoryId3
	v.fieldMap["sale_date"] = v.SaleDate
	v.fieldMap["create_time"] = v.CreateTime
	v.fieldMap["update_time"] = v.UpdateTime
	v.fieldMap["min_buy"] = v.MinBuy
	v.fieldMap["item_no"] = v.ItemNo
	v.fieldMap["is_distribution"] = v.IsDistribution
	v.fieldMap["distribution_rule"] = v.DistributionRule
	v.fieldMap["is_bonus_global"] = v.IsBonusGlobal
	v.fieldMap["is_bonus_area"] = v.IsBonusArea
	v.fieldMap["is_bonus_team"] = v.IsBonusTeam
	v.fieldMap["bonus_rule"] = v.BonusRule
	v.fieldMap["distribution_rule_val"] = v.DistributionRuleVal
	v.fieldMap["bonus_type"] = v.BonusType
	v.fieldMap["bonus_rule_val"] = v.BonusRuleVal
	v.fieldMap["teambonus_rule_val"] = v.TeambonusRuleVal
	v.fieldMap["taobao_id"] = v.TaobaoID
	v.fieldMap["short_name"] = v.ShortName
	v.fieldMap["goods_media"] = v.GoodsMedia
	v.fieldMap["cancle_times"] = v.CancleTimes
	v.fieldMap["cart_type"] = v.CartType
	v.fieldMap["valid_type"] = v.ValidType
	v.fieldMap["invalid_time"] = v.InvalidTime
	v.fieldMap["store_list"] = v.StoreList
	v.fieldMap["valid_days"] = v.ValidDays
	v.fieldMap["is_wxcard"] = v.IsWxcard
	v.fieldMap["goods_attr_string"] = v.GoodsAttrString
	v.fieldMap["wx_card_id"] = v.WxCardID
	v.fieldMap["video_id"] = v.VideoID
	v.fieldMap["point_deduction_max"] = v.PointDeductionMax
	v.fieldMap["point_return_max"] = v.PointReturnMax
	v.fieldMap["illegal_reason"] = v.IllegalReason
	v.fieldMap["goods_count"] = v.GoodsCount
	v.fieldMap["single_limit_buy"] = v.SingleLimitBuy
	v.fieldMap["buyagain"] = v.Buyagain
	v.fieldMap["buyagain_level_rule"] = v.BuyagainLevelRule
	v.fieldMap["buyagain_recommend_type"] = v.BuyagainRecommendType
	v.fieldMap["buyagain_distribution_val"] = v.BuyagainDistributionVal
	v.fieldMap["gjp_goods_id"] = v.GjpGoodsID
	v.fieldMap["wurl"] = v.Wurl
	v.fieldMap["wplatForm"] = v.WplatForm
	v.fieldMap["for_store"] = v.ForStore
	v.fieldMap["is_goods_poster_open"] = v.IsGoodsPosterOpen
	v.fieldMap["poster_data"] = v.PosterData
	v.fieldMap["px_type"] = v.PxType
	v.fieldMap["electroncard_base_id"] = v.ElectroncardBaseID
	v.fieldMap["delivery_type"] = v.DeliveryType
	v.fieldMap["evaluate_give_point"] = v.EvaluateGivePoint
	v.fieldMap["area_bonus"] = v.AreaBonus
	v.fieldMap["global_bonus"] = v.GlobalBonus
	v.fieldMap["global_bonus_choose"] = v.GlobalBonusChoose
	v.fieldMap["global_bonus_calculation"] = v.GlobalBonusCalculation
	v.fieldMap["area_bonus_choose"] = v.AreaBonusChoose
	v.fieldMap["area_bonus_calculation"] = v.AreaBonusCalculation
	v.fieldMap["team_bonus_choose"] = v.TeamBonusChoose
	v.fieldMap["team_bonus_calculation"] = v.TeamBonusCalculation
	v.fieldMap["distribution_bonus_choose"] = v.DistributionBonusChoose
	v.fieldMap["distribution_bonus_calculation"] = v.DistributionBonusCalculation
	v.fieldMap["area_list"] = v.AreaList
	v.fieldMap["plus_member"] = v.PlusMember
	v.fieldMap["supplier_id"] = v.SupplierID
	v.fieldMap["payment_type"] = v.PaymentType
	v.fieldMap["supplier_rebate"] = v.SupplierRebate
	v.fieldMap["shop_list"] = v.ShopList
	v.fieldMap["shop_list_second"] = v.ShopListSecond
	v.fieldMap["supplier_info"] = v.SupplierInfo
	v.fieldMap["supplier_goods_id"] = v.SupplierGoodsID
	v.fieldMap["supplier_operation"] = v.SupplierOperation
	v.fieldMap["supplier_pick_cover_nums"] = v.SupplierPickCoverNums
	v.fieldMap["supplier_pick_status"] = v.SupplierPickStatus
	v.fieldMap["lock_version"] = v.LockVersion
	v.fieldMap["original_sku_ids"] = v.OriginalSkuIds
	v.fieldMap["form_base_id"] = v.FormBaseID
	v.fieldMap["sub_title"] = v.SubTitle
	v.fieldMap["activity_pic"] = v.ActivityPic
}

func (v vslGoods) clone(db *gorm.DB) vslGoods {
	v.vslGoodsDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v vslGoods) replaceDB(db *gorm.DB) vslGoods {
	v.vslGoodsDo.ReplaceDB(db)
	return v
}

type vslGoodsDo struct{ gen.DO }

type IVslGoodsDo interface {
	gen.SubQuery
	Debug() IVslGoodsDo
	WithContext(ctx context.Context) IVslGoodsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IVslGoodsDo
	WriteDB() IVslGoodsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IVslGoodsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IVslGoodsDo
	Not(conds ...gen.Condition) IVslGoodsDo
	Or(conds ...gen.Condition) IVslGoodsDo
	Select(conds ...field.Expr) IVslGoodsDo
	Where(conds ...gen.Condition) IVslGoodsDo
	Order(conds ...field.Expr) IVslGoodsDo
	Distinct(cols ...field.Expr) IVslGoodsDo
	Omit(cols ...field.Expr) IVslGoodsDo
	Join(table schema.Tabler, on ...field.Expr) IVslGoodsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IVslGoodsDo
	RightJoin(table schema.Tabler, on ...field.Expr) IVslGoodsDo
	Group(cols ...field.Expr) IVslGoodsDo
	Having(conds ...gen.Condition) IVslGoodsDo
	Limit(limit int) IVslGoodsDo
	Offset(offset int) IVslGoodsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IVslGoodsDo
	Unscoped() IVslGoodsDo
	Create(values ...*fxshop.VslGoods) error
	CreateInBatches(values []*fxshop.VslGoods, batchSize int) error
	Save(values ...*fxshop.VslGoods) error
	First() (*fxshop.VslGoods, error)
	Take() (*fxshop.VslGoods, error)
	Last() (*fxshop.VslGoods, error)
	Find() ([]*fxshop.VslGoods, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.VslGoods, err error)
	FindInBatches(result *[]*fxshop.VslGoods, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*fxshop.VslGoods) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IVslGoodsDo
	Assign(attrs ...field.AssignExpr) IVslGoodsDo
	Joins(fields ...field.RelationField) IVslGoodsDo
	Preload(fields ...field.RelationField) IVslGoodsDo
	FirstOrInit() (*fxshop.VslGoods, error)
	FirstOrCreate() (*fxshop.VslGoods, error)
	FindByPage(offset int, limit int) (result []*fxshop.VslGoods, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IVslGoodsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (v vslGoodsDo) Debug() IVslGoodsDo {
	return v.withDO(v.DO.Debug())
}

func (v vslGoodsDo) WithContext(ctx context.Context) IVslGoodsDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v vslGoodsDo) ReadDB() IVslGoodsDo {
	return v.Clauses(dbresolver.Read)
}

func (v vslGoodsDo) WriteDB() IVslGoodsDo {
	return v.Clauses(dbresolver.Write)
}

func (v vslGoodsDo) Session(config *gorm.Session) IVslGoodsDo {
	return v.withDO(v.DO.Session(config))
}

func (v vslGoodsDo) Clauses(conds ...clause.Expression) IVslGoodsDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v vslGoodsDo) Returning(value interface{}, columns ...string) IVslGoodsDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v vslGoodsDo) Not(conds ...gen.Condition) IVslGoodsDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v vslGoodsDo) Or(conds ...gen.Condition) IVslGoodsDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v vslGoodsDo) Select(conds ...field.Expr) IVslGoodsDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v vslGoodsDo) Where(conds ...gen.Condition) IVslGoodsDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v vslGoodsDo) Order(conds ...field.Expr) IVslGoodsDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v vslGoodsDo) Distinct(cols ...field.Expr) IVslGoodsDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v vslGoodsDo) Omit(cols ...field.Expr) IVslGoodsDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v vslGoodsDo) Join(table schema.Tabler, on ...field.Expr) IVslGoodsDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v vslGoodsDo) LeftJoin(table schema.Tabler, on ...field.Expr) IVslGoodsDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v vslGoodsDo) RightJoin(table schema.Tabler, on ...field.Expr) IVslGoodsDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v vslGoodsDo) Group(cols ...field.Expr) IVslGoodsDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v vslGoodsDo) Having(conds ...gen.Condition) IVslGoodsDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v vslGoodsDo) Limit(limit int) IVslGoodsDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v vslGoodsDo) Offset(offset int) IVslGoodsDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v vslGoodsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IVslGoodsDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v vslGoodsDo) Unscoped() IVslGoodsDo {
	return v.withDO(v.DO.Unscoped())
}

func (v vslGoodsDo) Create(values ...*fxshop.VslGoods) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v vslGoodsDo) CreateInBatches(values []*fxshop.VslGoods, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v vslGoodsDo) Save(values ...*fxshop.VslGoods) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v vslGoodsDo) First() (*fxshop.VslGoods, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslGoods), nil
	}
}

func (v vslGoodsDo) Take() (*fxshop.VslGoods, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslGoods), nil
	}
}

func (v vslGoodsDo) Last() (*fxshop.VslGoods, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslGoods), nil
	}
}

func (v vslGoodsDo) Find() ([]*fxshop.VslGoods, error) {
	result, err := v.DO.Find()
	return result.([]*fxshop.VslGoods), err
}

func (v vslGoodsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*fxshop.VslGoods, err error) {
	buf := make([]*fxshop.VslGoods, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v vslGoodsDo) FindInBatches(result *[]*fxshop.VslGoods, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v vslGoodsDo) Attrs(attrs ...field.AssignExpr) IVslGoodsDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v vslGoodsDo) Assign(attrs ...field.AssignExpr) IVslGoodsDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v vslGoodsDo) Joins(fields ...field.RelationField) IVslGoodsDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v vslGoodsDo) Preload(fields ...field.RelationField) IVslGoodsDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v vslGoodsDo) FirstOrInit() (*fxshop.VslGoods, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslGoods), nil
	}
}

func (v vslGoodsDo) FirstOrCreate() (*fxshop.VslGoods, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*fxshop.VslGoods), nil
	}
}

func (v vslGoodsDo) FindByPage(offset int, limit int) (result []*fxshop.VslGoods, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v vslGoodsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v vslGoodsDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v vslGoodsDo) Delete(models ...*fxshop.VslGoods) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *vslGoodsDo) withDO(do gen.Dao) *vslGoodsDo {
	v.DO = *do.(*gen.DO)
	return v
}
